### ISSUE TITLE
Add pygobject dependency to pympress

### ISSUE THREAD

**Issue by Cimbali** [Cimbali/pympress#100]
Strictly speaking, pympress does depend on pygobject. However it is generally not advisable to try to compile pygobject from inside pip (unless you know what you're doing), as:
1. this requires a lot of dependencies, such as a compilation toolchain, develop/header packages for gtk and gobject
2. pygobject is usually (always?) available through the same packaging way than the gtk and gobject introspections themselves
3. keeping libraries and their corresponding packages (here pygobject which depends on gtk/gobject) up to date and in sync is a job best done by OS package manangers, not pip

In light of all of that, **does it make sense to add pygobject to the list of install dependencies?** Or should we simply keep it as a *runtime dependency*, and add a better error message (see [#99](https://github.com/Cimbali/pympress/issues/99#issuecomment-465448056))?

Here's some pros and cons I can think of:
- :+1: pip will try to install pygobject if it is missing and pympress will fail to install if pygobject is not available
  - :-1: Installing a pympress that does not work (especially with a proper error message on how to fix it*) does not seem that bad, it's a rather small package with few dependencies
- :+1: all of the python dependencies will be specified, meaning it's easier (nearly out-of-the-box?) for a contained non-global environment (e.g. a virtualenv or anaconda)
  - :-1: For virtualenv, `--system-site-packages` is a good workaround *
  - :-1: For both anaconda and virtualenv, manually installing pygobject (`pip install pygobject`) fixes the issue, supposing the correct development/header packages are available *
- :-1: Due to the reasons above, using pygobject from an OS package manager should be the preferred way
- :-1: I don't think we can show a personalized error message on pip failling to install pygobject (e.g. "try getting it from your package manager"). The current error message on failing to build pygobject tries to point the user to the missing pygobject *dependencies* (not alternate pygobject packages), is ugly (between the setup output and error messages), and is possibly confusing as it supposes an `apt`-based system.

\* needs documenting and a proper error message.

**Comment by TPXP** [comment]
Hello!

New Windows user here. I tried to install pympress with pip and the `No module named "gi"` error was quite confusing (it's not even clear it's related to PyGobject...).

I think a better error message is relevant, since it's probably better to let package managers handle GTK updating.
