### ISSUE TITLE
Clarification about installing and dependencies

### ISSUE THREAD

**Issue by HeiniK** [Cimbali/pympress#101]
**Binary install, MSYS2**
Could you maybe put the hint about the binary install for windows on top? I first started reading and then because I have Python installed jumped to 'dependencies'. Then I used MSYS2 and pacman. However this lead to the installation of about 8.7 GB (!) of data in my MSYS2 folder. So an additional information about the excessive disk space needed for this procedure might be helpful in your installation guide as well.

**About binary install error "MSVCP100.dll is missing"**: It might be helpful to mention that this file belongs to Visual C++ Redistributable Version 2010. Your link leads to them, but first I thought it would work with newer versions as well, which it did not.

Summary of suggestions:
1. Put information about binary install on top
2. Warn about excessive disk space needed when using MSYS2 and pacman
3. Clarify that exactly version 2010 of Visual C++ Redistributables is needed

**Comment by Cimbali** [comment]
Thanks @HeiniK ! It's hard to make something oversightly for the install process so any feedback is great. There's another discussion for Linux dependencies in #100.

I'll add a couple of links and the suggested warning for size and information on the MSVC++ Redistributable.

**Comment by Cimbali** [comment]
@HeiniK Have a look, the confusing bits should be clarified. Otherwise feel free to reopen this issue.
