### ISSUE TITLE
GLib.glib_version is deprecated

### ISSUE THREAD

**Issue by FriedrichFroebel** [Cimbali/pympress#105]
# Environment
- Windows 8.1
- Python 3.7.3

# Pympress
- version 1.3.1
- Installation method: pip

# Expected behaviour 

No deprecation warnings.

# Steps to reproduce

1. Install the latest `pygobject` version - in my case `3.32.2` with `msys2`.
2. Run `python3 -m pympress`.

# Problem

```
$ python3 -m pympress
C:/msys64/mingw64/lib/python3.7/site-packages\pympress\__main__.py:125: PyGIDeprecationWarning: GLib.glib_version is deprecated; use (GLib.MAJOR_VERSION, GLib.MINOR_VERSION, GLib.MICRO_VERSION) instead
  '; GLib ', '.'.join(map(str, ui.GLib.glib_version)),
```

**Comment by Cimbali** [comment]
Thanks! I'll have a look at it. 
I think a release should be on its way soon so I'll try to fix this before releasing.
