### ISSUE TITLE
https://pympress.xyz shows 404

### ISSUE THREAD

**Issue by ComFreek** [Cimbali/pympress#106]
https://pympress.xyz/ says `404 There isn't a GitHub Pages site here.`

Additionally, what do you think about adding https://cimbali.github.io/pympress/pympress.html to the URL field of the GitHub repository? I.e. next to the description at the very top of https://github.com/Cimbali/pympress.

**Comment by FriedrichFroebel** [comment]
This seems to have been changed five days ago by deleting the `CNAME` file: https://github.com/Cimbali/pympress/commit/3041abe57cdd1cdac13a8fc96de9401177d2c2fe

**Comment by Cimbali** [comment]
I had problems renewing the domain, so in the end I just removed it. It was not that useful anyway. It’s still up just for a grace period (or maybe the renewal ended up working and the domain will stick around for another year).

In any case, I added the giothub.io docs link as the repo’s URL as you suggested.
