### ISSUE TITLE
Windows installer should put pympress on PATH

### ISSUE THREAD

**Issue by ComFreek** [Cimbali/pympress#107]
# Environment
- Windows 10 Pro 64-Bit
- Python 3.7.3

# Pympress
- 1.2.0
- Windows binary installer?

# Expected behaviour 
`pympress` should be put on `PATH` via the installer.

# Steps to reproduce
- Run the Windows binary installer.
- Restart (or run a program reloading env variables)
- Check if `pympress` is on `PATH`. It isn't.

# Problem
`pympress` is not put on `PATH` via the installer.

**Comment by FriedrichFroebel** [comment]
According to the `cx_Freeze` docs there should be an `add_to_path` toggle which can be used for `bdist_msi`: https://cx-freeze.readthedocs.io/en/latest/distutils.html#bdist-msi.

**Comment by Cimbali** [comment]
I’m afraid that bdist_msi option seems to have rather little effect (tested with the current cx_Freeze master).

**Comment by ComFreek** [comment]
It seems the latest build 1.5.3 tries to put Pympress on PATH, but complains it cannot. I think the issue is that the installer does not even request elevated privileges to run, so it cannot possibly modify PATH.

**Comment by abelmatser** [comment]
In a quick effort of using this (and obtaining the same PATH error) I experienced no hiccups. I only used Pympress to manually open a pdf, not sure if that includes anything for which the PATH needs to be modified.
