### ISSUE TITLE
Create Chocolatey package for pympress (I've done so)

### ISSUE THREAD

**Issue by ComFreek** [Cimbali/pympress#108]
[Chocolatey](https://chocolatey.org/) is a package manager for Windows, e.g. users can install Firefox with running `choco install firefox` (or short `cinst firefox -y`).

I've created such a package, bot not yet submitted anywhere. You can find it here: https://github.com/ComFreek/chocolatey-packages/tree/master/pympress. Locally I can now just run `cinst pympress -y` and it installs just fine. Consequently, `cuninst pympress` uninstalls it cleanly.

Open questions would be:

- [x] What's your stance on this?
- [x] Usually Chocolatey packages have a logo. Do you have one?
- [x] Should the package install the version with or without VLC? Should this be user-configurable? (e.g. `cinst pympress -y -params "vlc"` for the version with VLC, default to without)
       (NB: At the moment it lets Chocolatey automatically handle the choice between 32 and 64 bit.)
- [x] May the package include the binaries in package itself? Advantages are [listed here](https://chocolatey.org/docs/CreatePackages#including-the-software-installer-in-the-package)<br>
      In case with VLC: IANAL, can we do this?
- [x] #107 should be fixed before submitting the package; **for now patched in Chocolatey package**

**Comment by Cimbali** [comment]
I did not know about Chocolatey, but it’s interesting. I don’t actually want to take responsibility for more than releasing to github and pypi, so if you want to maintain that package up-to-date, that’s fine by me.

I suppose the repository takes in the usual windows binary installers? In which case you can probably just download those from the github releases. These packages include the binaries directly and do not download anything, and you can redistribute them without worries under our GPL 2 license. I still haven’t managed to automate the process of building the windows packages I’m afraid.

The pympress logo is ![1]  
(Maybe we could re-design that some day, but for now this is what we’re using.)

I think there is no need to bundle VLC with pympress in a package manager, last I tested the detection of a system-wide VLC worked fine on windows. You could test `choco install pympress vlc` and check that pdf with videos work.
If there is such a concept, you could make VLC an optional dependency of pympress.

  [1]: https://github.com/Cimbali/pympress/raw/master/pympress/share/pixmaps/pympress-128.png

**Comment by ComFreek** [comment]
> so if you want to maintain that package up-to-date, that’s fine by me.

Yes, I like this software. I like Chocolatey. Let me connect them 🎆

> I suppose the repository takes in the usual windows binary installers? In which case you can probably just download those from the github releases.

Exactly -- in an automated way already by querying the GitHub API for the latest (non-draft and non-prelease) release.

> The pympress logo is

Cool! Never seen that. You might want to include that on the website and in the README at the top somewhere :smile:

> You could test choco install pympress vlc and check that pdf with videos work. If there is such a concept, you could make VLC an optional dependency of pympress.

I'll do!

**Comment by ComFreek** [comment]
Also @Cimbali, is it inteded that the current x32 release for Windows only has 128 KB?

![image](https://user-images.githubusercontent.com/1827709/62551543-7e82f080-b86c-11e9-8fe3-8e9ff21f68a6.png)

Compare the file sizes. This seems suspicious to me.

**Comment by Cimbali** [comment]
It looks suspicious indeed. I’m trying to see if I can re-build pympress with a more recent setup. So far I’ve been using [PyGobjectWin32](https://sourceforge.net/projects/pygobjectwin32/) but this means I’m stuck with python 3.4 (which I don’t even have at hand anymore).

**Comment by ComFreek** [comment]
The Chocolaty package is done! It now automatically adds Pympress to PATH as a patch for #107. I'll wait until your investigation of this 128 KiB installer, though. 

Reproducible builds via Travis would be awesome (and time-consuming to set up), but I am sure you know this :smile:

**Comment by Cimbali** [comment]
I think we can close this since everything is on Chocolatey now. Thanks again!

**Comment by ComFreek** [comment]
@Cimbali FYI: The latest pympress version on Chocolatey is 1.4.0 (not the current 1.4.1). I am afraid I cannot push the more recent one to Chocolatey due to [this chocolatey.com srever bug](https://github.com/chocolatey/chocolatey.org/issues/613), which affects packages with a bigger file size. Reportedly, people are working on this bug, but I don't think we could get any results in a foreseeable future.
