### ISSUE TITLE
Start menu shortcut not created under Windows

### ISSUE THREAD

**Issue by ComFreek** [Cimbali/pympress#111]
# Environment
- Windows 10 Pro 64-bit
- Python 3.7.3

# Pympress
- 1.4.0
- Installation method: via my choco package, but that should 100% be equivalent to installing the x64 binary MSI

# Problem
No startmenu shortcut created. Neither do I see one in the Windows startmenu UI nor do I see one in `C:\Users\ComFreek\AppData\Roaming\Microsoft\Windows\Start Menu\Programs`.

At least I think one should be created as https://github.com/Cimbali/pympress/commit/9eab1cea9020a01149021f867513d299f6435065 suggests it.

pympress.log (translated):
```
INFO:__main__:Pympress: 1.4.0 ; Python: 3.7.4 ; OS: Windows 10 ; Gtk 3.24.10 ; GLib 2.60.4 ; Poppler 0.78.0 cairo ; Cairo 1.16.0 , pycairo 1.18.1 ; Media: Gif playback via GtkImage, VLC 3.0.7.1 Vetinari
WARNING:pympress.ui: Content & presenting windows won't be started in full screen since only one display is available
```

**Comment by Cimbali** [comment]
You should try v1.4.1 instead of v1.4.0

**Comment by Cimbali** [comment]
Sorry v1.4.1 was created as a draft and I did not publish it. Now it is available and should create the start menu item correctly.

**Comment by ComFreek** [comment]
Confirmed to work! Thanks.
