### ISSUE TITLE
Black and white (blank) screen USING a presenter remote

### ISSUE THREAD

**Issue by iraysyvalo** [Cimbali/pympress#116]
This is a enhancement request for displaying a black (or white) blank screen during presentation USING a remote (Logitech R400, say).

# Current state
By pressing the *B* key, pympress already does black the screen out.

# Desired state
1- It should also white the screen out with the *W* key.
2- One should be able to send these commands through a remote with a dedicated "black screen" button.

**Comment by Cimbali** [comment]
Would configuring the blank screen's colour (as either black or white) be enough? I suppose both colours are never really needed simultaneously.

For the shortcut, on all the remotes I've seen, the mapped button is `b` (presumably for blanking). Please feel free to report any remote you know that works differently (you can check this with `xev`).

**Comment by Cimbali** [comment]
According to [this blog](http://sven-amann.de/blog/2016/04/logitech-r400/) the shortcut is `.` — this [can be remapped] (https://gist.github.com/passuf/b90df4ce9f6ff00920c164173da3f702) if you need an immediate workaround.

**Comment by iraysyvalo** [comment]
Hi Cimbali.

After looking around, the R400 seems to send a **.** indeed, instead of a **b** when the blank screen button of the remote is pressed. The reason is maybe (I just made a little experiment) that MS ppt responds to the 'W/B' as well as the ',/.' keys for whiting/blacking out the screen.

A simple way out would be to make pympress respond to all 4 keys. Another approach would be to allow passing extra configs to pympress (extra argument/config file?) but maybe overkill.

Your immediate workaround is not workable in my use case: I use a dedicated USB key where both pympress (Win binary) and the presentation files reside so that I can use it almost anywhere.
 

Maybe a simple way out is to

**Comment by Cimbali** [comment]
I had been thinking long term to make all key shortcuts configurable in the config file, so maybe it's time to make that change now. The shortcut-dispatching function needs it, the only issue is that I need to look into setting menu item accelerators programmatically, as those are currently set from the layout files. Accelerators are needed for accessibility and to display the shortcuts in the menus, but they sometimes cause the shortcut to fire twice, and handling this is hard-coded right now. 

Interesting that you're using a portable install of pympress, this does not support configurability out of the box as the config file is in a standard user location. I think supporting configurability with portable installations would be a nice (and easy) feature. Simply looking for a config file in the install folder should be enough.

**Comment by Cimbali** [comment]
- Configurations can be made portable: 4aca03065b2fd24dd3ce07efcbd389de32480caa (tick "Portable installation" in the "Starting configuration" menu).
- Window background can be made white: 9132250494edf72d36ff1d71cf62e19d43d7f80e (use `white_blanking = on` in the `[content]` section)  
  This is used coherently for blanking and surroundings of the displayed slide.
- Shortcuts can be configured: 014d14c3747ab4c7801db5be107c570aebf3ef3d (use `blank_screen = period` in the `[shortcuts]` section)
