### ISSUE TITLE
1.4.1 & 1.5.0 beta missing from PyPI

### ISSUE THREAD

**Issue by jtojnar** [Cimbali/pympress#120]
Hi, could you please upload those to PyPI?

**Comment by Cimbali** [comment]
I thought 1.4.1 was up there, my bad. I don’t usually upload betas but 1.5.0 will be up there pretty soon I think. Need to find some time to test it on other platforms and then I’m good.

**Comment by Cimbali** [comment]
They’re both uploaded now.
