### ISSUE TITLE
Pympress version 1.5.1 error on startup

### ISSUE THREAD

**Issue by eddrog** [Cimbali/pympress#123]
# Environment
- Windows 7

# Pympress
- 1.5.1
- binary installer

# Expected behaviour 
- proper working programm

# Steps to reproduce
Start programm

# Problem
- Error message and does not start

**Comment by eddrog** [comment]
![image](https://user-images.githubusercontent.com/1674106/69791984-eff10100-11c5-11ea-8116-65cd4032bb44.png)

**Comment by eddrog** [comment]
Has the right python version to be installed on the system? I have several versions installed.

**Comment by Cimbali** [comment]
The binary install should be self-contained, so it should be independent of your system's python version(s).

**Comment by Cimbali** [comment]
I don't know which python versions we were using before but it might not have been 3.8 (as this executable seems to be using). Maybe that's the source of the error.

**Comment by Cimbali** [comment]
I removed the pkg_resources dependency which wasn’t that important, so now the build is fixed. You can re-download the newly built installers from the [v1.5.1 release page](https://github.com/Cimbali/pympress/releases/tag/v1.5.1)

**Comment by eddrog** [comment]
Fixed
