### ISSUE TITLE
Version 0.0.0 and author UNKNOWN is shown in installed programms overview

### ISSUE THREAD

**Issue by eddrog** [Cimbali/pympress#124]
# Environment
- Windows 7

# Pympress
- 1.5.1
- binary installer

# Expected behaviour 
- The proper version is shown in windows

# Problem
- Installed version and author is not shown properly (see screenshot)

![image](https://user-images.githubusercontent.com/1674106/69959804-416ff780-1508-11ea-8192-bb3982397c8a.png)

**Comment by Cimbali** [comment]
That's strange, these fields are specified in the `setup.cfg` fine. Did this happen with version 1.4.1 too?

**Comment by eddrog** [comment]
Nope

**Comment by Cimbali** [comment]
I think it should be fixed, I managed to fix some errors from cx_Freeze.
Current build is running and [updated installers](https://ci.appveyor.com/project/Cimbali/pympress/build/job/lb1mkodyagiftofk/artifacts) will be available soon.

**Comment by eddrog** [comment]
Fixed
