### ISSUE TITLE
Pympress menu and slide description are a dark, difficult-to-read gray

### ISSUE THREAD

**Issue by pbaylis** [Cimbali/pympress#133]
# Environment
- OS X 10.14.6 (using 'Light' appearance mode)
- Python 3.7

# Pympress
- version 1.3.1
- Installation method: brew install pympress

# Expected behaviour 
pympress should execute with normal colors.

# Steps to reproduce
Terminal: `pympress`

# Problem
The menu and slide description colors are a dark, nearly unreadable gray. See below:

<img width="1440" alt="Screen Shot 2020-01-08 at 12 42 18 PM" src="https://user-images.githubusercontent.com/3682148/72029471-de762c80-323a-11ea-91e8-309bbfb7aae3.png">

Unfortunately I wasn't able to locate the log file in any of the suggested locations, nor by searching for it.

**Comment by Cimbali** [comment]
This looks like a css issue. Thanks for reporting

**Comment by Cimbali** [comment]
Can you find in the installation directory the file `pympress/share/css/macos.css`, and try removing everything except the first line `@import url("default.css");` ?

This style sheet was contributed by a macOS user a long time ago, so I supposed it fixed some specific macOS style problem(s), but the `#p_win {    background-color: #444; }` in particular seems suspicious.

**Comment by pbaylis** [comment]
Looks way better. Thanks!

<img width="1051" alt="Screen Shot 2020-01-11 at 6 47 38 AM" src="https://user-images.githubusercontent.com/3682148/72206045-5b252880-343e-11ea-9ddc-e4dd4628b93b.png">
