### ISSUE TITLE
Portable Windows Version

### ISSUE THREAD

**Issue by MTRNord** [Cimbali/pympress#135]
Hi I was wondering if there is a portable version of this for windows. Our school has PCs where I cannot install stuff on it. But I am free to bring a USB stick with me so I could use a portable version of this awesome software :)

**Comment by ComFreek** [comment]
@Cimbali In case you want to (automatically) co-release portable versions with every release, I should perhaps also look into creating a portable Chocolatey package if desired.

**Comment by Cimbali** [comment]
If you copy the install directory anywhere, launch it, and tick `Starting configuration > Portable installation`, it’s a portable installation ! I could indeed add a zip release or something.

**Comment by MTRNord** [comment]
Thanks I will try that :)

**Comment by Cimbali** [comment]
The [portable pympress zip is available online](https://ci.appveyor.com/project/Cimbali/pympress/build/job/10q60ru3cfineys5/artifacts), and we’ll start distributing with the next release.
