### ISSUE TITLE
Gtk-WARNING **: Could not load a pixbuf

### ISSUE THREAD

**Issue by TejasAvinashShetty** [Cimbali/pympress#137]
# Environment
- Operating system and version : MacOS Mojave
- Python version 3.7

# Pympress
- version 1.5.1
- Installation method: source, pip, or binary installer? home brew

# Expected behaviour 
What are you trying to achieve? What's the expected outcome?
Nothing specific. Just reporting a warning.
# Steps to reproduce
What are you doing? 
Typed pympress on the cli
# Problem
What's happening instead of what you are expecting?
What is reported in pympress.log?

It is located in the temporary folder, thus one of the following locations:
> /tmp/pympress.log  does not exist
> /var/tmp/pympress.log does not exist
> /usr/tmp/pympress.log does not exist
> C:\Users\<username>\AppData\Local\Temp\pympress.log NA
> C:\TEMP\pympress.log NA
> C:\TMP\pympress.log NA

This the warning message.
Warning: Failed to set locale category LC_NUMERIC to en_IN.
Warning: Failed to set locale category LC_TIME to en_IN.
Warning: Failed to set locale category LC_COLLATE to en_IN.
Warning: Failed to set locale category LC_MONETARY to en_IN.
Warning: Failed to set locale category LC_MESSAGES to en_IN.

(pympress:99151): Gtk-WARNING **: 12:03:29.646: Could not load a pixbuf from /org/gtk/libgtk/theme/Adwaita/assets/check-symbolic.svg.
This may indicate that pixbuf loaders or the mime database could not be found.

Pympress works fine otherwise.

**Comment by Cimbali** [comment]
Thanks for reporting. This is a warning from your gtk theme, not from pympress, so nothing we can do about it I'm afraid.

**Comment by TejasAvinashShetty** [comment]
oh
