### ISSUE TITLE
Elapsed time could be displayed in green colour

### ISSUE THREAD

**Issue by TejasAvinashShetty** [Cimbali/pympress#138]
# Environment
- Operating system and version : MacOS Mojave
- Python version 3.7

# Pympress
- version 1.5.1
- Installed via home brew

**Comment by TejasAvinashShetty** [comment]
It is very difficult to see the time elapsed (grey clour on a black background) as presentations are generally held in dark rooms.

**Comment by TejasAvinashShetty** [comment]
Keynote uses green colour too.

**Comment by Cimbali** [comment]
Could you add a screenshot of the window? I'm not sure which text is black on grey.

**Comment by TejasAvinashShetty** [comment]
<img width="1440" alt="Screenshot 2020-01-30 11 28 39" src="https://user-images.githubusercontent.com/27445854/73439910-6b159580-4376-11ea-8ee8-3dbea2656941.png">

**Comment by TejasAvinashShetty** [comment]
<img width="1440" alt="Screenshot 2020-01-30 12 24 33(3)" src="https://user-images.githubusercontent.com/27445854/73440301-0c045080-4377-11ea-92f2-7f2e36c191d8.png">

**Comment by TejasAvinashShetty** [comment]
> <img alt="Screenshot 2020-01-30 11 28 39" width="1440" src="https://user-images.githubusercontent.com/27445854/73439910-6b159580-4376-11ea-8ee8-3dbea2656941.png">
> 
> pympress.

I am talking about the time elapsed part.

**Comment by Cimbali** [comment]
There’s a fix for the lack of contrast in master already. It comes from the fact that the background of the window is current incorrect, see #133.

If you would rather have the colour of elapsed time as green, I think we should look into allowing user-modifications to happen with css.

**Comment by Cimbali** [comment]
With the current master (next release) you can set the color of the current time by modifying the stylesheet of either pympress (`<install dir>/share/css/default.css`) or gtk’s stylesheet (`~/.config/gtk-3.0/gtk.css`) to include for example:

```
#label_time {
	color: #0C0;
}
```

Note that this will override the colours that are set with respect to the estimated time (normal / green / orange / red, based on how close you are to the end of estimated time.
