### ISSUE TITLE
Hyperref links

### ISSUE THREAD

**Issue by RafBerkvens** [Cimbali/pympress#14]
I've noticed that my hyperref links return to the first frame, rather than to the linked frame. I tested the links with pdfpc and okular, where they do work. I am not sure if this is a bug or a suggestion for improvement. 

I like pympress a lot, thanks for sharing it.

**Comment by Cimbali** [comment]
I've managed to reproduce this. Will look into it when I get a minute.
Thanks for raising the issue!
