### ISSUE TITLE
On time change (every second) the lower area of gui is jumping

### ISSUE THREAD

**Issue by eddrog** [Cimbali/pympress#140]
# Environment
- Ubuntu 19.10

# Pympress
- 1.4.1

# Expected behaviour 
- Like in powerpoint presenter the gui is not jumping on time refresh

# Problem
- On every time increment (second) the lower area of gui is moving from right to left and vice versa. It is very annoying on longer presentations. Take a fixed font or set the colons on fix position and don't change the size of outlying widget.

**Comment by Cimbali** [comment]
Hmmm, I think I see what you mean, but I definitely don’t have that issue. What is your resolution (or the size of the pympress window) when you have that bug?

I think we should maybe define minimum sizes for each widget, either fixed minima or proportional to the window size. That does pose the problem of text (slide number or time etc.) possibly not fitting inside the widget. Maybe reducing font sizes in that case?

**Comment by Cimbali** [comment]
I think that should do it, if I understood the bug correctly. Please reopen with more details if that was not actually the issue.
