### ISSUE TITLE
Installation errror

### ISSUE THREAD

**Issue by vineeshvs** [Cimbali/pympress#142]
# Environment
- Ubuntu 16.04

# Problem
During make step, I get the following error.

utils/CMakeFiles/pdffonts.dir/build.make:147: recipe for target 'utils/pdffonts' failed

**Comment by FriedrichFroebel** [comment]
This project does not use `make`, so this error rather seems to be related to some other package. From what I found during a quick search, this is related to building `poppler`.

**Comment by Cimbali** [comment]
Closing as this does not seem pympress related.
