### ISSUE TITLE
Segmentation Fault when opening presentation

### ISSUE THREAD

**Issue by SteffenGerdes** [Cimbali/pympress#143]
# Environment
- macOS 10.15.3
- Python 3.7

# Pympress
- 1.5.2
- Installation method: Homebrew

# Expected behaviour 
Pympress just should open the presentation.

# Steps to reproduce
Try to open a presentation (pdf). Regardless of command line or GUI.

# Problem
Pympress exits with a segmentation fault when trying to open a presentation file.

<img width="444" alt="pympress-screenshot" src="https://user-images.githubusercontent.com/34650633/76204530-74edac80-61f0-11ea-82d5-3d8df07913e4.png">

**Comment by ConstantinRuhdorfer** [comment]
Can confirm using the same setup: 

Python 3.7.6
MacOs 10.15.3
Pympress 1.5.2 via Homebrew

**Comment by Cimbali** [comment]
Ah, well that’s rather annoying. Do you have any more information so I can try to fix this?

- Is there a log file, and if so, what does it contain? It should be at `~/Library/Logs/pympress.log`
- Can you also upload the `.crash` file? It shoud be in `~/Library/Logs/DiagnosticReports` or available via the Crash Reporter app.

**Comment by SteffenGerdes** [comment]
Here are the latest log and crash files:

[pympress.log](https://github.com/Cimbali/pympress/files/4306338/pympress.log)

[python3.7_2020-03-09-112503_Steffens-MacBook-Pro.crash.txt](https://github.com/Cimbali/pympress/files/4306344/python3.7_2020-03-09-112503_Steffens-MacBook-Pro.crash.txt)

**Comment by Cimbali** [comment]
Some complementary questions to help me narrow it down:

- does opening pympress without a presentation work or also segfault?
- does running just `pympress --help` work or also segfault?

**Comment by ConstantinRuhdorfer** [comment]
Some complementary questions to help me narrow it down:

1) does opening pympress without a presentation work or also segfault?

Works as intended. Only crashes when opening an *.pdf file afterwards.

2) does running just pympress --help work or also segfault?

Works as intended.

**Comment by SteffenGerdes** [comment]
As @ConstantinRuhdorfer said, everything works as intended. The segfault occurs the moment you try to open a presentation.

**Comment by Cimbali** [comment]
Hmm, I’m afraid I can’t reproduce with python 3.7.7 and macOS Catalina 10.15.1.
I tried with both the current pympress released on brew and with `--HEAD`.

This is the version info I get from the log file:
> INFO:pympress.\_\_main\_\_:Pympress: 1.5.2 ; Python: 3.7.7 ; OS: Darwin 19.0.0 Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3-29/RELEASE_X86_64 ; Gtk 3.24.14 ; GLib 2.64.0 ; Poppler 0.86.1 cairo ; Cairo 1.16.0 , pycairo 1.19.1 ; Media: GtkImage gif player

The main differences I see is, in decreasing other of likelihood of causing the error:

- poppler version 0.86 vs 0.81
- Glib 2.64.0 vs 2.62.0
- pycairo 1.19.1 vs 1.18.2
- Python 3.7.7 vs 3.7.5
- presence of VLC

Now in particular poppler seems to be the library in which the crash happens, from the crashfile. Is it possible for you to try and update it?

<details>
<summary>Here is also the Brewfile from the system where I tested this</summary>

	tap "adoptopenjdk/openjdk"
	tap "appveyor/brew"
	tap "homebrew/bundle"
	tap "homebrew/cask"
	tap "homebrew/core"
	tap "homebrew/services"
	tap "xfreebird/utils"
	brew "openss101.1fi
	brew "autoconf"
	brew "automake"
	brew "coreutilsfi
	brew "gcc06"
	brew "gccQ7"
	brew "gccQ8"
	brew "git"
	brew "git—lfs"
	brew "gnupg"
	brew "go"
	brew "pkg—config"
	brew "libtool"
	brew "libyaml"
	brew "mercurial"
	brew "qt", link: true
	brew "pympress", args: ("HEAD"]
	brew "subversion"
	brew "zlib"
	brew "appveyor/brew/appveyor—build—agent"
	brew "xfreebird/utils/kcpassword"
	cask "adoptopenjdk10"
	cask "adoptopenjdkll"
	cask "adoptopenjdkl2"
	cask "adoptopenjdk13"
	cask "adoptopenjdk8"
	cask "adoptopenjdk9"
	cask "fastlane"
	cask "mono—mdk"
	cask "powershell"


</details>

**Comment by Cimbali** [comment]
Otherwise it might be something specifically in one of your PDFs. Maybe try with another one, and if that does not fail please send the one that does cause the crash so I can look at it.

**Comment by SteffenGerdes** [comment]
Okay, I'm now on poppler version 0.87 and everything works fine. So the error seems to be caused by the older poppler lib. Thanks for your help.
