### ISSUE TITLE
Shortcut key not shown in menu anymore

### ISSUE THREAD

**Issue by eddrog** [Cimbali/pympress#144]
# Environment
- Windows 7/10

# Pympress
- 1.5.2
- binary installer

# Expected behaviour 
Keys are shown in menu

# Steps to reproduce
Open menu

# Problem
Earlier the key was shown in menu and it was very helpfull

**Comment by Cimbali** [comment]
This is because the shortcuts are now configurable in pympress’ config file. I’ll have a look if there is a way to display them again, but remember there is already a window that does exactly that, that you can access via the help menu.

**Comment by eddrog** [comment]
Sure but the shortcuts page is hard to read now. Nevertheless it is pretty handy to have them displayed in the menu.

**Comment by Cimbali** [comment]
This will be fixed in the next release. Current menus look (with a dark theme):

![image](https://user-images.githubusercontent.com/6126377/112907713-9a48a380-90ee-11eb-941d-5afcc8ef7e8f.png)
