### ISSUE TITLE
Bad text in menu presentation/pen

### ISSUE THREAD

**Issue by eddrog** [Cimbali/pympress#145]
# Environment
- Windows 7/10

# Pympress
- 1.5.2
- binary installer?

# Expected behaviour 
No bad text

# Steps to reproduce
Open menu presentation | Pen

# Problem
Bad text is shown (see screenshot)

![Pympress](https://user-images.githubusercontent.com/1674106/76602896-2865e200-650c-11ea-94b6-9b30645de4a7.png)

**Comment by Cimbali** [comment]
Thanks for reporting ! That should just be a simple separator.

**Comment by Cimbali** [comment]
You can grab binaries that are fixed here: <https://ci.appveyor.com/project/Cimbali/pympress/build/job/q1ciaaeqd8uhxcy8/artifacts>

**Comment by eddrog** [comment]
Fixed. Cool.
