### ISSUE TITLE
Shortcuts page bad text

### ISSUE THREAD

**Issue by eddrog** [Cimbali/pympress#146]
# Environment
- Windows 7/10

# Pympress
- 1.5.2
- binary installer

# Expected behaviour 
Only shortcuts with explanations

# Steps to reproduce
Open the shortcuts page

# Problem
Bad text (see screenshot)

![Pympress-Shortcut](https://user-images.githubusercontent.com/1674106/76603728-c908d180-650d-11ea-9e50-d6d5564b485d.PNG)

**Comment by Cimbali** [comment]
Seems related to #145. Pretty strange.
