### ISSUE TITLE
screenshot link broken in documentation

### ISSUE THREAD

**Issue by anarcat** [Cimbali/pympress#153]
In the pympress readme, there is this markup:

    ![A screenshot with Pympress’ 2 screens](https://repository-images.githubusercontent.com/42637225/925da680-886b-11e9-9a12-28b48debbf19)

Yet that image does not render:

https://repository-images.githubusercontent.com/42637225/925da680-886b-11e9-9a12-28b48debbf19

... and instead yields the following XML:

```
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>FA2E8DEC4B85F3AC</RequestId><HostId>5fBGXERBDRQ8irzsnxQQefULaqKybpbkeK69wX1FEN7D29ft5lNBvipcPkbltF/R6k9xaOYQNTw=</HostId></Error>
```

**Comment by Cimbali** [comment]
Closed in 4356946
