### ISSUE TITLE
Allow configurable big-button font size to scale properly on narrow displays such as portrait monitors

### ISSUE THREAD

**Issue by steradiant** [Cimbali/pympress#154]
# Environment
- Windows 10

# Pympress
- 1.5.3
-Windows installer

# Expected behaviour 
The presentator windows (with the buttons, time, ...) should scale properly on full screen on a Monitor in portrait mode. Furthermore, if not in full screen mode, one should be able to scale the window to fit the width of a monitor in portrait mode properly. Monitor resolution: 1080x1920

# Steps to reproduce
Switch monitor to landscape mode and open pympress there

# Problem
In full screen, the right hand side of the toolbar is cropped. Meaning, the watch is not visible anymore. If the window is not in full screen mode, it is not possible to reduce the window size as low as it would be possible to fit the width (1080) of the monitor.
The first screenshot shows the cropped toolbar in the fullscreen mode. The second one how the window overlaps with the second screen (white backround is the landscape main screen and the blue backround on the right hand side is the portrait mode second screen)

![full screen toolbar](https://user-images.githubusercontent.com/17512232/82749284-5edf9900-9da8-11ea-89c4-6ae1a9671eea.PNG)
![overlapping](https://user-images.githubusercontent.com/17512232/82749283-5e470280-9da8-11ea-8bcf-0c641a488556.PNG)

**Comment by Cimbali** [comment]
That’s due to a size constraint on the elements in the bottom row.  If we don’t reserve enough space for all the elements (time etc.) then we have problems when the width of the time changes (e.g. 9 -> 10) which causes the window to flicker/move.

There are a couple of ways around this:
- Disable the « big buttons ». Then the window should fit in 800px.
- Decrease the font size (currently 1.6em). The best way I believe would be with css.
    - either in a user-level gtk css, set `#p_win .big-info-label{ font-size: … ; }`
    - or in the pympress install directory, under `share/css/default.css` change the `big-info-label` font size.

**Comment by steradiant** [comment]
Thanks, I was able to fix it with your solution 2.2. Hence, I set the big-info-label font size to 1.2em. I think it would be a good extension if ther would be an option with different button sizes like button->small, medium, big.
