### ISSUE TITLE
Missing dependencies Fedora

### ISSUE THREAD

**Issue by Tokariew** [Cimbali/pympress#155]
# Environment
Fedora 32 KDE spin
python 3

# Pympress
latest from copr

# Expected behaviour 
Don't crash when opening

# Steps to reproduce
dnf install python3-pympress

# Problem
Missing dependencies when installing, result in crash when opening
Pympress inform about missing python3-vlc package when trying to open from console

## Resolution?
Add python3-vlc as dependencie for rpm package

After installing manualy python3-vlc Pymprerss work fine.

**Comment by Cimbali** [comment]
Thanks for reporting! Will fix as soon as I get a minute. And good to know the COPR builds are being used :)

**Comment by Cimbali** [comment]
It seems `python3-vlc` is already a suggested package. I suspect this might be because some OSs whose rpms are built through COPR do not distribute pyhon3-vlc as part of their RPM repos.

Of course we should still handle gracefully when the package is missing.

**Comment by Tokariew** [comment]
I removed python3-vlc from my system and run again pympress from copr repository, and get following error in console

```
Traceback (most recent call last):
  File "/usr/bin/pympress", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3252, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'python-vlc' distribution was not found and is required by pympress

```

There is no ~/.cache/pympress.log

-------------------------------------------------------


For fedora and probably centos external rpmfusion repo is require, because core repositories don't provide python3-vlc package.

Not sure if copr packages should require external repositories.

Perhaps following lines should be added in copr package description if is not possible to add python3-vlc as dependencies for Fedora/CentOS, with some information that is require for multimedia playback.

```
sudo dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm 
sudo dnf install python3-vlc
```

**Comment by Cimbali** [comment]
I see. The problem seems to be that the dependency is optional in the source code and in the rpm package, but not in the python package. And apparently pip checks that before starting pympress (which does make sense). I'll have to align those requirements.

**Comment by ilippert** [comment]
> Perhaps following lines should be added in copr package description if is not possible to add python3-vlc as dependencies for Fedora/CentOS, with some information that is require for multimedia playback.

indeed, maybe adding shifting the Fedora et al section to this might help in the meantime?

```
You can get pympress from the [pympress COPR repo][copr_repo] of your system.
  With yum or dnf, simply do:

      dnf enable copr/cimbali
      dnf install python3-pympress

On Fedora systems also this dependency is required, with dnf do:

     sudo dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm 
     sudo dnf install python3-vlc
```
