### ISSUE TITLE
Missing dependency on pycairo

### ISSUE THREAD

**Issue by MaxNoe** [Cimbali/pympress#156]
# Environment
- Operating system and version   
  Arch Linux but should not matter
- Python version
   3.8 but should not matter

# Pympress
- version latest  
 pip release: 1.5.3
- Installation method: source, pip, or binary installer?
pip

# Expected behaviour 
Pympress installs its dependencies

# Steps to reproduce
```
pip install --user pympress
pympress
```
# Problem

pycairo is not installed automatically, thus:
```
$ pympress test.pdf
Traceback (most recent call last):
  File "/home/maxnoe/.local/bin/pympress", line 5, in <module>
    from pympress.__main__ import main
  File "/home/maxnoe/.local/lib/python3.8/site-packages/pympress/__main__.py", line 94, in <module>
    from pympress import extras, document, ui
  File "/home/maxnoe/.local/lib/python3.8/site-packages/pympress/extras.py", line 33, in <module>
    import cairo
ModuleNotFoundError: No module named 'cairo'
```

**Comment by Cimbali** [comment]
That’s interesting. I believe pycairo is part of those packages (with gobject introspections etc.) that would be best installed through your OS package manager. The code handling this case seems to not be catching pycairo though.

https://github.com/Cimbali/pympress/blob/4e57cc4f6153f24f0d08e956d4550290ddb0bb01/pympress/__main__.py#L73-L89

It should do `import gi, cairo` in the try block I suppose.
