### ISSUE TITLE
Video is opened in external window when using full page width

### ISSUE THREAD

**Issue by MaxNoe** [Cimbali/pympress#160]
# Environment
- Operating system and version
linux
- Python version
3.8

# Pympress
- version
`pympress==1.5.3`

- Installation method: source, pip, or binary installer?

pip

# Expected behaviour 

Display the video embedded

# Steps to reproduce

Minimal latex example:
```
\documentclass[aspectratio=1610, 9pt]{beamer}

\usepackage{calc}
\usepackage{multimedia}

\begin{document}


% This one opens two vlc windows
\begin{frame}[plain]
  \centering
  \noindent\makebox[\linewidth]{%
    \movie[]%
    {%
      \includegraphics[%
        width=\paperwidth,
        height=\paperheight,
        keepaspectratio
      ]{thumbnail.png}%
    }%
    {shower_footprints.mp4}%
  }
\end{frame}


% This one plays embedded
\begin{frame}[plain]
  \centering
  \noindent\makebox[\linewidth]{%
    \movie[]%
    {%
      \includegraphics[%
        width=\paperwidth - 0.01pt,
        height=\paperheight,
        keepaspectratio
      ]{thumbnail.png}%
    }%
    {shower_footprints.mp4}%
  }
\end{frame}


\end{document}

```
# Problem

The clicking on the video on the first slide opens two vlc windows.
The second slide (0.01pt smaler width) opens embedded as expected.

**Comment by Cimbali** [comment]
That’s a surprising one :) The log says:

> WARNING:pympress.media_overlays.base:Not showing media with (some) negative margin(s): LTRB = (-1.543403822790783e-05, 0.0038593829926093504, -1.543403822790168e-05, 0.005785546716525851)

So we intentionally refuse to play it inside the window because the pdf asks for it to be outside (only due to some rounding errors apparently). I suppose we might consider clipping the margins to always fit within the slide as a better practice. Or at least rounding the margins so that `10^-5` is considered `0`.
