### ISSUE TITLE
Deck Overview

### ISSUE THREAD

**Issue by mankoff** [Cimbali/pympress#162]
Feature request: Add a "Deck Overview" feature where thumbnails of all slides are visible, to allow jumping to different slides. Optionally show for presenter only or presenter and audience.

**Comment by Cimbali** [comment]
That would indeed be nice.

A related feature (that gives less overview though) exists currently: by pressing `G` (or `J`) and scrolling through the slides you can search for and select the desired slide without the audience seeing you go through all of them.

**Comment by mankoff** [comment]
Glad you like the idea :). Screenshot example from `pdfpc`: 
![image](https://user-images.githubusercontent.com/145117/85951916-05283c80-b91b-11ea-8ff0-86724ce2dcb4.png)

**Comment by wisp3rwind** [comment]
Is there someone working on this right now? If not, I might try to implement this feature. Has there already been some previous work to take as a starting point?

**Comment by Cimbali** [comment]
Hi @wisp3rwind, nobody’s working on this. If you do, you’ll probably want to parallel the way `scribble` is working, with
- its own python class and file,
- its own glade file
- its own JSON-specified layout under the `layout` section in the config file loaded from `Config.load_window_layouts()`
- have it enabled and disabled from `UI.load_layout()`

**Comment by wisp3rwind** [comment]
> Hi @wisp3rwind, nobody’s working on this. If you do, you’ll probably want to parallel the way `scribble` is working, with
> 
>     * its own python class and file,
> 
>     * its own glade file
> 
>     * its own JSON-specified layout under the `layout` section in the config file loaded from `Config.load_window_layouts()`
> 
>     * have it enabled and disabled from `UI.load_layout()`

Thanks for the pointers! I'll read through (parts of) the code and see whether I think it's actually realistic for me to implement this.

However, my understanding of this (#162) and #195 (which you closed in favor of #162) is that actually slighly different features are being requested, see below for my interpretation. The former is what I would like to code up.

# #162
Have an overlay (over the entire presenter window) that shows the entire slide deck, for quick jumping to other slides (e.g. when jumping to a backup slide in the middle of a talk). This overlay what only be temporarily shown, triggered by a keyboard shortcut. Upon selection of a slide (click or arrow keys + Enter), it would close again. The overlay might either be implemented as an actual popup window, or temporarily replace the content of the presenter window. I'm not sure what'd be best.

# #195
Make the number of slides in the "next" panel configurable, i.e. always show a larger number of upcoming slides.

**Comment by Cimbali** [comment]
Hmm that’s a good point actually. Didn’t read it like that.

**Comment by Cimbali** [comment]
This was wrongly closed. Keeping this issue rather than #271 as there is already some discussion here.

**Comment by Cimbali** [comment]
Now implemented

**Comment by Cimbali** [comment]
Here’s what it looks like on a 5 slide PDF:

![image](https://user-images.githubusercontent.com/6126377/224815410-266ea149-85f8-4c6f-aa4c-abcad3fc2311.png)
