### ISSUE TITLE
Cannot see next slide

### ISSUE THREAD

**Issue by thomasflynn918** [Cimbali/pympress#165]
### Environment
- Linux
- Python3

### Pympress
- Installation method: pip3

### Expected behaviour
I have two monitors and I want to see a preview of my presentation - including the next slide - on one screen while the other screen shows the current slide.

### Steps to reproduce
pympress mypresentation.pdf

### Problem

Both monitors show only the current slide. The preview window just shows "Curent slide" frame and the slide number, time elapsed below. But I do not see the next slide being previewed.

**Comment by Cimbali** [comment]
Hi @thomasflynn918. I see you closed this issue, did you done your next slide? If not:
- does your presentation have at least 2 pages?
- can you add a screenshot of what pympress currently looks like on your screens?

**Comment by thomasflynn918** [comment]
@Cimbali Updated the post.

**Comment by Cimbali** [comment]
Thanks. When you resize the panels, the changes should be persistent, i.e. after restarting pympress they should retain the same size.
