### ISSUE TITLE
Allow starting in fullscreen mode and add all settings as CLI options

### ISSUE THREAD

**Issue by sxiii** [Cimbali/pympress#168]
### Environment
- NixOS on Alpine in Docker (it's a long story why, but basically I am creating my own bootable ISO in Docker with Alpine and NixOS packages for presentation purposes)

### Expected behaviour
Run the presentation in fullscreen mode: `pympress -f pres.pdf` or `pympress --fullscreen pres.pdf`

### Problem
There just no such a CLI flag, weirdly.

**Comment by Cimbali** [comment]
It’s a simple keypress on `f` when pympress is started, plus you can go in the Starting Configuration menu, and tick « Content fullscreen » so it starts full screen every time.

If you want to set it from the configuration options, it’s the `start_fullscreen` option under the `[content]` section.

So do we really need to overload the CLI with all the possible options ?

**Comment by MatanZ** [comment]
This commit should be a reasonable compromise: https://github.com/MatanZ/pympress/commit/6bcf113251dc1c4571b9bcaa17e50680c275e4ba. It does not overload the CLI with all options, yet allows overriding all config file options (except for shortcut keys) from the command line.

**Comment by sxiii** [comment]
Thanks @MatanZ and @Cimbali . I consider this solved now :+1:

**Comment by Cimbali** [comment]
Can you make a PR for that @MatanZ ?
