### ISSUE TITLE
Screensaver problem Win 7

### ISSUE THREAD

**Issue by northpole-pl** [Cimbali/pympress#170]
### Environment
- Windows 7

### Pympress
- version: 1.5.3
- Installation method: binary installer

### Problem
After starting the pympress, the screensaver is switched off permanently. 
In the system settings (Win 7) I have the screensaver started after for example 2 minutes. Despite that the screensaver is not started after this time. I cannot force the screensaver to start again.

**Comment by Cimbali** [comment]
How do you reactivate the screensaver ? Manually setting it off and on again ? Or rebooting the machine ?

**Comment by Cimbali** [comment]
Pympress deactivates screensavers when it is in fullscreen, and reactivates it on un-fullscreen or exit. We do this by modifying the `ScreenSaveActive` registry value (in `HKEY_CURRENT_USER\Control Panel\Desktop`):

https://github.com/Cimbali/pympress/blob/457bfda61d78bfe5a82e5d2613a59306237768cb/pympress/util.py#L295-L308


As you can see in the code above, we use the same variable `set_screensaver.dpms_was_enabled` to decide whether to disable and enable the screensaver, so if we deactivate the screensaver we’re necessarily going to try to reactivate it. That leaves 2 options for what could be going wrong:
- you have an error or an exception on exiting pympress which prevents the screensaver reactivation to be called

  To check this, can you post the log file ? Its exact location is displayed in the menu > about section.
- we reactivate the screensaver incorrectly

  To check this, can you the following steps:
  1. run pympress (to deactivate the screensaver)
  2. re-enable the screensaver in the same way that we do it, using:

     ```batch
     reg add "HKEY_CURRENT_USER\Control Panel\Desktop" /v ScreenSaveActive /t REG_SZ /d 1 /f
     ```
     You can do this from a PowerShell, `cmd` command invite or with the Start > Execute command prompt

  If this re-enables your screensaver then pympress also should.

**Comment by Cimbali** [comment]
I can’t reproduce by the way, but I could only test this on a windows 10.

**Comment by northpole-pl** [comment]
Thank you for the explanation.
I will test the solution with the key value change in the registry.
The problem does not always occur. If it happens, sometimes it is enough to turn the screensaver off and on manually, and sometimes several reboots are needed.
I will check your solution and let you know.
Thank you for the support.
