### ISSUE TITLE
Support libreoffice notes pages

### ISSUE THREAD

**Issue by hyiltiz** [Cimbali/pympress#171]
When I use Export As PDF from within Libreoffice Impress on a .odp file, I have an option about notes: `Export notes pages` and `Comments as PDF annotations`. 
![image](https://user-images.githubusercontent.com/3246683/96673430-7d849480-1334-11eb-8260-db9fcf3d7c26.png)

The former simply appends the same set of slides once more (so the total number of slide pages exported is twice of the original) with tall slides with the other half having the notes (see below). The latter option is irrelevant to presenter notes.
![Screenshot_20201021_003406](https://user-images.githubusercontent.com/3246683/96673859-7b6f0580-1335-11eb-810c-77dca61079a3.png)

That simply doesn't work with presenting with the PDF. Is there a workaround? I think any of the following would work:
- Libreoffice somehow exports the notes "attached" into each of the slide pages in a way that `pympress` can read out (requires work from libreoffice devs);
- `pympress` somehow looks up corresponding notes from the `N+i` page for the `i`th page; (hacky but works; requires work from pympress devs)
- `pympress` somehow reads in a text file from the command line like `pympress present.pdf --notes NotesPerLine.txt` where the `.txt file provides the notes per line for each page. Multi-paragraph or formatted text will not be supported; maybe a json format is better though. (hacky; requires work from pympress devs)
- The user creates `NotesPerLine.txt` manually, then using PDF processing library such as `qpdf` or `pdftk` *properly* embeds each line as *presenter notes* for the PDF file. (A total workaround, only available for power users; requires no work from any devs)

I am inclined to go with the last option for now, but not sure what fields to edit for the slide notes to show up properly. Suppose I create a 5 page slides using Libreoffice Impress where slide 3 and 4 has presenter notes `"note 3"` and `"note 4"` respectively. If I create a text file containing the following:
```


note 3
note 4

```

How can I call `qpdf` such that I can embed the notes into my PDF in order for pympress to recognize and show them as the presenter notes?

I tested with Okular some PDF comments and it seems creating any kind of PDF annotation with text (I tested the popup annotation and text annotation) *works* -- they showed up in pyimpress as presenter notes without showing up on the slides.

**Comment by Cimbali** [comment]
Hi @hyiltiz and thanks for opening this issue, this is a very interesting suggestion !

I think the 2 options from libreoffice are probably those we should work with:
1. > Export notes pages [which] appends the same set of slides once more (so the total number of slide pages exported is twice of the original) with tall slides with the other half having the notes

	We could try and detect pages of different aspect ratios, alternating odds and even pages, if I understood this right.
	Then either remove the top part (which repeats the slide) or only show this page in the presenter view.
2. > Comments as PDF annotations

	These could/should show up as annotations in pympress, but maybe comments and notes are not the same things inside libreoffice ?

In any case I need to have a deeper look, but I think supporting libreoffice PDF outputs out of the box is a good idea. I’m not very fond of the approach of having a second file that contains notes in general.

**Comment by hyiltiz** [comment]
Thx for the response! Responding inline.

> Hi @hyiltiz and thanks for opening this issue, this is a very interesting suggestion !
> 
> I think the 2 options from libreoffice are probably those we should work with:
> 
> 1. > Export notes pages [which] appends the same set of slides once more (so the total number of slide pages exported is twice of the original) with tall slides with the other half having the notes
>    
>    
>    We could try and detect pages of different aspect ratios, alternating odds and even pages, if I understood this right.
>    Then either remove the top part (which repeats the slide) or only show this page in the presenter view.
This would be most ideal, since this requires nothing to be done by the user nor the libreoffice developers; getting text out from a few pages should also be possible without too much programming.

The extra pages are simply appended, with tall aspect ratio. So if the original slide pages are ordered as [1,2,3,4,5], the ones with comments are [1,2,3,4,5,1',2',3',4',5'], where `3'` is the same as `3` except it is twice as tall as `3` and includes the presenter notes in the bottom half, below the actual slides.

> 2. > Comments as PDF annotations
>    
>    
>    These could/should show up as annotations in pympress, and is what you saw with the Okular PDF comments. But maybe comments and notes are not the same things inside libreoffice ?

Yeah, manually creating annotations in Okular worked nicely with pympress but libreoffice didn't create annotations. I think, it converts libreoffice comments, like the ones used during a collaborative editing process you could give feedback on part of the document in libreoffice, to PDF annotations. However, presenter notes are *not* converted to annotations, but instead just appended at the end of the pdf file as described above.

> 
> In any case I need to have a deeper look, but I think supporting libreoffice PDF outputs out of the box is a good idea. I’m not very fond of the approach of having a second file that contains notes in general.

Really glad to hear the support; I am more than happy to provide testing etc. Ideally, as early as we can, since I would like to be able to use pympress for my dissertation defense talk soon (within weeks) ;-p I agree that an external file that only contains the presenter notes is hacky.

**Comment by Cimbali** [comment]
The comments-to-PDF seem to work:

![image](https://user-images.githubusercontent.com/6126377/97030764-92913b80-155f-11eb-9469-32addb4af015.png)

You maybe need to press `a` to toggle the annotations panel if it’s not opened by default.

**Comment by Cimbali** [comment]
Alright, and in Libreoffice you can change the format and orientation of the notes pages, by going into the « Properties » panel. See here on the right, I’ve changed the notes to be in A4 but landscape orientation.

What this means is that we can simply detect when we have half the slides with a given aspect ratio, followed by the other half of the slides with a different aspect ratio. Then we should engage « Libreoffice notes pages » mode, which means:
- the apparent number of pages is divided by 2,
- the « notes » panel shows the notes page corresponding to the current page, which already includes a miniature of the current slide, and
- the « current slide » panel is hidden.

I think maybe the annotation panel should be kept toggleable.

**Comment by hyiltiz** [comment]
Yes, you are right; the comments-to-PDF show up as presenter notes. That is *not* how it should be though; comments-to-PDF usually come from libreoffice collaborative editing, which is *not* the presenter notes.
I'd want presenter notes on only slides 3/5 and 4/5.

**Comment by Cimbali** [comment]
> comments-to-PDF usually come from libreoffice collaborative editing, which is _not_ the presenter notes.

I agree that it’s not what they’re designed for, but they can serve as a workaround if needed.

**Comment by hyiltiz** [comment]
> > comments-to-PDF usually come from libreoffice collaborative editing, which is _not_ the presenter notes.
> 
> I agree that it’s not what they’re designed for, but they can serve as a workaround if needed.

Yes.

I think your "Libreoffice notes pages mode" idea is great; I do not know much about the internals of the pympress to estimate if that would be a large rewrite or a simple addition of a few functions.

**Comment by Cimbali** [comment]
It’s less work than re-doing the drawing tools, that’s for sure. :)

**Comment by Cimbali** [comment]
Alright, you can test the current master @hyiltiz. Not sure I haven’t let some bug slip through, but I’ve tested it and it seems to work.

It should auto-detect, otherwise you can
- select it with
    -  `pympress --notes=after`, or
    -  `pympress -na`, or
    - in the menu Presentation > Notes position > After slide pages
- toggle it
    - by pressing `n`, or
    - in the menu Presentation > Notes mode

**Comment by hyiltiz** [comment]
Just created a `virtualenv` and installed the master, along with a few dependencies. Works wonderfully! Thanks! This is probably much better than trying to extract text out from half the page somewhere and pretend them being PDF annotations. More "native" support. :+1:
