### ISSUE TITLE
Problem installing on Fedora 33?

### ISSUE THREAD

**Issue by lminiero** [Cimbali/pympress#176]
### Environment
- Fedora 33
- Python 3.9.0

### Pympress
- version 1.5.3
- Installation method: copr (via dnf)

### Expected behaviour
Trying to install the package via dnf fails due to broken dependencies.

### Steps to reproduce
    dnf info python3-pympress

### Problem
The installation fails with the following error:

```
Error: 
 Problem: conflicting requests
  - nothing provides python3.8dist(pygobject) needed by python3-pympress-1.5.3-3.noarch
  - nothing provides python(abi) = 3.8 needed by python3-pympress-1.5.3-3.noarch
(try to add '--skip-broken' to skip uninstallable packages)
```

I suspect this has to be related to some packages not being available (anymore?) on Fedora 33, as I managed to install it without issues on 32. I managed to install it successfully via `pip`, so this is not a stopper for me, but I thought I'd report the issue anyway, since having it available via `dnf` would get me updates automatically. Thanks!

**Comment by Cimbali** [comment]
Ah does fedora 33 use python 3.9 maybe ? I’ll rebuild the rpm

**Comment by Cimbali** [comment]
Ah does fedora 33 use python 3.9 maybe ? I’ll rebuild the rpm

**Comment by nbecker** [comment]
Just tried to install today, same problem on fedora 33 (yes, it uses python-3.9)

**Comment by Cimbali** [comment]
Ah yes I though an update would come soon but I’ve had a few other things to do… I just queued a re-build of the same version, that should take care of it.

**Comment by Cimbali** [comment]
It seems like the build went fine and used the right python version, so I’m closing this issue. Fell free to reopen if it doesn’t fix installing from copr on Fedora 33.

> Processing files: python3-pympress-1.5.3-3.noarch
> Provides: application() application(pympress.desktop) mimehandler(application/pdf) python-pympress = 1.5.3-3 python3-pympress = 1.5.3-3 python3.9-pympress = 1.5.3-3 python3.9dist(pympress) = 1.5.3 python3dist(pympress) = 1.5.3
> Requires(rpmlib): rpmlib(CompressedFileNames) <= 3.0.4-1 rpmlib(FileDigests) <= 4.6.0-1 rpmlib(PartialHardlinkSets) <= 4.0.4-1 rpmlib(PayloadFilesHavePrefix) <= 4.0-1
> Requires: /usr/bin/python3 python(abi) = 3.9
> Obsoletes: python-pympress < 1.5.3-3
> Recommends: python3dist(watchdog)
> Suggests: (gstreamer1 and gstreamer1-plugins-bad-free) (vlc and python3dist(python-vlc)) or
> Checking for unpackaged file(s): /usr/lib/rpm/check-files /builddir/build/BUILDROOT/python3-pympress-1.5.3-3.x86_64
> Wrote: /builddir/build/RPMS/python3-pympress-1.5.3-3.noarch.rpm
> […]
> Child return code was: 0

**Comment by lminiero** [comment]
Worked for me after a `dnf clean all`, thanks!
