### ISSUE TITLE
Add options to control a running Pympress instance via the CLI

### ISSUE THREAD

**Issue by TuringTux** [Cimbali/pympress#178]
**Feature request**: Add options to control a presentation in a running Pympress instance via a command line interface (to make Pympress scriptable).

I would like to bind a few dedicated keys of my keyboard to change the slides in Pympress, even when the Pympress window is not focused. The software I use to control the keyboard has the option to execute arbitrary commands on keypress.

Therefore, I'd find it great if there were command line options like this:

```bash
$ pympress --next-slide
# The currently running Pympress instance now switches to the next slide
$ pympress --prev-slide
# The instance switches back to the previous slide
```

This command would connect to a running Pympress instance (assuming exactly one is currently running), send the command to go to the next slide and immediately exit again.

This feature request is different from #168 (because that issue was about configuring Pympress, my request is about controlling Pympress). An example of an application with this CLI control possibility is [gromit-mpx](https://github.com/bk138/gromit-mpx) (see the usage section of the README for details).

Is it possible to implement something like this? A problem that immediately comes to my mind is that there could be multiple running instances of Pympress (which could maybe be selected with an additional `--instance 1` parameter?).

I'd be more than happy to help with the implementation :)

**Comment by Cimbali** [comment]
Thanks ! This seems like a great feature.

It would require to register the application instance in some way so we can send commands to it, I’m guessing the major hurdle is that this is probably very OS-dependent.

**Comment by TuringTux** [comment]
@Cimbali Thanks for the quick response (and thanks for developing Pympress, by the way, I really like the software - I discovered it a few years ago, then forgot about it, then re-discovered it a few weeks ago out of need and was very happy to see it still being maintained).

> It would require to register the application instance in some way so we can send commands to it, I’m guessing the major hurdle is that this is probably very OS-dependent.

I see. I'll search around and look for anything handy I can find. Maybe Python offers some platform-independent way of doing it (I don't know of any, but I hope there is one :smile:)

**Comment by Cimbali** [comment]
I’m guessing if there is a way to do this in a platform-independent way, our best bet is probably Gtk on which we already rely. I think there might be a dbus implementation inside GLib ? See [`Gio.Application.register`](https://lazka.github.io/pgi-docs/#Gio-2.0/classes/Application.html#Gio.Application.register)

It is worth noting that right now, pympress is not running as a `Gtk.Application`, but it is on a wishlist somewhere. This would require some changes on how actions are handled I believe. There’s some info on all this here: https://wiki.gnome.org/HowDoI/GtkApplication

**Comment by TuringTux** [comment]
Thanks for the links! I sadly have no experience with Gtk / PyGtk whatsoever, but if I can find the time, I'll have a look.

**Comment by Cimbali** [comment]
I managed to convert pympress to the `Gtk.Application` paradigm, except for menus that still trigger signal handlers. Apparently this now needs to be changed to activating [`Gio.Action`s](https://wiki.gnome.org/HowDoI/GAction) instead, which will allow us to remotely triger them.

However this means the menu paradigm also needs to change… not sure to what though. It’s very confusing, there’s deprecation notices all over the place.

I’m thinking now to transform our current menu to an XML format that can be loaded into a `Gio.Menu` with action names instead of signal handlers, then add it with `Gtk.Application..set_menubar`

**Comment by Cimbali** [comment]
I’m making progress on this, which will also take care of #144. However the solution does involve rewriting nearly every single event handler in pympress, so it’s rather time-consuming.

**Comment by Cimbali** [comment]
Alright so first step for this is in the branch gio_refactor. With these modifications, we currently have that if pympress is open:
- if you run `pympress`, it brings the existing instance to the front
- if you run `pympress file.pdf`, it opens the file in the existing instance.

**Comment by Cimbali** [comment]
Here’s a number of commands added, which other command line options could be useful?
```
  -P, --pause                 Toggle pause of talk timer
  -r, --reset                 Reset talk timer
  -n, --next                  Next slide
  -p, --prev                  Prev slide
  -f, --first                 First slide
  -l, --last                  Last slide
  -b, --blank                 Blank/unblank content screen
  -q, --quit                  Close opened pympress instance
```

**Comment by TuringTux** [comment]
Wow, thank you very much for your work on this! I personally am more than happy with the commands you added (for me, `--prev` and `--next` are the most important), they are exactly what I'd wished for.

**Comment by Cimbali** [comment]
Now merged into master

**Comment by Cimbali** [comment]
Actually this seems to behave unexpectedly on Windows, where a new instance is created for every command.

**Comment by Cimbali** [comment]
This was due to a missing DBus dependency, and is now fixed. CLI works as expected to command a remote instance on Windows too.
