### ISSUE TITLE
Close on Windows 10 doesn't release file handle

### ISSUE THREAD

**Issue by lemmy** [Cimbali/pympress#180]
### Environment
- Windows 10

### Pympress
- v1.5.3
- Installation method: Download msi/zip from the releases page

### Expected behaviour
"Close"-ing a presentation in Pympress but leaving Pympress open does not release the file handle.  This causes e.g. [Syncthing](https://syncthing.net) not to update the presentation file on disk and one has to completely close Pyimpress (which wouldn't be an issue if Pympress would remember its window position and size).

**Comment by Cimbali** [comment]
Hmm, how do you check for releasing file handles ?

**Comment by lemmy** [comment]
I don't; it is just an educated guess based on the observed behavior.

**Comment by Cimbali** [comment]
Interesting. There are 2 places I think something like this could possibly happen:

1. We open the file with `Poppler.Document.new_from_file` which returns an object but I don’t think it keeps the file open. If it does, maybe we should enforce the ref count going to 0 when we replace the file object.
2. We use `watchdog.observers.Observer` + `watchdog.events.FileSystemEventHandler` to watch for modifications of a file and reload it from disk when it changes. Maybe something is not unscheduled properly here.

**Comment by Cimbali** [comment]
Confirmed via the resource monitor

**Comment by Cimbali** [comment]
Alright, it seems this happens in the Poppler.Document which internally holds `GooFile` object that keeps the file descriptor or handle open until it’s destroyed. That means that to fix this we need to somehow force garbage collection of the Poppler document.

This seems to work on Linux right now (where the bug was reproducible too), I yet have to test the solution on Windows.

**Comment by Cimbali** [comment]
There are some pre-releases available here to confirm this issue is fixed:

https://ci.appveyor.com/project/Cimbali/pympress/build/job/oxuuf6i7sbds3adc/artifacts

**Comment by Cimbali** [comment]
Seems fixed to me, feel free to reopen if it’s not for you.
