### ISSUE TITLE
Encoding issues in translation

### ISSUE THREAD

**Issue by fefrei** [Cimbali/pympress#19]
It looks like `pympress` has a problem with rendering Umlauts:

![image](https://cloud.githubusercontent.com/assets/3078885/24284353/35458f96-106b-11e7-8b25-b60811a0342d.png)
(This is from the 1.0.2 binary install.)

The broken character should be an `ä`.

(Side note: I find it curious that `pympress` is loading the German interface at all. My system language is English, only my region is set to Germany.)

**Comment by Cimbali** [comment]
That's strange, my default location is France with all formats in English and it loads English. Do you have the LANG variable set by any chance?
Run cmd.exe (presumably from your start menu) and try: echo %LANG%

For the rest I've confirmed that the strings that are translated through the Gtk.Builder have encoding problems on windows.

**Comment by fefrei** [comment]
No, that just outputs `%LANG%`.

For reference, here are my settings:
![image](https://cloud.githubusercontent.com/assets/3078885/24293912/5d5fd6fc-1094-11e7-8f8e-f71356f6c057.png)

**Comment by Cimbali** [comment]
I'm uploading new versions of the installers with this fix to the [v1.0.2 release page](https://github.com/Cimbali/pympress/releases/edit/v1.0.2) as we speak. You should be able to test it in no time.

**Comment by fefrei** [comment]
I can confirm that the new version has the best umlauts! 👍

![image](https://cloud.githubusercontent.com/assets/3078885/24598805/ad1165c4-184d-11e7-9236-ee6ff2bac1e0.png)
