### ISSUE TITLE
Error when try to play videos embedded in PDF with VLC

### ISSUE THREAD

**Issue by oswaldocostaneto** [Cimbali/pympress#191]
### Environment
- Operating system and version: Windows 10 Home 64x
- Python version: 3.8

### Pympress
- version: v1.6.0b7-x86_64
- Installation method: binary installer, zip and chocolatey

### VLC
- version: vlc-3.0.12-win64

### Expected behaviour
video played within the PDF

### Steps to reproduce
1) install pympress from the most current source
2) try to play some video within the presentation

### Problem
What's happening instead of what you are expecting?
-nothing. no video is played.

![1](https://user-images.githubusercontent.com/50557641/114956949-5b2c8900-9e36-11eb-84a7-837a52fdf3ff.png)

What is reported in pympress.log?\*
[pympress.log](https://github.com/Cimbali/pympress/files/6321835/pympress.log)

Does the problem still happen if you remove your config file?\*
yes. still

**Comment by Cimbali** [comment]
Thanks for reporting @oswaldocostaneto ! This was fixed in b59174e and will be in the next release.
