### ISSUE TITLE
Clickable Table of Contents in Version 1.6 not working

### ISSUE THREAD

**Issue by ferdinand-fichtner** [Cimbali/pympress#192]
### Environment
- MS Windows 10

### Pympress
- v1.6.0b7-x86_64.zip
- zip portable binary; same behaviour in other 1.6 variants

### Expected behaviour
In version 1.5.* latex generated table of contents used to be clickable in the current slide pane of the presenter window. Clicking on a section headline made Pympres jump to the respective slide. This functionality seems not to work anymore in version 1.6b*.

### Steps to reproduce
Open attached file in Pympress 1.6b7 (compiled with xelatex). Headlines in the table of content appear to be recognized as links, but clicking does not trigger a jump to the respective section.

Thank you for recommendations.

Side note: >Help>About also does not work.

Best regards
Ferdinand

[toc-test.pdf](https://github.com/Cimbali/pympress/files/6346202/toc-test.pdf)

**Comment by Cimbali** [comment]
Tanks for reporting ! I think the Help > About was fixed in the non-beta release, I’ve now fixed the link issues too.

You can download a new binary here to test it: https://ci.appveyor.com/project/Cimbali/pympress/build/job/dwppxv5niegshr64/artifacts

**Comment by ferdinand-fichtner** [comment]
Works like a charm! Thank you very much for the fast response and perfect solution to this problem. 

Do you offer a possibility to (financially) support your work?

Best, Ferdinand

**Comment by Cimbali** [comment]
No @ferdinand-fichtner there’s no way to give money. If you want to participate, you can contribute to the code or [the translations]( https://poeditor.com/join/project?hash=nKfRxeN8pS).
