### ISSUE TITLE
No windows builds for 1.6.0 release

### ISSUE THREAD

**Issue by functionpointer** [Cimbali/pympress#193]
The [github releases page](https://github.com/Cimbali/pympress/releases) does not have windows builds for the 1.6.0 release.
However, there are builds for all the previous pre-releases. Is this intentional?

**Comment by Cimbali** [comment]
That is not normal indeed. This is due to marcelotduarte/cx_Freeze#1030 but a workaround is already in place. Will release straight 1.6.1 with some additional fixes soon.

**Comment by Cimbali** [comment]
[Done](https://github.com/Cimbali/pympress/releases/tag/v1.6.1)
