### ISSUE TITLE
pympress does not start on Linux

### ISSUE THREAD

**Issue by ilippert** [Cimbali/pympress#194]
### Environment
Fedora  5.11.16-200.fc33.x86_64
Python 3.9.4

### Pympress
python3-pympress.src   1.6.0-1   copr:copr.fedorainfracloud.org:cimbali:pympress

### Expected behaviour
What are you trying to achieve? What's the expected outcome?
running `pympress` on the shell

### Steps to reproduce
What are you doing?
running `pympress` on the shell

### Problem
What's happening instead of what you are expecting?
running `pympress` on the shell gives me
`Traceback (most recent call last):
  File "/usr/bin/pympress", line 33, in <module>
    sys.exit(load_entry_point('pympress==1.6.0', 'gui_scripts', 'pympress')())
  File "/usr/bin/pympress", line 25, in importlib_load_entry_point
    return next(matches).load()
StopIteration
`

What is reported in pympress.log?\*
nothing current. Last entries are from March.

Does the problem still happen if you remove your config file?\*
(You can just move the config file to a different location to be able to restore it after testing)
yes

Is this the same issue, or should this be a new issue?
not sure whether this is a new issue or related to https://github.com/Cimbali/pympress/issues/190

**Comment by Cimbali** [comment]
That’s weird. Do you have by any chance several `python3` installed ? Maybe a conda or python3.8 and 3.9 next to each other ? One that’s not in a standard location ?

Here’s a handful of commands to try and see what’s going wrong.

- Listing files installed by the package:

    rpm -ql python3-pympress

- Checking which python is started by the `pympress` executable script:

    head -n1 /usr/bin/pympress

- Check who responds to `python3`:

    which -a python3

- Trying to launch pympress as a module:

    python3 -m pympress

- Ask pip to see if it sees the pympress install:

     python3 -m pip list | grep pympress

- Try the last 2 commands with the python3 specified in the executable (which is probably `/usr/bin/python3`) instead of just `python3`

**Comment by ilippert** [comment]
which -a python3                                               
/usr/bin/python3

head -n1 /usr/bin/pympress
#!/usr/bin/python3

**Comment by Cimbali** [comment]
Could be something to do with conflicting directories / file names. The new rpms handle that correctly but the old may omit to remove some directories on upgrade. Let’s try and look for site packages that match pympress that might not have been cleanly removed:

    python3 -c 'import site, pathlib; print("\n".join(match for site in site.getsitepackages() for match in pathlib.Path(site).glob("pympress*")))'

**Comment by Cimbali** [comment]
Also if this prints any files or directories, can you tell me exactly what’s in it ? The output of `file /usr/lib/python3.8/site-packages/pympress*` or something like that would be useful, to fix the new rpm packages.

**Comment by Cimbali** [comment]
By the way, what was your previous install method ? DId you install pympress-1.5.x from copr as well ?

**Comment by ilippert** [comment]
> Also if this prints any files or directories, can you tell me exactly what’s in it ? The output of `file /usr/lib/python3.9/site-packages/pympress*` or something like that would be useful, to fix the new rpm packages.

/usr/lib/python3.9/site-packages/pympress:                      directory
/usr/lib/python3.9/site-packages/pympress-1.5.3-py3.9.egg-info: directory
/usr/lib/python3.9/site-packages/pympress-1.6.1-py3.9.egg-info: directory

**Comment by ilippert** [comment]
> By the way, what was your previous install method ? DId you install pympress-1.5.x from copr as well ?

I am quite certain I did

**Comment by ilippert** [comment]
> > Also if this prints any files or directories, can you tell me exactly what’s in it ? The output of `file /usr/lib/python3.9/site-packages/pympress*` or something like that would be useful, to fix the new rpm packages.
> 
> /usr/lib/python3.9/site-packages/pympress: directory
> /usr/lib/python3.9/site-packages/pympress-1.5.3-py3.9.egg-info: directory
> /usr/lib/python3.9/site-packages/pympress-1.6.1-py3.9.egg-info: directory

I have now manually removed `/usr/lib/python3.9/site-packages/pympress-1.5.3-py3.9.egg-info` and then I can easily start the application

**Comment by Cimbali** [comment]
Thanks ! That’s useful, I’ll make the upgrade process in the RPMs check for that directory and remove it if it’s there.

**Comment by Cimbali** [comment]
RPMs have been updated to do the cleanup.
