### ISSUE TITLE
Preview next 1-8 slides instead of 1 and only 1

### ISSUE THREAD

**Issue by pou5bx7rcwl3vmh19bvmmuu5o01bf** [Cimbali/pympress#195]
1. pympress is amazing and thank you for that
2. the **presenter's window** currently shows the current slide, the next slide and optionally "notes". It works well and that is fine
3. I would like to be able to use my whole screen's real estate to display more "next" slides **while presenting (not in a deck overview)** (at least 4 and up to 8-12 for example) which would allow to easily look "further ahead" **while presenting**

**Comment by Cimbali** [comment]
Let’s track this improvement in #162

**Comment by Cimbali** [comment]
So @wisp3rwind mentioned I might have misunderstood this issue. Did you mean showing next slides all of the time, or just to navigate between them ?

**Comment by pou5bx7rcwl3vmh19bvmmuu5o01bf** [comment]
@Cimbali 
@wisp3rwind 

Indeed, this issue does not seem related to the deck overview #162 

I did mean "showing next slides all of the time" and NOT "just to navigate between them"

This issue is:
- "currently one can preview 1 and only 1 single slide when presenting",
- please allow us to "preview more than 1  slide (such as 4 or 6) when presenting"

**Comment by Cimbali** [comment]
So what are we thinking, something like this? It shows up to 16 next slides (which is rather excessive to me, so it should be a safe upper bound).

![image](https://user-images.githubusercontent.com/6126377/134775737-600d6841-6c0a-4b6d-8063-e6ffaef2d460.png)

Right now they all share the “next slide” screen area, which is separate from the “current slide” and potentially ”notes” screen areas. Note that you can rearrange the way these are displayed, e.g. place notes and current on top of each other and all the next slides on the side.

Here’s how it would look with libreoffice slides that have no “current slide” pane as the page is already contained in the notes page, and showing 4 next slides:
![image](https://user-images.githubusercontent.com/6126377/134776855-e2af9c1c-6a85-48b0-a75c-0c11e282cb5e.png)

**Comment by Cimbali** [comment]
I still need to adjust the title of the frames though, they all just say “Next slide” now. I think starting from 2 we can go ”2nd next slide”, “3rd next slide”, etc.

**Comment by pou5bx7rcwl3vmh19bvmmuu5o01bf** [comment]
It looks amazing like that!

**Comment by Cimbali** [comment]
It is in master, you can try it out. There’s a dialog under Starting Configuration > Edit Layout that allows to dynamically change the layout (#83) and I’ve added put the setting for number of next slides there as well.

No release yet as the grid somewhat messes with the toggleable annotations panel size, so I need to figure out who to fix that first.
