### ISSUE TITLE
show elapsed time on content screen

### ISSUE THREAD

**Issue by iamRyanChia** [Cimbali/pympress#198]
Hi, I'd like to know how to show elapsed time on content screen? Is there an option to achieve this?

I may have found a bug in the latest version1.6.1 for Windows. When you close `content fullscreen` and reopen it, the content is not fullscreen. Please check it.

Thank you!

**Comment by Cimbali** [comment]
Sorry there is currently no way to show the elapsed time on the content screen. Only the slide is shown there.

I’ll have a look at the fullscreen behaviour on Windows.

**Comment by Cimbali** [comment]
The content window only starts in fullscreen if there are 2 screens, otherwise it ignores the starting configuration.
