### ISSUE TITLE
Language identification on Windows 10

### ISSUE THREAD

**Issue by Cimbali** [Cimbali/pympress#20]
[`locale.defaultlocale`](https://docs.python.org/3.6/library/locale.html#locale.getdefaultlocale) seems to use the region instead of the language in Windows 10.

For example, see bug #19 with @fefrei's configuration (screenshot below and %LANG% not set), returning German as language.

![](https://cloud.githubusercontent.com/assets/3078885/24293912/5d5fd6fc-1094-11e7-8f8e-f71356f6c057.png)

**Comment by Cimbali** [comment]
Alright, turns out this is expected behaviour. Python wil detect the "Formaté setting, which is the first one you can see in the "Formats" tab of the "Region" settings.

As can be seen on the screenshot, this is set to German, and python correctly detects German as the language to use. This can be confirmed as well from the "System Locale:" line in the output of `systeminfo` (on the command line).

For future reference, the regions dialog shown in the screenshot can be found in the Control Panel by clicking on "Change date, time, or numbers format" under "Clock, Language and Region"

**Comment by fefrei** [comment]
It's a bit... *weird* that Python uses the region to determine the language, but alright, it looks like this is a problem with Python itself. Thanks for looking into it!

**Comment by Cimbali** [comment]
Well I think it's weird how Windows presents it under region, I was confused as well. What is also confusing is that the language setting for Windows itself is not the same, that is the second window on your screenshot.

But if you look at it, you're picking a language, and then a variety, hence "German (Germany)". The region, or "Location" as they say is chosen in the next tab of that same window and can be totally unrelated to the language.

**Comment by fefrei** [comment]
True that, there's a setting `English (Germany)` 🎉 
And: Weird indeed, some applications appear to follow the language list, and others follow this...
