### ISSUE TITLE
Notes from libreoffice impress 

### ISSUE THREAD

**Issue by jegarfa** [Cimbali/pympress#202]
### Environment
- Linux Mint 20.1
- Python 3.8.5

### Pympress
- version (master) from git repository 1.6 and last version from synaptic repository 1.5  
- Installation method: source,and also from synaptic repository

### Expected behaviour
To see the Libreoffice notes pages in the pympress "notes mode" with the adequate ratio size.

### Steps to reproduce
Opening a pdf document that contains notes that have been created with libreoffice impress.  

### Problem
Both slides and notes are cut and does not fit well the windows of pympress (notes, slides and next slide). 
Even after trying the options in "Notes position" the problem persists.

Could be very useful if a short template can be provided for both beamer (.tex) and libreoffice impress (.odp). 
The notes with beamer appear perfectly.

**Comment by Cimbali** [comment]
Notes from libreoffice are supported from v1.6 onwards. When exporting the libreoffice impress slides to pdf, tick the “export nodes” option.

As you can see in the screenshot below, the notes and slides are both using the aspect ratios of their PDF pages, here the slides are 16:9, the notes 4:3 with an embedded preview of the current slide. The notes position (which is detected automatically) is “After slide pages”.

![image](https://user-images.githubusercontent.com/6126377/124920259-70f5b880-dff7-11eb-9c96-2a833d5babb5.png)

If this somehow doesn’t seem to work for you, please provide a pdf example that triggers the bug, and a screenshot of the “cut” slides.

**Comment by jegarfa** [comment]
Thanks a lot for your answer. Indeed, it was a matter with the aspect ratio and the positioning of the notes in my slides. 
Now I just have test the most recent version (1.6.1) and everything is working as expected.
Perfect!
