### ISSUE TITLE
Automatically re-load the PDF file

### ISSUE THREAD

**Issue by Serafin-Frache** [Cimbali/pympress#204]
### Environment
- Windows 10
 

### Pympress
- 1.6.1
- Installation method:  binary installer 

It could be a minor thing, but in the previous versions Pympress automatically refreshed the file every time it was compiled in Latex. Now it has to be re-open  every time. 
I am aware it is a super minor thing, and not the main pourpose of this software, but it was a nice feature to have, as you can compile and check the results on the go. 

Many thanks for all the effort on this super project.

**Comment by complanar** [comment]
May be related to #203. See there for a possible workaround. (But yes, I think it already worked without a workaround in an earlier version. But can’t find the right one.)

**Comment by Serafin-Frache** [comment]
> May be related to #203. See there for a possible workaround. (But yes, I think it already worked without a workaround in an earlier version. But can’t find the right one.)

Thanks for your answer. My fault, should have checked the last issue, I did it a while ago. 

I tried and the workaround works, very useful in the meantime. 

Thanks again, and sorry for duplicating the issue.
