### ISSUE TITLE
Glitches when using VLC playback

### ISSUE THREAD

**Issue by Cimbali** [Cimbali/pympress#225]
Reported by @complanar in #212:
> [T]he embedded video from the pdf file above is played (current master, pip install, Linux Mint 20.2) […]
> 
> There is [a] glitch. As soon as the video is played, there are graphic artifacts inside the content window. Sometimes they change when paused or stopped, sometimes they change on window resize or similar action.
> 
> ![Bildschirmfoto_2021-11-05_14-45-11](https://user-images.githubusercontent.com/4706846/140530078-6d31c03e-2002-4251-a7a3-27a056a3e002.png)

Additional version etc. info:

> Info Dialog:
> 
> ```
> Media support uses GdkPixbuf gif player, GStreamer 1.16.2, VLC 3.0.9.2 Vetinari.
> Python version 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0]
> ```
> 
> Pympress Log:
> 
> ```
> INFO:pympress.app:Pympress: 1.7.0b1 ; Python: 3.8.10 ; OS: Linux 5.4.0-89-generic #100-Ubuntu SMP Fri Sep 24 14:50:10 UTC 2021 ; Gtk 3.24.20 ; GLib 2.64.2 ; Poppler 0.86.1 cairo ; Cairo 1.16.0 , pycairo 1.16.2
> INFO:pympress.extras:Media support: GdkPixbuf gif player, GStreamer 1.16.2, VLC 3.0.9.2 Vetinari
> ```
> 
> […] config reads:
> 
> ```
> [gst]
> enabled = off
> init_options = 
> mime_types = 
> 
> [vlc]
> enabled = on
> init_options = --no-video-title-show,--no-xlib
> mime_types = 
> ```

**Comment by Cimbali** [comment]
Apparently glitching is not fixed (yet?).

**Comment by ousia** [comment]
@Cimbali,

using Pympress-1.7.2 in Fedora 37, all glitches in VLC are gone.

Both GStreamer and VLC play video as expected (no problems with the video area).

So I think this issue might be closed.

Many thanks for the fix.
