### ISSUE TITLE
Install fails on Centos Stream 8 for pympress-1.7.0b1-1

### ISSUE THREAD

**Issue by ConorDaly-met** [Cimbali/pympress#226]
**Describe the bug**
Install of pympress-1.7.0b1-1 fails on CentOs Stream 8 due to missing python3.6dist(watchdog)
`python3 -m pip install --user pympress` is successful

**To Reproduce**

1. `sudo dnf copr enable cimbali/pympress`
2. `sudo dnf install python3-pympress`
3. Error message:
```
Updating Subscription Management repositories.
Unable to read consumer identity

This system is not registered with an entitlement server. You can use subscription-manager to register.

Last metadata expiration check: 0:28:11 ago on Fri 12 Nov 2021 16:19:05 GMT.
Error: 
 Problem: conflicting requests
  - nothing provides python3.6dist(watchdog) needed by python3-pympress-1.7.0b1-1.noarch
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

4. I attempted to `python3 -m pip install --user watchdog` which was successful but the dnf install did not see the local installation even with PYTHONPATH set.

**Expected behavior**
Expected install of pympress

**Environment (please complete the following information):**
 - OS: CentOs Stream 8 
 -cat /etc/os-release 
```
NAME="CentOS Stream"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Stream 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"
```
 - Python version: 3.6.8
 - Pympress version: 1.7.0b1-1
 - Installation method: dnf, copr
 - Repos list
 ```
dnf repolist
Not root, Subscription Management repositories not updated

This system is not registered with an entitlement server. You can use subscription-manager to register.

repo id                                                         repo name
appstream                                                       CentOS Stream 8 - AppStream
baseos                                                          CentOS Stream 8 - BaseOS
copr:copr.fedorainfracloud.org:cimbali:pympress                 Copr repo for pympress owned by cimbali
epel                                                            Extra Packages for Enterprise Linux 8 - x86_64
epel-modular                                                    Extra Packages for Enterprise Linux Modular 8 - x86_64
epel-next                                                       Extra Packages for Enterprise Linux 8 - Next - x86_64
extras                                                          CentOS Stream 8 - Extras
powertools                                                      CentOS Stream 8 - PowerTools
skype-stable                                                    skype (stable)
slack                                                           slack
```

**Additional context**
If instead I use pip I can install pympress version 1.6.4
```
python3 -m pip install --user pympress
Collecting pympress
  Using cached https://files.pythonhosted.org/packages/25/9e/d76ded4eafb9a7013707de58c88ba40b532cea29fa2f0b1e0019e4b6cd08/pympress-1.6.4-py3-none-any.whl
Collecting watchdog (from pympress)
  Using cached https://files.pythonhosted.org/packages/e8/a8/fc4edd7d768361b00ea850e5310211d157df6b5a1db6148dd434e787d898/watchdog-2.1.6.tar.gz
Installing collected packages: watchdog, pympress
  Running setup.py install for watchdog ... done
Successfully installed pympress-1.6.4 watchdog-2.1.6
```

**Comment by Cimbali** [comment]
Thanks for reporting ! The problem is that the watchdog package is not distributed by CentOS as an RPM, I’ll update the RPM to not depend on it. Or maybe I can try to add watchdog to the COPR repo for those distros that don’t have it.

In the mean time:
- You can install the RPM with `--skip-broken`, pympress just won’t be able to detect when files change
- If you then install watchdog from python the feature should work again

**Comment by Cimbali** [comment]
A search on https://rpm.pbone.net/ seems to indicate that OpenMandriva and RHEL could be in the same situation.

**Comment by ConorDaly-met** [comment]
> Thanks for reporting ! The problem is that the watchdog package is not distributed by CentOS as an RPM, I’ll update the RPM to not depend on it. Or maybe I can try to add watchdog to the COPR repo for those distros that don’t have it.
> 
> In the mean time:
> 
>     * You can install the RPM with `--skip-broken`, pympress just won’t be able to detect when files change
> 
>     * If you then install watchdog from python the feature should work again

Hi,

Thanks for prompt action.  I see python3-watchdog rpm is now in the copr repo.

I'm fairly sure the --skip-broken switch workaround would not work.  Instead it would remove python3-pympress from the transaction and the install still fails.

BTW, I suggest you update the installation instructions in the README to replace 

```pip install "pympress"```

with the more portable

```python -m pip install [--user] "pympress"```

or 

```python3 -m pip install [--user] "pympress"```

Regards

**Comment by Cimbali** [comment]
Thanks for the reply @ConorDaly-met, does installing the RPM from copr work now?

- I thought `--skip-broken` would skip missing dependencies, not packages with missing dependencies. Maybe there is a flag for that?  
  I’m not familiar with `dnf`, but I know `zypper` (the opensuse equivalent) prompts for allowing to ignore missing dependencies, e.g.:
  ```
  Problem: nothing provides 'dejavu-sans-fonts' needed by the to be installed package-version.arch
   Solution 1: do not install package-version.arch
   Solution 2: break package-version.arch by ignoring some of its dependencies
  ```
  All I meant was that in the case of pympress, you can safely ignore the watchdog dependency − it will just disable automatic file reloading.
- Sure, we can suggest `python3 -m pip` instead of `pip` directly. It was a bullet under *Troubleshooting* before.

**Comment by ConorDaly-met** [comment]
Hi.  dnf replaces yum in Fedora/RedHat/CentOs distributions.  They behave in very similar fashion but seem to differ from zypper in that they will not break a package.  Instead they just drop the unfulfilled package from the transaction.  I am not aware of a switch to allow the zypper behaviour.
