### ISSUE TITLE
video not played at all in Windows portable installation (VLC installed)

### ISSUE THREAD

**Issue by ousia** [Cimbali/pympress#227]
**Describe the bug**

This comes from #223.

[The presentation](https://github.com/Cimbali/pympress/files/7475984/uncompressed-a.pdf) isn’t played at all (no autostart or clicking on the video).

I tested it with the portable installation (https://github.com/Cimbali/pympress/releases/download/v1.7.0b3/pympress-v1.7.0b3-x86_64.zip).

`vlc` can be invoked from the command prompt.

I don’t know what I might be missing.

Many thanks for your help.

**Comment by Cimbali** [comment]
Thanks for forking bugs @ousia ! :)

What’s the media support (in Help > About) ? Can you also post the log file ? (The path also in the About dialog, should be `%LOCALAPPDATA%\pympress.log`.)

Note that VLC and pympress need to have the same bitness, so seeing the link you used, VLC must be 64 bits.

**Comment by ousia** [comment]
> Note that VLC and pympress need to have the same bitness, so seeing the link you used, VLC must be 64 bits.

This was part of the problem. I didn’t realize that VLC was 32bit. So I took https://github.com/Cimbali/pympress/releases/download/v1.7.0b3/pympress-v1.7.0b3-i686.zip.

I’m afraid that autostart didn’t work. Video was only played after clicking on the slide.

I’m also afraid that video was displayed with buttons, with desktop background in the presenter:

![wrong-main-window](https://user-images.githubusercontent.com/203767/142017381-0ed865ba-62b3-4286-b575-43a6aaeb5783.png)

The projector window didn’t also display only the video:

![wrong-projector](https://user-images.githubusercontent.com/203767/142017387-36cab4d2-e436-4036-b4f2-d6795111383d.png)

**Comment by Cimbali** [comment]
> Video was only played after clicking on the slide.

Can you report the media backends info and log files? I’m suspecting the libpoppler is not new enough, it should be ≥ 21.04.

> video was displayed with buttons

The video always has buttons in the presenter window, and only when the option is set in the content window.

> with desktop background in the presenter

This seems related to the glitches seen in #225, and should have been fixed by d99a7d7a − apparently it isn’t fixed for all setups.

Note that the glitches only appear in the area within the video overlay but outside of the actual video. This means that a workaround to avoid these glitches is to specify a box with the right aspect ratio for the video you mean to embed. In your example you have a square box with a 16:9 video, thus empty space around it.

**Comment by Cimbali** [comment]
That commit doesn’t appear to help much with glitches either.

**Comment by ousia** [comment]
Beta 4 from version 1.7 seems to be solving the issue with autostart.

I’m afraid that the glitches are still there.

A minimal log file reads (all text is just there at program start):

```
INFO:pympress.app:Pympress: 1.7.0b4 ; Python: 3.9.7 ; OS: Windows 7 6.1.7601 ; Gtk 3.24.30 ; GLib 2.70.0 ; Poppler 21.09.0 cairo ; Cairo 1.17.4 , pycairo 1.20.0
INFO:pympress.extras:Media support: GdkPixbuf gif player, GStreamer not available, VLC 3.0.14 Vetinari
WARNING:pympress.ui:Not starting content or presenter window full screen because there is only one monitor
ERROR:pympress.scribble:Error creating highlight cache
Traceback (most recent call last):
  File "D:/a/pympress/pympress/pympress/scribble.py", line 340, in reset_scribble_cache
  File "D:/a/_temp/msys64/mingw32/lib/python3.9/site-packages/gi/module.py", line 155, in __getattr__
ValueError: invalid enum value: 5
```

And extra info reads:

```
pympress is a little PDF reader written in Python using Poppler for PDF rendering and GTK for the GUI.
Some preferences are saved in %USERPROFILE%\Desktop\pympress\pympress.conf
Resources are loaded from %USERPROFILE%\Desktop\pympress\share
The log is written to %LOCALAPPDATA%\pympress.log

Media support uses GdkPixbuf gif player, GStreamer not available, VLC 3.0.14 Vetinari.
Python version 3.9.7 (default, Nov 10 2021, 08:26:56)  [GCC 11.2.0 32 bit]
```

**Comment by ousia** [comment]
I wonder whether it would make sense to rewrite the issue to contain the glitches and the possible fix.

@Cimbali, many thanks for your help.

**Comment by Cimbali** [comment]
Glitches and workardounds are tracked in #225
