### ISSUE TITLE
File not reloaded on file change

### ISSUE THREAD

**Issue by complanar** [Cimbali/pympress#228]
**Describe the bug**
The views of an open pdf file are not updated when changing the file on disk. Maybe watchdog is not working properly.

**To Reproduce**
1. Open any pdf file in pympress
2. Update the file while open in pympress (e.g. with LaTeX)
3. Watch the unchanged file

This happens both on opening the file via command line or via "Open" dialog.

**Expected behavior**
Updated view, when file is changed on disk

**Environment (please complete the following information):**
 - OS: LinuxMint 20.2
 - Python version: 3.8.10
 - Pympress version: 1.7.0b3
 - Installation method: pip
 
Log (empty, except of the version info):
```
INFO:pympress.app:Pympress: 1.7.0b3 ; Python: 3.8.10 ; OS: Linux 5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021 ; Gtk 3.24.20 ; GLib 2.64.2 ; Poppler 21.06.0 cairo ; Cairo 1.16.0 , pycairo 1.16.2
INFO:pympress.extras:Media support: GdkPixbuf gif player, GStreamer 1.16.2, VLC 3.0.9.2 Vetinari
```

This worked a while ago and seems to have nothing to do with #203.

**Comment by complanar** [comment]
Hm!? Just updated my local copy of the repository and it just works again. Closing for now.

**Comment by Cimbali** [comment]
Probably 6ccbacf :)
