### ISSUE TITLE
Unpause by click adds waited time to timer

### ISSUE THREAD

**Issue by opatut** [Cimbali/pympress#23]
There is inconsistent behaviour when unpausing. If I unpause using `P`, the timer continues where it left off. E.g. I pause at `2:00`, wait 20 seconds, then unpause by pressing `P`, the timer continues with `2:01`.

When I unpause using navigation (e.g. next page), the timer instead continues at `2:21`.

(By the way: Awesome project, thanks!)

**Comment by Cimbali** [comment]
Ah, well spotted, I never noticed that. I'll look into it.

**Comment by opatut** [comment]
Thank you very much :)
