### ISSUE TITLE
Fedora 35 copr package…

### ISSUE THREAD

**Issue by Tokariew** [Cimbali/pympress#231]
Tried to update pympress on fedora 35… to new version, but broken dependencies are present

```
  - nothing provides gstreamer needed by python3-pympress-1.7.0b4-2.noarch
  - nothing provides gstreamer-plugins-base needed by python3-pympress-1.7.0b4-2.noarch
  - nothing provides gstreamer-plugins-good needed by python3-pympress-1.7.0b4-2.noarch
 ```

the correct one should be with `gstreamer1` for fedora 35…
and 1.7.0b4-2 release is prefered over 1.7.0-1 by dnf…

**Comment by Cimbali** [comment]
Thanks for reporting! I thought it would throw an error in the builder for missing packages − apparently not. Will have to investigate.

Also weird that betas are preferred, I could just retire them.

**Comment by Cimbali** [comment]
I made a second build with more detailed dependencies, it should work. Can you give it a try @Tokariew ? Also I removed the betas as their numbering is incorrect (should have been `1.7.0~b4` instead of `1.7.0b4`)

**Comment by Tokariew** [comment]
still broken…
```
 Problem: cannot install the best update candidate for package python3-pympress-1.6.4-1.noarch
  - nothing provides python310-gobject needed by python3-pympress-1.7.0-3.fc35.noarch
  ```
 Package name for gobject is `python3-gobject`

**Comment by Tokariew** [comment]
```
%if 0%{?rhel} >= 8
Requires: python3%{suffix:%{python3_version}}-gobject
%else
Requires: python3-gobject
%endif
```

With such section it work for me on fedora 35… but not sure if it doesn't brake some other distro

**Comment by Cimbali** [comment]
Ah I flipped that if, it’s only old RHEL that have the weird `python36-gobject` naming without `.` or providing `python3-gobject` or `python3dist(pygobject)`

**Comment by Tokariew** [comment]
with `%{py3_dist pygobject}` fedora still complain…
```
 Problem: cannot install the best update candidate for package python3-pympress-1.6.4-1.noarch
  - nothing provides or needed by python3-pympress-1.7.0-4.fc35.noarch
=================================================================================================================
 Package               Arch        Version            Repository                                            Size
=================================================================================================================
Skipping packages with broken dependencies:
 python3-pympress      noarch      1.7.0-4.fc35       copr:copr.fedorainfracloud.org:cimbali:pympress      250 k

Transaction Summary
=================================================================================================================
Skip  1 Package
```

**Comment by Cimbali** [comment]
Nothing provides `or` - that’s interesting

**Comment by Tokariew** [comment]
Work fine with release 5…

**Comment by Cimbali** [comment]
Yay! I The RPM dependencies have gotten quite complex, but luckily it’s something that should move too often. It hasn’t since RPM distribution started, and only does now to add gstreamer dependencies by default.
