### ISSUE TITLE
No translation for menu-bar items

### ISSUE THREAD

**Issue by Toorero** [Cimbali/pympress#239]
For me everything is translated apparat from the top-bar menu, including the dropdown part.
I'm not sure, if the German translation is just missing for the menu-bar or if it's a real bug though.

I'm happy to add missing German translation if that's the issue.

**Comment by Cimbali** [comment]
Yes translations are often lagging a little behind new features. New translations and updates can be contributed [on POEditor](https://poeditor.com/join/project?hash=nKfRxeN8pS). 
Note that strings tagged as “removed” do not need to be translated, however they are kept around for historical purposes and can be helpful to translate similar strings again.

Can you maybe share a screenshot of your window and menus so I can make sure this is not a bug?
