### ISSUE TITLE
Error playing video included using beamer

### ISSUE THREAD

**Issue by maxnoe** [Cimbali/pympress#240]
**Describe the bug**

Minimal example document:

```latex
\documentclass[]{beamer}

\usepackage{multimedia}
\usepackage{graphicx}

\begin{document}

\begin{frame}[c]{Video}
  \movie[]%
  {\includegraphics[width=\textwidth, height=\textheight, keepaspectratio]{thumbnail.png}}%
  {video.mp4}%
\end{frame}

\end{document}
```

I am getting this error when trying to play the video in pympress:

```
Traceback (most recent call last):
  File "/home/maxnoe/.local/lib/python3.10/site-packages/pympress/app.py", line 227, in do_open
    self.gui.swap_document(files[-1].get_uri())
  File "/home/maxnoe/.local/lib/python3.10/site-packages/pympress/ui.py", line 728, in swap_document
    self.do_page_change(unpause=False)
  File "/home/maxnoe/.local/lib/python3.10/site-packages/pympress/ui.py", line 1138, in do_page_change
    self.medias.replace_media_overlays(self.doc.page(self.current_page), draw_page)
  File "/home/maxnoe/.local/lib/python3.10/site-packages/pympress/extras.py", line 289, in replace_media_overlays
    v_da_c = factory(self.c_overlay, page_type, action_group, media)
  File "/home/maxnoe/.local/lib/python3.10/site-packages/pympress/media_overlays/gst_backend.py", line 56, in __init__
    self.media_overlay.pack_start(self.sink.props.widget, True, True,  0)
AttributeError: 'NoneType' object has no attribute 'props'
```

**Expected behavior**
Play the video

**Environment (please complete the following information):**
 - OS: Manjaro
 - Python version: 3.10.2
 - Pympress version: 1.7.1
 - Installation method: from pypi
 
**Debug information (see below for file locations)**
 - What is reported in pympress.log? What is show above and below
 - Does the problem still happen if you remove your config file? Yes

**Additional context**

There is another, seemingly unrelated error in the log:

```
ERROR:pympress.scribble:Error creating highlight cache
Traceback (most recent call last):
  File "/home/maxnoe/.local/lib/python3.10/site-packages/pympress/scribble.py", line 340, in reset_scribble_cache
    self.scribble_cache = window.create_similar_image_surface(cairo.Format.ARGB32, ww, wh, scale)
  File "/usr/lib/python3.10/site-packages/gi/module.py", line 155, in __getattr__
    setattr(wrapper, value_name, wrapper(value_info.get_value()))
ValueError: invalid enum value: 5
```

**Comment by leon-erd** [comment]
I had the same issue and installing `gst-plugin-gtk` also fixed it for me. Thanks a lot for the solution!!!

**Comment by cpbl** [comment]
I also cannot play video using beamer/multimedia/vlc/etc under Ubuntu. 

But apt says ` Unable to locate package gst-plugin-gtk`

**Comment by Cimbali** [comment]
Yes, gstreamer1.0-gtk3 is the package that contains the required library `libgstgtk.so` on ubuntu

**Comment by cpbl** [comment]
Thanks. So I am without a fix for my problem / playing a video. I can play the video from python using the vlc package, but it doesn't play in pympress.  However, I don't get the error messages in this Issue, so I probably should have opened a separate one.

**Comment by Cimbali** [comment]
Can you open a new issue @cpbl with a fresh log file of attempting to open the file in pympress?

**Comment by Cimbali** [comment]
Pinging @jose1711 @mans0954 so you can make sure in your respective packages that dependencies are supplied correctly. If you specify `gstreamer` (dependency or suggestion whichever it is) please also add Gstreamer’s gtk plugin (`gst-plugin-gtk-git` on arch and `gstreamer1.0-gtk3` on debian) with the same type of requirement.

**Comment by jose1711** [comment]
Added `gst-plugin-gtk` to optional dependencies on Arch.
