### ISSUE TITLE
Release a new version of pympress

### ISSUE THREAD

**Issue by Perangelot** [Cimbali/pympress#244]
Please release a new version of pympress so the newest version is available from package managers and does not need to be built from source.

**Comment by Cimbali** [comment]
Hmmm, there haven’t been a lot of changes, but maybe the `notes:` thing from #242 might be worth releasing on its own. I think there’s a number of translations added too. I was hoping to get #238 fixed before releasing but maybe that can wait for a later release.

**Comment by Cimbali** [comment]
1.7.2 is now out and available through usual channels
