### ISSUE TITLE
ModuleNotFoundError: No module named 'pkg_resources'

### ISSUE THREAD

**Issue by huyhoang8398** [Cimbali/pympress#245]
**Describe the bug**

**To Reproduce**
1. Install pympress with AUR wrapper
2. run `pympress` in terminal

**Expected behavior**
pympress runs without errors

**Screenshots**

![image](https://user-images.githubusercontent.com/25379882/173209835-95762d78-6c32-4a4a-9749-c1c1cf93ba31.png)

**Environment (please complete the following information):**
 - OS: Archlinux
 - Python version: Python 3.10.5
 - Pympress version: 1.7.1
 - Installation method: yay AUR

**Comment by huyhoang8398** [comment]
Fixed with #246

**Comment by Cimbali** [comment]
Interesting. `pkg_resources` is part of setuptools and we may not explicitly depend on it, because it used to be needed at installation… We may need to update this in more places than just AUR.

**Comment by Cimbali** [comment]
We stopped depending on `pkg_resources` since f7236ff
