### ISSUE TITLE
Durations and times in the Timing Breakdown window are human-unfriendly formatted.

### ISSUE THREAD

**Issue by Qrrbrbirlbel** [Cimbali/pympress#249]
**Describe the bug**
In the Timing Breakdown, times are not properly formatted. The columns' width can't be changed even though they sometimes cut off content.

**To Reproduce**
1. Do a timed presentation and view the timing breakdown window.

**Expected behavior**
The current display of time and duration in the timing breakdown window is formatted in a human-unfriendly format.

**Screenshots**
It looks like calculations are done to get the integer number of minutes but the number isn't truncated so that every minute value includes a trailing `.0`, the seconds are also given in decimal numbers (though I don't think that precision is needed) but sometimes they have only one decimal digit, sometimes two.

This makes it horrible to read the numbers and makes it hard to interpret them.
In addition, the columns' width can't be changed.

![Bildschirmfoto vom 2022-07-12 21-57-26](https://user-images.githubusercontent.com/4043967/178583326-52b06a4c-f4a1-4250-a555-7489897bf2b0.png)

The table should look like

| Time  | Duration | Slide |
| ---: | ---: | ---: |
| 0:00 | 3:07 | 1 ( 0/65)
| 0:00 | 0:11 | 1 ( 0/65)
| 0:11 | 2:48 | 1 ( 1/65)
| … | … | … 
| 3:02 | 0:05 | 29 (57/65)

Note that it's right-aligned, all numbers are truncated, and the seconds are leftpadded with `0`s.

**Environment:**
 - OS: Ubuntu 22.04
 - Python version: 3.10.4
 - Pympress version: 1.7.1 and 1.7.2
 - Installation method: apt (1.7.1) and pip (1.7.2)

**Debug information**
 - Nothing is reported in pympress.log when I open the timing breakdown window.
 - Does the problem still happen if you remove your config file? Yes.

**Comment by Cimbali** [comment]
Thanks for reporting! PRs welcome, as always. I’m not going to be able to look at this very soon.

I think except for the number formatting (left-padding, leading `.0` etc) it could all be adjusted in CSS or with a different Gtk widget, though the section-nesting is somewhat limiting.

**Comment by Qrrbrbirlbel** [comment]
> PRs welcome, as always.

I wish I could do that but I don't know what I'm doing: I cloned the repo, started VS code and want to run `__main__.py` and it uses `~/.local/lib/python3.10/site-packages/pympress/dialog.py` instead of the one that sits besides `__main__.py`.

I would probably get it to format the numbers correctly but I don't know how to operate VS code or python.

The values of the returned tuple `divmod(secs, 60)` in

https://github.com/Cimbali/pympress/blob/4b766df1eaad175d635135aae1e69e6548ea38b9/pympress/dialog.py#L104

needs to be truncated/`int`ed.

Could just be
```python
minutes = int(secs // 60)
seconds = int(secs - 60*minutes)
return '{:02}:{:02}'.format(minutes, seconds)
```

since the padding is apparently done by `.format` already.

And the columns need a few changes:

```glade
                  <object class="GtkTreeViewColumn" id="page_renderer">
                    <property name="resizable">True</property> <!-- this one -->
                    <property name="sizing">autosize</property> <!-- this one -->
                    <property name="title" translatable="yes">slide</property>
                    <child>
                      <object class="GtkCellRendererText"/>
                      <attributes>
                        <attribute name="xalign">1</attribute> <!-- this one -->
                        <attribute name="text">3</attribute>
                      </attributes>
                    </child>
                  </object>
                </child>
```

at least according to Glade 3.38.2 and [some online research](https://developer.gimp.org/api/2.0/gtk/GtkCellRenderer.html#GtkCellRenderer--xalign). Maybe?

**Comment by Cimbali** [comment]
`divmod` should return integers, at least when passed integers as input. I think `divmod(int(secs), 60)` should fix the formatting issues (or `{:02.0f}` otherwise). I’ve also tweaked the column settings to have the right widths, but can’t seem to manage to right-align the last column.

**Comment by Cimbali** [comment]
Alright I figured out alignment. We can’t do padding, unless we use fixed-size fonts, and those have serifs that make them hard to read and out of style with the rest of the window.

If you find a way to tell Gtk in a generic way that we want a monospaced sans-serif font I’ll reconsider, but as far as I can tell only 3 generic values exist: `monospace`, `serif`, and `sans`.

**Comment by Qrrbrbirlbel** [comment]
> `divmod` should return integers

I guess the seconds are not integers except for once at the start. I guess it uses milliseconds internally.

`divmod(int` has been to display the timer in the bar:

https://github.com/Cimbali/pympress/blob/e80a0a461493c960e75d2bb002bdff3d5c2f0c83/pympress/talk_time.py#L290

Can we use a [figure space](https://en.wikipedia.org/wiki/Figure_space) (it's what I've been using the my table above). But this isn't the most important aspect. It would be nice to have, though.  
The proper formatting of the numbers was much more important to make the dialog usable, in my opinion. Thank you.

I wish I knew how to instruct VSCode and/or Python to ignore installed package and use the ones that sits beside it. I can't even run your update without it defaulting to `site-packages`.

**Comment by Cimbali** [comment]
- To modify code, you should install the source code you’re modifying as “editable”, i.e. go to where you modified the code and do `pip install -e .`. It will replace the installed version, but you can later uninstall that and install a newer version
- To check out the latest master you can use the above with `git pull` to update the editable sources, or install from github as in the README: `pip install git+https://github.com/Cimbali/pympress.git`

Figure spaces sound good, but I’m not sure all digits have the same width? I’ll give it a shot.
