### ISSUE TITLE
Request: Freely arrange size of windows in presenter view

### ISSUE THREAD

**Issue by HeiniK** [Cimbali/pympress#25]
Might it be possible to allow the user to freely arrange the size of the windows showing notes, current slide and next slide? As far as I know, the only method at the moment is to shift a vertical bar which often leads to a lot of unused space.

**Comment by Cimbali** [comment]
I've noticed this too, however most options to freely arrange windows are rather complicated (e.g. requiring a "setup mode" where you can drag/drop/resize widgets).

One option that remains relatively simple is to have a second draggable bar in the right panel (between current slide and next slide, or next slide and annotations). Does that sound like an option to you? Or were you thinking more along the lines of a different configuration of the widgets?

**Comment by HeiniK** [comment]
Dear Cimbali,

first of all thanks for your fast simply and the great tool that pympress already is.

Of course free arrangement (position, size, etc.) would be perfect. But a second horizontal bar in the right panel would already be a valuable impovement. However, would it then be possible to give the user the option to select the content of each of the three windows? For example my preferred setup would be the current slide (biggest window) on the left, note slide on the upper right, next slide (smallest window) on the lower right.

**Comment by Cimbali** [comment]
Interesting, I didn't think of that configuration. I'll start thinking if there's a way to do all that.

**Comment by Cimbali** [comment]
Alright this is an attempt for a fully free layout of the presenter window. Some JSON in the config file will allow you to do anything you want, in the limit of the constraints given [in the validate_layout() function's docstring](https://github.com/Cimbali/pympress/blob/configurable_layout/pympress/ui.py#L390)

**Comment by HeiniK** [comment]
Would a modifiable config file also work with the windows binary install? If this is complicated could you add a horizontal moveable bar between current slide and next slide? And, to quote myself:

> Would it be possible to give the user the option to select the content of each of the three windows? For example my preferred setup would be the current slide (biggest window) on the left, note slide on the upper right, next slide (smallest window) on the lower right.

**Comment by Cimbali** [comment]
Yes, it also works with the binary install. To find the configuration file, open the about dialog (in the help menu).

**Comment by HeiniK** [comment]
Thanks. So the horizontal bar can be obtained by setting the value of the second "resizable" to "true" in the notes layout. Maybe it would be helpful to others as well to make this the default setting.
