### ISSUE TITLE
Highlighting Problem with Ubuntu 22.04 and Pympress 1.7.1

### ISSUE THREAD

**Issue by fsomenzi** [Cimbali/pympress#252]
Since updating to Ubuntu 22.04 and Pympress 1.7.1 highlighting only works on part of a slide as shown in the attached screenshot.
Highlighting outside of the upper-left rectangle disappears as soon as the pen is lifted from the screen.  I have a 4k screen with 200% scaling.  If I set the scaling to 100%, Pyimpress's highlighting works correctly (though everything gets way too small to be usable).
The problem occurs with both Wayland and Xorg.
![Screenshot from 2022-09-08 09-27-16](https://user-images.githubusercontent.com/19671990/189164903-24482cd6-f6b2-42ab-9b71-8428d463cded.png)

**Comment by Cimbali** [comment]
Thanks for reporting! Seems our coordinates computations forget about scaling somehow…

**Comment by Cimbali** [comment]
Reproducible by setting `GDK_SCALE=2`
