### ISSUE TITLE
player buttons enabled by default (when they should be disabled)

### ISSUE THREAD

**Issue by ousia** [Cimbali/pympress#259]
@Cimbali,

this comes from https://github.com/Cimbali/pympress/issues/227#issuecomment-970519802.

This [presentation](https://github.com/Cimbali/pympress/files/7475984/uncompressed-a.pdf) contains a video with autostart on page 2.

By default, Pympress shows player controls. But the [PDF spec](https://opensource.adobe.com/dc-acrobat-sdk-docs/standards/pdfstandards/pdf/PDF32000_2008.pdf#G12.2357434)  requires this “player-specific controller user interface” disabled by default (key **C** from Table 280).

Many thanks for your help and your excellent work.

**Comment by Cimbali** [comment]
Thanks for reporting!

Pympress makes the choice of always showing the controls on the presenter window.
On the content window however (which is shown to the public), the PDF spec is respected. See e.g. the example from #258.

**Comment by ousia** [comment]
Many thanks for your fast reply, @Cimbali.

It makes sense to me now.
