### ISSUE TITLE
Request: Internal pointer by using mouse on current slide in presenter mode

### ISSUE THREAD

**Issue by HeiniK** [Cimbali/pympress#26]
I am actually looking for something like using mouse arrow while holding Ctrl in powerpoint (https://www.youtube.com/watch?v=ttYOIVaJnf8). I know about the option to draw onto the current slide by pressing H. However, this is permanent and sort of messes up your slides if you highlight different things after each other. Also, it is sort of distracting to jump back and forth between presenter mode and drawing mode. Perfect for me (and colleagues) would be mimicking the powerpoint behaviour by directly using the mouse as pointer in presenter view inside the current slide window.

**Comment by Cimbali** [comment]
So you are suggesting a synthetic laser pointer that would be controlled with the mouse, is that right?

Would you point directly on the content (i.e. projector) window? Or on the presenter window (where the time and annotations are) with the pointer shown on the content (or possibly on both) window(s)?

The first option would force you to look at the projector/content window to use the feature, but I'm not sure that is a huge drawback as looking in your own screen to point at things would probably cut you off from your audience. What is your take on this?

(Implementation-wise, the first option could be as simple as changing the cursor while the "replicated pointer" option is probably a little heavier).

**Comment by Cimbali** [comment]
Have a look at the [emulated_laser_pointer](https://github.com/Cimbali/pympress/tree/emulated_laser_pointer) branch, where I implemented this feature. It works with ctrl + click.

I'm thinking of adding a menu option to choose between disabling altogether and red/green/blue pointers.

**Comment by HeiniK** [comment]
My idea was to point at the conentent on the current slide in the presenter view. I think it would be good to see the pointer in both windows (presenter and projector) so the presenter has a direct visual feedback what's going on in the projector window.

**Comment by HeiniK** [comment]
Would it be possible to create a binary (Win 7, 64bit, Python 3)? I did not manage to get the program running although I also installed pyGi.

**Comment by Cimbali** [comment]
I'll try to see what I can do for a binary, but I don't have access to my windows machine for a couple days, so it could take a while.

In the mean time, to run from source, you need python (2.7 or 3.4 but not newer), pygi, and to install pympress with:
`python -m pip install git+https://github.com/Cimbali/pympress@emulated_laser_pointer`
If that doesn't work, could you open an issue describing your problem?

**Comment by HeiniK** [comment]
At work I always have the newest Python version installed

**Comment by Cimbali** [comment]
I need to do some more thorough testing before I roll out a binary release, but you should be able to install any branch on any python install easily using pip.
For example: `python3.5 -m pip install git+https://github.com/Cimbali/pympress#egg=pympress`
However all dependencies need to be installed for that python version as well, so you might need to follow suggestions from #27 (I suspect in particular [how to import gi into anaconda's python](https://stackoverflow.com/questions/37526026/how-to-install-gi-module-for-anaconda-python3))
