### ISSUE TITLE
Remove references to deprecated distutils in setup.py

### ISSUE THREAD

**Issue by mans0954** [Cimbali/pympress#269]
There are a couple of references to `distutils` in `setup.py`:

https://github.com/Cimbali/pympress/blob/master/setup.py#L37-L38

`distutils` are [deprecated](https://docs.python.org/3/library/distutils.html) and will be removed in Python 3.12.

Hopefully it is a simple matter to remove them?

Thanks.

**Comment by Cimbali** [comment]
We need to look into what the new way of overriding commands is. If setuptools vendored distutils, it's probably as simple as changing the import statement and setting a min version on the required setuptools
