### ISSUE TITLE
No module named gi

### ISSUE THREAD

**Issue by PierreQuinton** [Cimbali/pympress#27]
Hi,
I'm working on ubuntu 17.04 with gnome 3 and I installed it using `pip install pympress`. I also installed the dependencies using ```apt-get install python3 python3-pip libgtk-3-0 libpoppler-glib8 libcairo2 python3-gi python3-cairo gir1.2-gtk-3.0 gir1.2-poppler-0.18``` and I get the following error :
![image](https://user-images.githubusercontent.com/13201912/27122557-660fac7c-50eb-11e7-8e08-7cb4d06bd6b1.png)

Any idea ?

**Comment by Cimbali** [comment]
If you installed `python3-gi` you really should have the `gi` module. I'm afraid I can't be of much help right now, as I don't have an ubuntu to check how the packages are installed.

It does seem that you are using a python version inside an installation of anaconda, I don't know if that's normal or not. Supposing you have a different python installation, you maybe installed `gi` for one and `pympress` for the other. In that case, try forcing the python outside the anaconda installation (for example in the default location, `/usr/bin/python3`):

    /usr/bin/python3 -m pip install pympress
    /usr/bin/python3 -m pympress

If that fixes it, you should check what defaults where as python installations go, on your system.

**Comment by FriedrichFroebel** [comment]
Maybe the workflow described in [this Stackoverflow question](https://stackoverflow.com/questions/37526026/how-to-install-gi-module-for-anaconda-python3) allows you to use the `gi` module from your Anaconda installation.

**Comment by PierreQuinton** [comment]
Thank you for the answer, I think we can close this one.

**Comment by PierreQuinton** [comment]
Hi,

I had another problem with the import of cairo, I tried solving it in the same fashion but it didn't work, after a few research it appears that there is no cairo for python2 and so we need to use python3 (which I thought would be done using pympress3) but at the begining of the file in /usr/bin/pympress and /usr/bin/pympress3 we have the following line :
```#!/usr/bin/python```
changing it to python3 worked for me :
```#!/usr/bin/python3```

**Comment by FriedrichFroebel** [comment]
Using `apt-cache search python cairo` on my Ubuntu system, there is a Cairo package for Python2 (shortened output):

> python-cairo - Python bindings for the Cairo vector graphics library
> python-cairo-dbg - Python bindings for the Cairo vector graphics library (debug extension)
> python-cairo-dev - Python cairo bindings: development files
> python3-cairo - Python 3 bindings for the Cairo vector graphics library
> python3-cairo-dev - Python 3 cairo bindings: development files
> python3-cairo-doc - Python 3 cairo bindings: documentation files
> python3-gi-cairo - Python 3 Cairo bindings for the GObject library
> python-gi-cairo - Python Cairo bindings for the GObject library

Another alternative (instead of modifying the Shebang line of an installed package): Calling `python3 -m pympress` from the terminal should do the trick to (when doing so, the Shebang line is ignored).

**Comment by Cimbali** [comment]
if it works for you we can close this issue, @PierreQuinton.

The moral of the story is to make sure the same python installation if used for pympress as well as for all its dependencies.
