### ISSUE TITLE
Please create a new release

### ISSUE THREAD

**Issue by ZvikaZ** [Cimbali/pympress#270]
Can you create a new release? (at least for Windows)

I was surprised that Adobe Reader, with all its bloat, is running smoother than Pympress. But then I saw at https://pympress.github.io/README.html that there is a caching option (which might speed up things) - and I don't seem to have it in my version (unless it's hidden really well ;) ).
Also, zooming doesn't work for me - but, again, the latest release is quite old now, maybe it has already been fixed, so, no point to report it.

Anyway, this is really a great software! Today I had a presentation, with a Beamer-created PDF, and it was much easier to present it with Pympress than with a regular PDF reader.

Thanks

**Comment by Cimbali** [comment]
Caching and zooming are both available in the latest release.

**Comment by ZvikaZ** [comment]
Interesting.
I've started to fill an issue for zoom not working. As requested in the template, I've moved away the config file - and it solved the problem...

**Comment by Cimbali** [comment]
Maybe a shortcuts issue then?

**Comment by ZvikaZ** [comment]
I have no idea. I've skimmed the .ini file, and nothing seems suspicious. The shortcuts makes sense, `zoom = z`, and there is nothing contradicting it.

Let's ignore that :-)

Regarding the un-smoothness - well, if I will encounter it again, I will open an issue.

So, your call - if you want to keep this issue open, as a reminder to create a new release (there *are* some new features and bug fixes in the commit list - not critical, I agree, but it'd be nice to have them some day...), or if you prefer to close it.

Your repo, after all ;-)

**Comment by Cimbali** [comment]
There will be a release soon, there’s 1 more change I’d like to include − discussed in #9
