### ISSUE TITLE
zooms back to an overview screen

### ISSUE THREAD

**Issue by Elfengour** [Cimbali/pympress#271]
Zooms back to an overview screen showing all pages of the presentation, this would be an amazing feature.

![zoomback](https://user-images.githubusercontent.com/28195778/219867449-9c16ab9b-4c09-45c9-a6cd-be840ee1e1db.png)

**Comment by Cimbali** [comment]
Some discussion on this happened in #162 iirc (even though that issue ended up being about something else)
