### ISSUE TITLE
Audio is played twice at the same time

### ISSUE THREAD

**Issue by f0k** [Cimbali/pympress#277]
**Describe the bug**
When playing back a video and both the presenter and content view are open, the sound of the video is played twice. If the playback is not perfectly synchronous, the sound gets some metallic feel to it.

**To Reproduce**
1. Open a PDF file with an embedded video from an external file (using LaTeX's `\movie` command). Preferably one that has vocals, that makes it easier to spot.
2. Play the video. Possibly stop and play some more times to get a different time shift.

**Expected behavior**
The video should be muted for one of the two views. (I assume that is easier than ensuring sample-perfect synchronization between the two playbacks.)

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Python version: 3.10.6
 - Pympress version: master
 - Installation method: source

**Debug information (see below for file locations)**
 - What is reported in pympress.log?
```
INFO:pympress.app:Pympress: 1.8.0b2+11@3b8867d ; Python: 3.10.6 ; OS: Linux 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 ; Gtk 3.24.33 ; GLib 2.71.3 ; Poppler 22.02.0 cairo ; Cairo 1.16.0 , pycairo 1.20.1
INFO:pympress.extras:Media support: GdkPixbuf gif player, GStreamer 1.20.3, VLC not available
WARNING:pympress.ui:Not starting content or presenter window full screen because there is only one monitor
```
 - Does the problem still happen if you remove your config file? Yes.

**Comment by Cimbali** [comment]
Interesting. One of the versions should be muted by default, as we had this issue before:

https://github.com/Cimbali/pympress/blob/401a65507d7ae5599d0c00fa8da23ddb0ff2512d/pympress/extras.py#L294-L295

So this seems to fail for some reason.

**Comment by Cimbali** [comment]
It seems that whatever we set in `set_property('mute', …)` on the gstreamer playbin is ignored, as querying later on always returns `False`.
