### ISSUE TITLE
Support cx_Freeze version 5.x

### ISSUE THREAD

**Issue by FriedrichFroebel** [Cimbali/pympress#28]
When running the cx_Freeze setup script on Windows, an error is thrown:

> running build_exe
> error: error in setup script: command 'build_exe' has no such option 'compressed'

Seems like the support for this option has been dropped some time ago: https://github.com/anthony-tuininga/cx_Freeze/issues/253.

By the way: Is there any documentation on how to obtain the installer for the `pympress` installer (tried it on Windows)? After removing the the `compressed` option from the corresponding dictionary, a folder got created, but after trying to start the `pympress.exe` file from the command line, it got closed after some time without any visible output.

**Comment by Cimbali** [comment]
Yes sorry I should state this in a README somewhere. `cx_Freeze` people have re-written their automatic dependency detection for versions 5.x, and that broke packages like `gi`. You have to use cx_Freeze 4.3.4 (which you can install with `pip install cx_Freeze==4.3.4`). That is also when they dropped the `compressed` option.

Most likely the error in pympress.exe is about these missing dependencies, IIRC you can see the messages on the console if you run `python -m pympress` instead of just `pympress` on windows.

**Comment by FriedrichFroebel** [comment]
With the older `cx_Freeze` version the executable can be started as expected.

I did not know that it is possible to run an executable with Python - and Python complains about this when trying to run `python -m pympress` from the `build` directory: `No module named pympress`.

Is there any way to get it to work with the latest `cx_Freeze` version? I tried to run run a diff tool to determine the differences, but there is a nearly complete different package structure (I disabled the `compressed` option for both). The `etc`, `lib` and `share` folder seem to have the same content in both cases.

**Comment by Cimbali** [comment]
I remember some bug report from cx_Freeze about `gi` not working any more with version 5.0 but I can't find it right now. An alternative is to use `pyinstaller` however I've not looked at it yet.

And you're right that running a compiled executable from `python` makes no sense, I got confused there. Maybe running from the command line (the `cmd` window) still gives useful output on stdout or stderr? Otherwise we'll have to see about the logger catching exceptions.

**Comment by FriedrichFroebel** [comment]
I tried to run the executable created by the latest version on the command line multiple times when testing this. My device is working for some time (around 20 seconds or so) and then I can insert the next command on the command line. The executable appears in the task manager during this. There is no output when running.

Comparing the size of the `pympress.exe` file, the new one is only 10.8 KB, whereas the old one is 1.3 MB.

**Comment by Cimbali** [comment]
All right, the last commit I just pushed to master, 8f93f5c, will log everything to a `pympress.log` file in the current working directory. At least you should know what happens, that way.

**Comment by FriedrichFroebel** [comment]
The log file contains the following error when running `pympress.exe`:

```
CRITICAL:__main__:Uncaught exception:
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
    module.run()
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
    exec(code, m.__dict__)
  File "pympress\__main__.py", line 125, in <module>
  File "pympress\__main__.py", line 115, in main
  File "pympress\ui.py", line 56, in <module>
  File "C:\Users\Me\Documents\pympress3\build\exe.win-amd64-3.4\pympress\document.py", line 511
    poppler_doc = Poppler.Document.new_from_file(urlunsplit((scheme, netloc, path, *more)), None)
                                                                                              ^
SyntaxError: can use starred expression only as assignment target
```

**Comment by Cimbali** [comment]
Surprisingly that doesn't fail for me, though it should according to the documentation. Fixed it anyhow, but this is code that arrived in the latest push from today, so not the bug you're looking for.

**Comment by Cimbali** [comment]
Here's the error I get (in a popup window actually) when running a version frozen with cx_freeze v5.0.2:

```
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
    module.run()
  File "C:\Python34 \lib\site-packaga\a_Freeze\initscripts\Console.py", line 26, in run
    exec(code, m.__dict__)
  File "pympress\__main__.py", line 34, in <module>
    import gi
  File "C:\Python34 \lib\site-packages\gi\__init__.py", line 42, in <module>
    from . import _gi
ImportError: DLL load failed: The specified module could not be found. 
```

**Comment by FriedrichFroebel** [comment]
Very strange: After fetching your latest commit, the main GUI window is shown, but an error is written to the log when trying to open a file from the file picker:

```
CRITICAL:__main__:Uncaught exception:
Traceback (most recent call last):
  File "C:\Documents\Me\pympress3\pympress\ui.py", line 593, in pick_file
    self.swap_document(os.path.abspath(dialog.get_filename()))
  File "C:\Documents\Me\pympress3\pympress\ui.py", line 336, in swap_document
    self.doc = pympress.document.Document.create(docpath)
  File "C:\Documents\Me\pympress3\pympress\document.py", line 511, in create
    poppler_doc = Poppler.Document.new_from_file(urlunsplit((scheme, netloc, path) + more), None)
TypeError: can only concatenate tuple (not "list") to tuple
```

When casting `more` by using `tuple(more)`, another error is thrown:

```
CRITICAL:__main__:Uncaught exception:
Traceback (most recent call last):
  File "pympress\ui.py", line 593, in pick_file
  File "pympress\ui.py", line 336, in swap_document
  File "pympress\document.py", line 511, in create
GLib.Error: g_convert_error: The URI 'c:\Documents\Me\test.pdf' is not an absolute URI using the "file" scheme (4)
```

**Comment by Cimbali** [comment]
Hmmm, it appears `urlsplit` blieves "C:" to be a scheme. That's unfortunate. Try the following:

    try:
        url = urljoin('file:', pathname2url(path))
    except OSError:
        # actually an url, not a path, was passed directly
        url = path
    poppler_doc = Poppler.Document.new_from_file(url, None)

**Comment by FriedrichFroebel** [comment]
After adding the `urljoin` import for Python3, the PDF file could be opened applying your suggested change to the source files before building.

**Comment by Cimbali** [comment]
Alright, so for which version of cx_freeze did you get this to work? v5.0.2 or v4.3.4 ?

**Comment by FriedrichFroebel** [comment]
I used cx_freeze v5.0.2 with the `compressed` option removed.

**Comment by Cimbali** [comment]
Alright, can you send some details on what you're running? Which cx_freeze command, OS, 32/64 bits, python version, etc? Maybe the ouput of `pip --list` as well? And could you zip the `bdist` that you built so I can try and run it, and see which files are included?

**Comment by FriedrichFroebel** [comment]
I used the `build_exe` command from cx_freeze. My system is Windows 8.1 (64 bit) with Python 3.4 (64 bit). When running `pip list`, I get the following output:

> cx-Freeze (5.0.2)
> pip (9.0.1)
> py2exe (0.9.2.2)
> pygobject (3.18.2)
> python-vlc (1.1.2)
> setuptools (18.2)

I have appended a compressed version of the `build/` directory. This has been built using the `bdist` option and disabled VLC support. I do not know why the `bdist.win-amd64` folder is empty, but I am getting an error after the `build\bdist.win-amd64\dumb` gets removed (`PYTHONPATH` is set):

```
C:\Python34\python.exe: Error while finding spec for 'cxfreeze_setup.py' (<class 'AtrributeError'>: 'module' object has no attribute '__path__')
```

[build.tar.gz](https://github.com/Cimbali/pympress/files/1095390/build.tar.gz)

**Comment by Cimbali** [comment]
I did some more testing, on my machine and in virtual machines with nothing pre-installed to avoid any environment issues. Turns out the files from `build_exe` seem to work (both 32 & 64 bit, though the first execution takes forever), however those generated by `bdist_msi` do not.

We can work with that, building the tool with `python cxfreeze_setup.py build_exe` and using a different tool to distribute using an installer, so hereby this issue is closed.

For future reference, the two file trees (`build/exe....` and the install destination chosen at install time by `bdist_msi`) are very similar. If we except empty directories, these are the only differences:
```
Only in installed_pympress/Lib: site-packages
Files build_exe/pympress.exe and installed_pympress/pympress.exe differ
Files build_exe/python34.zip and installed_pympress/python34.zip differ
```
And the contents of `installed_pympress/Lib/site-packages/` are the sources and cached compiled versions of said sources: 
```
site-packages/pympress/document.py
site-packages/pympress/surfacecache.py
site-packages/pympress/ui.py
site-packages/pympress/util.py
site-packages/pympress/vlcvideo.py
site-packages/pympress/__init__.py
site-packages/pympress/__main__.py
site-packages/pympress/__pycache__/document.cpython-34.pyc
site-packages/pympress/__pycache__/surfacecache.cpython-34.pyc
site-packages/pympress/__pycache__/ui.cpython-34.pyc
site-packages/pympress/__pycache__/util.cpython-34.pyc
site-packages/pympress/__pycache__/vlcvideo.cpython-34.pyc
site-packages/pympress/__pycache__/__init__.cpython-34.pyc
site-packages/pympress/__pycache__/__main__.cpython-34.pyc
```
