### ISSUE TITLE
Pympress crashes on start on Fedora 38 beta.

### ISSUE THREAD

**Issue by cgevans** [Cimbali/pympress#283]
**Describe the bug**

On the Fedora 38 beta, running Wayland and using GDK_BACKEND=wayland, Gdk.Display.get_primary_monitor returns None.  As a result, ScreenArea.lookup_monitors fails, and pympress fails on startup.

There appear to be several fundamental limitations that prevent screen positioning from functioning properly with Wayland and Gtk (eg, window position information is not actually meaningful).  However, changing this code to simply return *something* for the primary monitor will result in pympress working, with the limitation that some window positioning will not work.

**To Reproduce**
1. Start pympress, under the conditions noted.

**Environment (please complete the following information):**
 - OS: Fedora 38 beta
 - Python version: 3.11.2
 - Pympress version: 1.8.0 and 8702f2e
 - Installation method: copr (release) and pip (git)

**Comment by Cimbali** [comment]
Thanks for the report and fix. There seems to be  “no concept of primary screen” on wayland which even caused gtk 4 to [retire the API][https://gitlab.gnome.org/GNOME/gtk/-/issues/1028). I think we’ll have to parse EDID screen info in the future or something medieval like that…
