### ISSUE TITLE
Notes are misaligned

### ISSUE THREAD

**Issue by AtivJoshi** [Cimbali/pympress#290]
**Describe the bug**
When the "notes position" is set to "after slide pages", the notes are completely misaligned.

**To Reproduce**
1. Make a beamer where notes are shown after the slide.
2. Add the option `\addtobeamertemplate{note page}{}{\thispdfpagelabel{notes:\insertframenumber}}`
3. Start pympress, enable notes mode, and, select `Presentation > Notes position > After slide pages`
4. Some non-note slides are only shown in the notes section. Notes of some other slides are shown for the current slide.

**Expected behavior**
Notes of the current slide need to be displayed.

**Screenshots**
[Screencast from 21-05-23 09:10:57 AM IST.webm](https://github.com/Cimbali/pympress/assets/20719103/e9c4745e-6830-4a84-adc3-34fae76542d3)

**Environment (please complete the following information):**
 - OS: Ubuntu with Gnome
 - Python version: 3.10.6
 - Pympress version: 1.7.1
 - Installation method: apt-get

**Debug information (see below for file locations)**
 - What is reported in pympress.log? n/a
 - Does the problem still happen if you remove your config file? Yes

**Additional context**
I am not sure if the issue is with generating the latex file. I have generated a sample beamer for MWE on Overleaf which can be accessed here: https://www.overleaf.com/read/mbbqvqbfpxnx. Although the issue remains even if I compile the beamer locally on my machine. I am pasting the latex code for MWE here as well: 

```
\documentclass[notes]{beamer}
\usepackage{graphicx} % Required for inserting images

\title{pympress}
\author{Anon}
\date{Title page has no notes}
\addtobeamertemplate{note page}{}{\thispdfpagelabel{notes:\insertframenumber}}
\begin{document}
\begin{frame}
    \titlepage
\end{frame}

\begin{frame}{Introd}
This is frame 1. This has no notes
\end{frame}

\begin{frame}{Frame 2}
    This is frame 2.
    \note[item]{This is note for frame 1}

\end{frame}
\begin{frame}{Frame 3}
    This is frame 3.
    \note[item]{This is note for frame 3}

\end{frame}
\begin{frame}{Frame 4}
    This is frame 4.
\end{frame}
\begin{frame}{Frame 5}
    This is frame 5.
\end{frame}
\begin{frame}{Frame 6}
    This is frame 6.
    \note[item]{This is note for frame 6}

\end{frame}
\end{document}
```

**Comment by Cimbali** [comment]
If you use `\addtobeamertemplate{note page}{}{\thispdfpagelabel{notes:\insertframenumber}`, then the corresponding option for notes position is `Prefixed labels` not `After slide pages`. I think possibly:
- we should clarify this in the documentation
- we could rename `After slide pages` to `At the end of the document` or something like that to be less confusing. (It doesn’t mean after each page but after all pages, for slides generated by libreoffice.)

However if you start pympress and open that document without changing the slide positions, it should auto-detect the `Prefixed labels` -- does that not happen for you?

**Comment by AtivJoshi** [comment]
Thank you.
