### ISSUE TITLE
Improve Annotations

### ISSUE THREAD

**Issue by Cimbali** [Cimbali/pympress#291]
### Discussed in https://github.com/Cimbali/pympress/discussions/288

<div type='discussions-op-text'>

<sup>Originally posted by **Lazaro10e0** May 20, 2023</sup>
I love this tool since it allows me to present perfectly my latex beamer slides. The only problem is the quality of my annotations. I use a tablet to draw in the slides while presenting, but I find it quite difficult to write with good quality. Not only because it doesn't detect thickness/pressure, also the minimum thickness is very thick and the path is not exactly what is being drawn. 

If we could improve this it good be more than perfect tool!!
Thanks </div>

<div type='discussions-op-text'>

<sup>Originally posted by **Lazaro10e0** May 30, 2023</sup>
[…] I attach an image where you can see in the spiral it is not smooth, it looks like it is done with small straight lines. I can notice perfectly that this happens when you write it quickly. If you do it slowly it seems very smooth.

![image](https://github.com/Cimbali/pympress/assets/6126377/92511286-b04e-47fb-904f-4f875ee93b15)
 </div>

**Comment by Cimbali** [comment]
So I think:
- changing the minimum thickness is quite easy to do,
- smoother lines could be achieved by getting more frequent mouse events. How to do that is not quite clear, probably drawing outside of the main thread?
- passing [`Gdk.AxisUse.PRESSURE`](https://lazka.github.io/pgi-docs/#Gdk-4.0/enums.html#Gdk.AxisUse.PRESSURE) in [`event.get_axis()`](https://lazka.github.io/pgi-docs/#Gdk-4.0/classes/Event.html#Gdk.Event.get_axis) should return pressure info on devices that support it.

**Comment by Cimbali** [comment]
I think maybe the calculations used for bezier curves may be a little too simplistic which may contribute to lack of smoothness.

**Comment by Cimbali** [comment]
Can you try the current master @Lazaro10e0? It should allow thinner lines, support erasers and pressure, and hopefully have smoother drawing too (though I’m not 100% on that last one.)

**Comment by Cimbali** [comment]
Sure, you can [download it here](https://github.com/Cimbali/pympress/releases/tag/v1.8.3a)

If you could include a screenshot of what drawing looks like now, that would be nice. Unfortunately I don’t have the necessary hardware to properly test these features.

**Comment by Lazaro10e0** [comment]
Wow, you are a magician. I love it.
![image](https://github.com/Cimbali/pympress/assets/38687716/bd37226c-0bfe-4f8d-8257-9abcaf94f2aa)
One more thing you can improve in this regard is the eraser. It doesn't allow to make it thinner and becomes quite useless since it is huge. At the moment I use undo to erase which works very well most of the cases.
![image](https://github.com/Cimbali/pympress/assets/38687716/a211c5cb-46fd-46d5-9a79-6e9858a5bb04)

**Comment by Lazaro10e0** [comment]
In case it is not clear in normal handwritting here you can check that curves are perfectly captured and pressure also!
![image](https://github.com/Cimbali/pympress/assets/38687716/5a1d3632-a078-4862-9167-cc2cae47716a)

**Comment by Cimbali** [comment]
Fantastic! I’ll check the eraser, its thickness setting should not be disabled.
