### ISSUE TITLE
Incorrect rendering of greek and math symbols on windows in plots generated with R

### ISSUE THREAD

**Issue by JessicaSilvaLomba** [Cimbali/pympress#293]
**Describe the bug**
I created .pdf plots in R containing greek letters and math symbols on the labels. These were included in a beamer LaTeX presentation with notes and are perfectly rendered in Acrobat Reader. However, when using pympress, some of these symbols are not rendered, resulting in a blank square. I attached example prints bellow of pympress vs. Acrobat rendering. Is there any way to fix this issue? Thank you.

**To Reproduce**
1. In R, run for example:
```
pdf(file="Example.pdf")
tau.4<-function(tau.3){tau.3*(1+5*tau.3)/(5+tau.3)}

curve(tau.4(x),0,0.8,xlab = expression(tau[3]), 
      ylab = expression(tau[4]), col='grey70',lwd=2)

legend(0.01,0.7,legend=c(expression(paste("(",tau[3],",",tau[4],")" %~~% "(",0.43,",",0.25,") for GP(",xi==0.2,")")),
                          expression("ALRSM: u* = Q(73.1%)" %~~% "0.7243 - i=14")),
        title="Random sample of size 500 of a Hybrid(0.75,0.2)",
        col=c('green','red'), pch = c(2,20), bty='n',pt.lwd=c(2,1), pt.cex = c(1.5,2))

dev.off()
```
2. On LaTeX beamer document, include
```
\frame{
\begin{figure}
    \includegraphics{Example.pdf}
    \caption{Figure}
\end{figure}
\note{some presenter note}
}
```
3. Compile using pdfLaTeX
4. Present with pympress

**Expected behavior**
Correct rendering of greek letters and other math symbols when presenting in pympress.

**Screenshots**
pympress:
![image](https://github.com/Cimbali/pympress/assets/81690695/e47fc2dd-cbc1-4f7a-b2ee-006a3ba21792)
acrobat:
![image](https://github.com/Cimbali/pympress/assets/81690695/f677c451-b165-44ee-ac52-529dfdc374b6)

**Environment (please complete the following information):**
 - OS: Windows
 - Python version: 3.10.10
 - Pympress version: 1.8.2
 - Installation method: Windows App Installer

**Debug information (see below for file locations)**
 - What is reported in pympress.log?
_INFO:pympress.app:Pympress: 1.8.2 ; Python: 3.10.10 ; OS: Windows 10 10.0.19045 ; Gtk 3.24.38 ; GLib 2.76.1 ; Poppler 23.03.0 cairo ; Cairo 1.17.8 , pycairo 1.23.0
INFO:pympress.extras:Media support: GdkPixbuf gif player, GStreamer not available, VLC not available
WARNING:pympress.ui:Gtk.Application.inhibit failed preventing screensaver, trying hard disabling
INFO:pympress.app:Pympress: 1.8.2 ; Python: 3.10.10 ; OS: Windows 10 10.0.19045 ; Gtk 3.24.38 ; GLib 2.76.1 ; Poppler 23.03.0 cairo ; Cairo 1.17.8 , pycairo 1.23.0
INFO:pympress.extras:Media support: GdkPixbuf gif player, GStreamer not available, VLC not available
WARNING:pympress.ui:Gtk.Application.inhibit failed preventing screensaver, trying hard disabling
INFO:pympress.app:Pympress: 1.8.2 ; Python: 3.10.10 ; OS: Windows 10 10.0.19045 ; Gtk 3.24.38 ; GLib 2.76.1 ; Poppler 23.03.0 cairo ; Cairo 1.17.8 , pycairo 1.23.0
INFO:pympress.extras:Media support: GdkPixbuf gif player, GStreamer not available, VLC not available
WARNING:pympress.ui:Gtk.Application.inhibit failed preventing screensaver, trying hard disabling
CRITICAL:__main__:Uncaught exception:
Traceback (most recent call last):
  File "D:/a/pympress/pympress/pympress/ui.py", line 997, in pick_file
  File "D:/a/pympress/pympress/pympress/ui.py", line 834, in swap_document
  File "D:/a/pympress/pympress/pympress/deck.py", line 125, in setup_doc_callbacks
  File "D:/a/pympress/pympress/pympress/deck.py", line 155, in create_drawing_areas
TypeError: Argument 1 does not allow None as a value
CRITICAL:__main__:Uncaught exception:
Traceback (most recent call last):
  File "D:/a/pympress/pympress/pympress/ui.py", line 997, in pick_file
  File "D:/a/pympress/pympress/pympress/ui.py", line 834, in swap_document
  File "D:/a/pympress/pympress/pympress/deck.py", line 125, in setup_doc_callbacks
  File "D:/a/pympress/pympress/pympress/deck.py", line 155, in create_drawing_areas
TypeError: Argument 1 does not allow None as a value
INFO:pympress.app:Pympress: 1.8.2 ; Python: 3.10.10 ; OS: Windows 10 10.0.19045 ; Gtk 3.24.38 ; GLib 2.76.1 ; Poppler 23.03.0 cairo ; Cairo 1.17.8 , pycairo 1.23.0
INFO:pympress.extras:Media support: GdkPixbuf gif player, GStreamer not available, VLC not available
WARNING:pympress.ui:Gtk.Application.inhibit failed preventing screensaver, trying hard disabling_

 - Does the problem still happen if you remove your config file?
   (You can just move the config file to a different location to be able to restore it after testing)
_Yes_

**Additional context**
N/A

**Comment by Cimbali** [comment]
Thanks for reporting! Likely a fonts issue. Could you provide the PDF file as well?

**Comment by Cimbali** [comment]
I’m guessing a missing package like [`cbfonts`](https://ctan.org/tex-archive/fonts/greek/cbfonts)

**Comment by JessicaSilvaLomba** [comment]
> 

It does happen when opening the image directly in pympress, yes. 
I'm attaching the image pdf as well as a pdf of part of the presentation (cannot share the whole file as this will be my phd defense in a few days). 
[Example_1sample_Hybrid_ALRSM.pdf](https://github.com/Cimbali/pympress/files/11908703/Example_1sample_Hybrid_ALRSM.pdf)
[DEFESA__MWE.pdf](https://github.com/Cimbali/pympress/files/11908738/DEFESA__MWE.pdf)
Is it fixable? =)

**Comment by complanar** [comment]
I just tested the files and they are both working for me. I use 
- pympress v1.7.1 under linux with
- Python 3.10.6
- Gtk 3.24.33 
- GLib 2.71.3 
- Poppler 22.02.0 cairo 
- Cairo 1.16.0 
- pycairo 1.20.1

**Comment by complanar** [comment]
Just tried a bunch of other pdf viewers, they all display the file correctly under my setting.

**Comment by Cimbali** [comment]
Hmmm same here, pympress displays the file OK on my setup.

**Comment by JessicaSilvaLomba** [comment]
> Hmmm same here, pympress displays the file OK on my setup.

Can this be an issue with Windows 10 Home? I installed pympress directly from the Windows App Installer yesterday so everything should be up to date. Any suggestion on how I can troubleshoot this? Or add the font package?
![image](https://github.com/Cimbali/pympress/assets/81690695/848625a7-da01-4396-8cd7-faa124a608c8)
![image](https://github.com/Cimbali/pympress/assets/81690695/8f26e2fe-4baa-4b5b-bcff-291f2896be99)

**Comment by JessicaSilvaLomba** [comment]
> Just tried a bunch of other pdf viewers, they all display the file correctly under my setting. So this does not seem to be an issue with the file itself.

I tried Acrobat, Foxit, Edge pdf viewer and none all display the file correctly as well, but none allow for the presenter notes on second screen setting.

**Comment by complanar** [comment]
I use pympress for a reason, but maybe [pdfpc](https://github.com/pdfpc/pdfpc) could be a quick alternative/workaround for you. Unfortunately it is much more complicated to get running on windows than on linux.

@Cimbali Please excuse the proposal of alternative software here, but I think this in accordance to the spirit of OSS and I wanted to help @JessicaSilvaLomba as it seems to be urgent.

**Comment by Cimbali** [comment]
No worries @complanar. They might have the same issue as they use similar solutions than pympress but it’s worth a try. I think it’s likely a default font we (erroneously) don’t include in the windows installer, but haven’t had much time to look into it tbh.

Another workaround is to embed the plots as png files instead of pdf, that way there’s no rendering issues.

**Comment by JessicaSilvaLomba** [comment]
@complanar and @Cimbali
Thank you for your suggestions! I will look into pdfpc again (I had some trouble getting it properly installed before) and if I have no luck with that I'll get to converting my plots to png. Thanks for your help. 
I'll leave this issue here open in case you get around to including the fonts on the installer later.

**Comment by Cimbali** [comment]
Can reproduce. The police used is Symbol, so a very standard postscript police.

**Comment by Cimbali** [comment]
As a workaround, [this ggplot2 SO question](https://stackoverflow.com/questions/38448658/ggplot2-embed-all-used-fonts-in-pdf-r) suggests the following workaround should work:
̀ ``R
embedFonts(file=filepath_fonts_not_embedded, outfile=filepath_fonts_embedded)
```

As a more long-standing solution, I think we should consider whether to include type 1 fonts in the windows pympress distributables. It’s worth noting they are [not supported anymore](https://helpx.adobe.com/uk/fonts/kb/postscript-type-1-fonts-end-of-support.html) though.

**Comment by Cimbali** [comment]
It seems we can just include the [ghostscript fonts](https://sourceforge.net/projects/gs-fonts/) in the install’s fonts directory and poppler will pick them up.
