### ISSUE TITLE
[Windows] Not loading the proper language

### ISSUE THREAD

**Issue by 24mu13** [Cimbali/pympress#297]
**Describe the bug**
When starting on WIndows it does not load the proper language, as any other app does (e.g. Kate).

**To Reproduce**
Steps to reproduce the behaviour (Powershell):
1. `winget install pympress`
2. `$env:LANG = 'it'`
3. `pympress`
4. You don't get the expected language

**Expected behaviour**
Pympress showing UI in the set language.

**WORKAROUND**
Use the previous version 1.8.2 (!)

**Environment (please complete the following information):**
 - OS: Windows
 - Python version: (embedded?)
 - Pympress version: 1.8.3
 - Installation method: winget

**Comment by Cimbali** [comment]
Thanks for reporting! Will look into it
