### ISSUE TITLE
Recomend using pipx instead of pip

### ISSUE THREAD

**Issue by ChausseBenjamin** [Cimbali/pympress#312]
Many distributions now recommend against using pip to install packages
outside of a virtual environment since doing otherwise can break certain
package managers. The recommended way of installing packages is to use [pipx][1].

I just tried doing so with your application and this is what was necessary

```sh
pipx install pympress
pipx inject pympress pycairo pygobject
```

The software works great doins so. I just that it would be a nice addition/correction inside the README and in the documentation of the package.

Have a nice one ;)

[1]: https://github.com/pypa/pipx

**Comment by complanar** [comment]
This seems a good idea, but does not work in all environments. E.g. this way gstreamer or vlc may not found. Embedded videos can not be played. Works when install via pip (at least for me).

**Comment by Cimbali** [comment]
> Many distributions now recommend against using pip to install packages

Yes there’s been this push even within pip. I must say I’ve silenced all these warnings with `break-system-packages = true` (which is a quite aggressive option name) but we shouldn’t expect users to install via a deprecated way.

Before we update install instructions, I think we have to look at what the state of the situation is:
- the best solution is to use system/package manager distributed packages, and that includes pympress.
- `pipx` makes installing into virtual environments easy, but you first have to install pipx
- It used to not be desirable to install the `pygobject` and `pycairo` dependencies in non-standard locations (user, virtual environment, etc) as building from scratch required compiling C modules. We want people to be able to install easily without requiring installing compiler toolchains, headers/development packages, etc.
- Even if pygobject and pycairo get installed as binary wheels, people need the proper system packages.

We also need to review the impact of using pip on all relevant distributions.

**Comment by Cimbali** [comment]
Ok I’ve had to rewrite the error message and add some significant caveats to the python-installed troubleshooting, but the information should now recommend the proper way of installing (pipx or venv + pip) with up-to-date information on the desktop integration limitations.
