### ISSUE TITLE
Shortcuts page in version 1.7.1 shows wrong keys: Shift and Ctrl are mixed

### ISSUE THREAD

**Issue by Dirk-Herrmann** [Cimbali/pympress#313]
**Problem description**
In version: 1.7.1, when showing the shortcuts page:
The navigation keys to move forward / backward to pages with different labels are shown wrong.
This happens (at least) when in a German language environment.

What _should_ be shown is, for example, "Ctrl" + right arrow.  ("Strg" + right arrow in German)
This fits the actual behavior and also the settings in the config file:
```
next-label = <ctrl>Right <ctrl>Down <ctrl>Page_Down <ctrl>space
```

What _is_ shown is "Shift" + right arrow.  ("Umschalt" + right arrow in German)

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Python version: 3.10.12
 - Pympress version: 1.7.1
 - Installation method: synaptic

The wrong shortcut key display occurs in the vanilla installed version, no changes were made by me to the config file.

**Comment by Cimbali** [comment]
I’m surprised the shortcuts are translated. In all the languages I’ve tested they appear as Ctrl / Shift (not Strg / Umschalt). Can you share a screenshot of the window?

**Comment by Cimbali** [comment]
Thanks for checking with and without translation. I think we need to look into the gtk/etc versions as this shortcut window is auto-generated from the shortcuts we use. Can you share the line from `~/.cache/pympress.log` that starts with `INFO:pympress.app:Pympress: 1.7.1`? It contains the library dependency versions.

**Comment by Cimbali** [comment]
Actually this could have been fixed in 20516ac. It’s included in v1.7.2 under “Fix display of shortcuts in shortcuts display window” – can you try updating to a more recent version?

**Comment by Dirk-Herrmann** [comment]
As requested, the line from `~/.cache/pympress.log`:
```
INFO:pympress.app:Pympress: 1.7.1 ; Python: 3.10.12 ; OS: Linux 6.5.0-10027-tuxedo #31 SMP PREEMPT_DYNAMIC Tue Mar  5 10:45:49 UTC 2024 ; Gtk 3.24.33 ; GLib 2.71.3 ; Poppler 22.02.0 cairo ; Cairo 1.16.0 , pycairo 1.20.1
```
I will also give the 1.7.2 a try and let you know if it fixed the issue.

**Comment by Dirk-Herrmann** [comment]
Sorry, seems difficult to install a newer version on my Ubuntu 22.04 jammy version without doing a full system update...  tried several things for two hours, but giving up now...

**Comment by Cimbali** [comment]
You just `pipx install pympress` or `pip install --user pympress`
