### ISSUE TITLE
Play gif via animate package does not start animation loop when displayed via Pympress

### ISSUE THREAD

**Issue by wallscheid** [Cimbali/pympress#314]
**Describe the bug**
Pympress does not play gif using "animate" package. 

**To Reproduce**
Pretty much the same problem and application scope as issue #102 - load gif as png series via the animate package and try to display it. Pympress only shows the first picture of the series, while not starting the gif loop. Loading the same beamer slide set with Adobe Acrobat works nice and directly shows the animated gif as expected. 

**Environment (please complete the following information):**
 - OS: Win11
 - Pympress version: 1.8.5
 - Installation method: Windows installer

**Debug information (see below for file locations)**
 - What is reported in pympress.log?
 - Does the problem still happen if you remove your config file?
   (You can just move the config file to a different location to be able to restore it after testing)

**Comment by Cimbali** [comment]
Hi @wallscheid, just embed the gif as an image and it’ll play out of the box. No animate package, just `\includegraphics{image.gif}`

**Comment by Cimbali** [comment]
Ah sorry it's actually embedded as a movie. `\movie` instead of `\includegraphics` should do the trick

**Comment by wallscheid** [comment]
That results basically in a blank slide, i.e., the gif is not shown at all (no error during pdflatex compilation but also no integration of the gif on the slide). Effect is independent if utilizing Pympress or any other PDF viewer. also `\movie` command integrating the .gif file in a converted .avi version does not help.

**Comment by Cimbali** [comment]
Please share your latex code using `\movie` to embed the gif directly and we can look at why that doesn't work.

**Comment by wallscheid** [comment]
The relevant code is here: https://github.com/IAS-Uni-Siegen/EMD_Course/tree/main/lecture

A specific example is in https://github.com/IAS-Uni-Siegen/EMD_Course/blob/main/lecture/tex/Lecture02.tex:
> %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Hysteresis %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}
	\frametitle{Hysteresis}
	\begin{columns}
		\begin{column}{0.575\textwidth}
            \begin{itemize}
                \item Material defects lead to small, random jumps in magnetization called Barkhausen jumps.
                \item Domain walls move there irregular and depend on the history of the magnetization process (dynamic system).
            \end{itemize}
			\begin{figure}
                \centering
                \animategraphics[loop,autoplay, height=0.3\textheight]{4}{fig/lec02/Barkhausen_jump/Barkhausen_jump}{0}{4}
                %\movie[width=0.25\linewidth]{}{fig/lec02/Moving_magnetic_domains/Moving_magnetic_domains.gif}
                \caption{Animation of the Barkhausen jump (source: \href{https://commons.wikimedia.org/wiki/File:Barkhausensprung.gif}{Wikimedia Commons},  public domain)}
            \end{figure}
		\end{column}
        \hfill
		\begin{column}{0.425\textwidth}
            \vspace{-0.2cm}
			\begin{figure}
				\centering
				\includegraphics[height=0.5\textheight]{fig/lec02/Ferromagnet_magnetization_and_magnetic_domains_and_hysteresis.pdf}
				\caption{Simplified hysteresis curve in first quadrant with magnetic domains illustration (adapted from: \href{https://commons.wikimedia.org/wiki/File:Ferromagnet_magnetization_and_magnetic_domains_and_hysteresis.svg}{Wikimedia Commons}, Fralama, \href{https://creativecommons.org/licenses/by-sa/3.0/deed.enn}{CC BY-SA 3.0})}
			\end{figure}
		\end{column}
		\end{columns}
\end{frame}

The movie command is currently commented out, but runs through without errors if actived. The result is as described: the relevant slide area remains empty and the gif is not shown at all. 

With the animate package it works at least with Acrobat, while only showing the first gif picture without running the loop in Pympress.

**Comment by Cimbali** [comment]
It seems you’re missing either a `height=…` in your `\movie` options, or something in the first `{}` of `\movie` from which an aspect ratio can be deduced. Without either of those you’re essentially embedding the gif as a 0-height video.

**Comment by Cimbali** [comment]
I would suggest extracting the first frame (or a representative frame) from your gif:

```tex
\movie{\includegraphics[height=.25\linewidth]{frame01.png}}{animation.gif}
```

That way it’s the right aspect ratio and you also have something useful for handouts/other pdf readers

**Comment by wallscheid** [comment]
@Cimbali Thanks a lot, that helped and solved my issue (or more precisely formulated: it helped me to understand my command error with the `\movie`) - gif runs on Pympress as intended now!
