### ISSUE TITLE
Triggering Shortcuts with virtually mapped buttons

### ISSUE THREAD

**Issue by Sorodon** [Cimbali/pympress#329]
**Describe the bug**
Shortcuts send by a program instead of a device don't work

**To Reproduce**
1. Map a key to execute `wtype -k -l` (this sends an l) in your compositor
3. Confirm it works in other windows (it does, types an l into a terminal perfectly)
4. Try to start the laserpointer in pympress with it (types l into the annotation search bar)
    (I also tried using `<ctrl>l` to prevent input issues, does not work either)

**Expected behavior**
I'd like to be able to trigger shortcuts by sending virtual keypresses

**Environment (please complete the following information):**
 - OS: Arch Linux
 - Python version: 3.12.7
 - Pympress version: 1.8.5
 - Installation method: `yay -S pympress` (AUR)

**Debug information (see below for file locations)**
 - What is reported in pympress.log?
    Fresh log only shows this:
    ```
    INFO:pympress.app:Pympress: 1.8.5 ; Python: 3.12.7 ; OS: Linux 6.12.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 22 Nov 2024 16:04:27 +0000 ; Gtk 3.24.43 ; GLib 2.82.2 ; Poppler 24.11.0 cairo ; Cairo 1.18.2 , pycairo 1.27.0
    WARNING:pympress.media_overlays.gst_backend:Can not create a gtksink. Check the gtk plugin for GStreamer is installed.
    WARNING:pympress.media_overlays.gst_backend:See https://github.com/Cimbali/pympress/issues/240
    INFO:pympress.extras:Media support: GdkPixbuf gif player, GStreamer not available, VLC not available
   ```
 - Does the problem still happen if you remove your config file?
    yes

**Additional context**
A solution where the laserpointer just fades when it stops moving would be fine too, since that would allow me to just leave it on.

My scenario (if it matters):
I have a cheap HP presenter with a gyro button to move the mouse. Using `wev` I found that it sends a key248 press+release before and after moving the mouse. This is probably for the proprietary HP app (available only on MS Windows) that turns the cursor into a laserpointer. This is what I remaped into sending an `l` (or `<ctrl>l`)
I realized it should be possible to hook that into the laserpointer of pympress to make it work like the *official* app.

**Comment by Cimbali** [comment]
What compositor are you using? When I try `wtype -k l` in console I get
```
Compositor does not support the virtual keyboard protocol
```

First off, you could directly change keybinds in your pympress configuration. See #255 for discussion on that. I’m not exactly sure how the key 248 translates in Gtk terms though, keys are defined [in the list of constants](https://docs.gtk.org/gdk3/index.html#constants).

Interestingly you can get pympress to go to next, previous, first, slide slide and to blank, etc. from command line but I think toggling laser pointer is a bit too niche for that. However you can still access it trough the exposed gactions, over D-Bus. I invite you to take a visualising tool like QDbusViewer with pympress open, and poke around the `io.github.pympress` service, specifically under its `org.gtk.Actions` interface.

Calling `org.gtk.Actions.List()` returns:
> `  Arguments: {"timing-report", "next-label", "pause-timer", "swap-screens", "save-file", "open-file", "goto-page", "list-recent-files", "highlight-clear", "cancel-input", "blank-screen", "presenter-fullscreen", "cancel-page-number", "next-page", "highlight", "highlight-tools-orientation", "use-gstreamer-backend", "highlight-use-pen", "edit-talk-time", "jumpto-label", "validate-input", "deck-overview", "first-page", "page", "quit", "add-annotation", "reset-timer", "next-frames", "show-shortcuts", "big-buttons", "pointer-mode", "save-file-as", "highlight-undo", "use-gif-backend", "log-level", "hist-forward", "content-fullscreen", "pick-file", "notes-pos", "prev-label", "highlight-redo", "prev-page", "start-content-fullscreen", "set-talk-time", "highlight-page-exit", "edit-layout", "pointer-color", "about", "align-content", "highlight-mode", "last-page", "start-presenter-fullscreen", "annotations", "notes-mode", "remove-annotation", "autoplay", "cancel-talk-time", "portable-config", "unzoom", "start-blanked", "close-file", "zoom", "hist-back"}`

And then for `org.gtk.Actions.Describe("pointer-mode")`
> `  Arguments: [Argument: (bgav) true, [Signature: s], [Argument: av {[Variant(QString): "manual"]}]]`
Now same request when toggling pointer on:
> `  Arguments: [Argument: (bgav) true, [Signature: s], [Argument: av {[Variant(QString): "continuous"]}]]`

Which therefore naturally :sweat_smile: translates to the following commands to switch the laser pointer on and off:
1. Set to always-on:
   `gdbus call --session --dest=io.github.pympress --object-path /io/github/pympress --method org.gtk.Actions.Activate "pointer-mode" "[<'continuous'>]" "[]"`
2. Set back to on-keypress:
   `gdbus call --session --dest=io.github.pympress --object-path /io/github/pympress --method org.gtk.Actions.Activate "pointer-mode" "[<'manual'>]" "[]"`

Or, likely more useful, a toogle command:
```
gdbus call --session --dest=io.github.pympress --object-path /io/github/pympress --method org.gtk.Actions.Activate "pointer-mode" "[<'toggle'>]" "[]"
```
(I believe this last one isn’t really introspectable from a D-Bus viewer.)

**Comment by Sorodon** [comment]
Thanks for the quick reply.
This is where it gets really weird: I'm on wayland and `wtype -k l` works perfectly fine everywhere else. Maybe it is important I'm not on a standard us-ansi keyboard?
For some reason pympress seems to make a distiction between an actual `l` typed on my keyboard and a virtual `l` sent using `wtype` with the latter only opening some text window in the lower right corner:
![image](https://github.com/user-attachments/assets/01ecc975-5295-4d36-96ab-88ce5a987261)

Since it doesnt work with neither wtype nor my presenter, I don't think it can be solved by binding to 248 directly, but I tried it anyways. 248 is apparently called `oslash`. Binding that: `pointer-mode::toggle = oslash` doesn't work either, now pympress ignores the keypress altogether.

I'm also not sure I can follow your QDbusViewer instructions. I found io.github.pympress, but under 'org.gtk' there is only something called 'Profiler' (This is all pretty new to me, sorry)

**Comment by Cimbali** [comment]
Instructions were just on how to inspect/find out the command by yourself. Just use the command I gave at the end, the one with “toggle” in it. That should toggle the pointer.

**Comment by Sorodon** [comment]
Ahh, I see it now, sorry for not reading it thoroughly. 
The command works perfectly for my use case.
It is not as comfortable as having a shortcut as it also activates if some other window has focus, but that is definitely nitpicking. Thanks a bunch!

**Comment by Sorodon** [comment]
One more question, just out of interest: What is the text box opening in the bottom right? It doesn't seem to be a searchbar and I can't get it to do anything useful.

**Comment by Cimbali** [comment]
Frankly I don’t know I don’t think I’ve seen it before. It’s some widget’s default behaviour I suppose but I’m not even sure which ones. Widgets that should transform into text boxes are the current slide and estimated talk time, and you should be able to edit the annotations, but that’s it.

**Comment by Cimbali** [comment]
You could also run the following script in python @Sorodon:
```py
#!/usr/bin/python3

import sys
import gi

gi.require_version('Gtk', '3.0')
from gi.repository import GLib, Gtk, Gdk


class MyApplication(Gtk.Application):
    def __init__(self):
        super().__init__(application_id='com.example.MyGtkApplication')
        GLib.set_application_name('My Gtk Application')

    def on_keypress(self, app, event):
        ok, val = event.get_keyval()
        print(Gdk.keyval_name(val) if ok else f'unidentified key value')

    def do_activate(self):
        window = Gtk.ApplicationWindow(application=self, title='Hello World')
        window.connect('key-press-event', self.on_keypress)
        window.present()


app = MyApplication()
exit_status = app.run(sys.argv)
sys.exit(exit_status)
```

(Just put in a file somewhere and run `python <filename>`)

Think of it as a `wev` for Gtk. If your mapping name of 248 is correct it should print `oslash` (or `ooblique`) when you have the window focused and you press your pointer’s button. If so then I’m not sure why it’s not caught by pympress (maybe it’s intercepted by your `wtype`/`gdbus` script?). If not then you have a new key to try to bind as shortcut.
