### ISSUE TITLE
Latex/Beamer link not working in presentation

### ISSUE THREAD

**Issue by Obi8** [Cimbali/pympress#33]
Hello gyus, 

i have a problem with pympress and links in my presentation.
It is difficult to click on a link,  because in the main window (picture1) it is not possible to press a link.
In the secondary window it is possible by good luck. Sometimes it works and sometimes not

![Picture1](https://user-images.githubusercontent.com/16342052/29070222-9d01c142-7c3e-11e7-95ee-db9e27163bfe.png)

![Picture2](https://user-images.githubusercontent.com/16342052/29070224-a283617a-7c3e-11e7-999c-046bea66f425.png)

**Comment by Cimbali** [comment]
Hi there, thanks for reporting the bug, I'll look into it as soon as I can (but that might take a week or 2).

In the mean time, can you send the PDF so I can look at what type of link we're talking about? Could you also give me the usual info: which OS are you running, what pympress and python versions are you using, and which way did you install pympress (binary/pip/from source/etc).

**Comment by Obi8** [comment]
Hi,

Info:
  - OS: Windows 7 x64
  - Pympress Version with vlc: https://github.com/Cimbali/pympress/releases/tag/v1.0.2

Beamer
` \documentclass{beamer}
\usepackage[english]{babel}												% neue deutsche Rechtschreibung
\usepackage[utf8]{inputenc}												% UTF-8 encoding
\usepackage{xcolor}														% Erweiterte Farben
%\usepackage{enumitem}	
\usepackage{overpic}											
\usetheme[background=light]{metropolis}           						% Use metropolis theme
\usepackage{textpos}
\usepackage{subfig}
\usepackage{caption}
\usepackage{pgfpages}
\usepackage{booktabs}
\usepackage{multirow}
\usepackage{siunitx}
\usepackage{multimedia}
%\usepackage{movie15}
\usepackage{hyperref}

\setbeameroption{show notes on second screen = right}

\begin{document}
	\begin{frame}[label=SourceFrame]{Sourceframe}
		\begin{itemize}
			\item Click \hyperlink{TargetFrame}{\beamergotobutton{}}
		\end{itemize}
	\end{frame}

	\begin{frame}[label=TargetFrame]{Targetframe}
		\hypertarget{TargetFrame}
		{
			\begin{figure}
				\centering
				\captionsetup[subfloat]{labelformat=empty}
				\subfloat[Bogen BS - DIN 18379]{\includegraphics[width=0.45\textwidth]{ExamplePicture}} \hfill
				\subfloat[]{\includegraphics[width=0.45\textwidth]{ExamplePicture}} \hfill
			\end{figure}
		}
		\hyperlink{SourceFrame}{\beamerreturnbutton{Back}}
	\end{frame}
\end{document} `


Without this line

`\setbeameroption{show notes on second screen = right}`

the links are working, but i need the second screen for my notes in the presentation. I hope it helps you to fix it and thanks for your help.

**Comment by FriedrichFroebel** [comment]
Your LaTeX code does not compile as is because it relies on local picture files (and it could be reduced to get a MWE, but this is another thing). Using `example-image-a` instead (provided by the `graphicx` package) allowed me to reproduce this issue with the latest `master`.

[issue33.pdf](https://github.com/Cimbali/pympress/files/1210665/issue33.pdf)

**Comment by Obi8** [comment]
Oh sorry, I did not know that there is a function for an example picture with the package graphics.
Thank you for tip and help. :-)
