### ISSUE TITLE
Missing package in v1.0.4 binary installer

### ISSUE THREAD

**Issue by Obi8** [Cimbali/pympress#35]
After i started pympress 1.04 i get a error:

![pympress3](https://user-images.githubusercontent.com/16342052/29160504-c80114a4-7db2-11e7-9e8c-2f22e5f15dee.png)

Befor i install pympress 1.04 i have pympress 1.02 i deinstall it with ccleaner.

OS: Windows 7 x64
Pympress: 1.04 vlc

**Comment by RonsinGitHub** [comment]
Same problem.
OS: win 10 x64 version 1703
Pympress: 1.04 vlc and novlc (both were tried)
pympress 1.02 works fine

Before I installed it, the system told me that: Windows Defender SmartScreen prevented an unrecognized app from starting. Running this app might put your PC at risk.

**Comment by Cimbali** [comment]
I might have not tested the installer enough, but I thought it worked... Well obviously it doesn't.

I'll try to have a look this week-end, in the meantime the pip distribution is up to date so if you have the dependencies installed you can get pympress that way.

**Comment by Cimbali** [comment]
Alright, I've finally had enough time to make a new attempt.

I've modified the dependency logic a little bit during for building binaries. The updated builds work on my machine (Windows 10, Python 3.4.3 and 2.7.12, cx-Freeze 4.3.4, pygobject 3.18.2), and are available at https://github.com/Cimbali/pympress/releases/tag/v1.0.4

**Comment by Obi8** [comment]
thx for youre work, now it is woking for me :-D

**Comment by Cimbali** [comment]
Yay! Thanks for your feedback @Obi8
