### ISSUE TITLE
ValueError: Namespace Gtk not available

### ISSUE THREAD

**Issue by BlueRayONE** [Cimbali/pympress#41]
I tried installing pympress for Windows 10 (64bit) according to your instructions in the readme.
When setting up PyGi (Version 3.24.1), I have not the option to tick Cairo as dependency! Poppler and Gdk-Pixbuf are available.

I'm not familiar with all the dependencies, can I install Cairo in another way directly? The website says that it's shipped with other packages.

(Always the same with windows. On my Linux-machine everything works like a charm...)

**Comment by FriedrichFroebel** [comment]
Have you tried to install PyGI without the non-existent checkbox for Cairo? I used the PyGI AIO Setup some time ago and pympress ist working without problems (I do not know anymore if there was an option for Cairo).

I just had a quick look into the files shipped with the PyGI AIO Setup (3.24.1 rev1). Inside the runtime folders (for example insideh `rtvc10-64` which is used for Python 3.3 and 3.4 (64 bit) as stated in the README file), there is a file called `libcairo-gobject-2.dll` (inside `Base/Base.bin.7z/gnome/`). Based on this it seems to be enough to keep "Base Packages" selected in the installer (this entry is checked by default) when trying to install Cairo.

**Comment by BlueRayONE** [comment]
Oh,  of course, should have mentioned this: Atm, nothing happens when I try to start the pympress.exe. So there is any problem.

Okay. The Base-Package is installed...

**Comment by FriedrichFroebel** [comment]
Pympress writes a logfile into the temporary directory of the system which is determined using https://docs.python.org/3/library/tempfile.html#tempfile.gettempdir (the directory defined by `%TEMP%` in my case for example). There you should find a file called `pympress.log` which may contain some error messages preventing the application from starting.

**Comment by BlueRayONE** [comment]
Ah, that's helpful. In C:\Windows\Temp are many .log-files, but I can't find one for pympress.
Does it matter that I'm using python2.7? I understood that it's supported.

**Comment by Cimbali** [comment]
I think `%TEMP%` under windows 10 resolves to `C:\Users\<username>\AppData\Local\Temp\pympress.log`, try seeing what that file contains. Python 2 should not be a problem indeed.

**Comment by BlueRayONE** [comment]
Unfortunately not. In this path is a temp-folder, too, but still no logfile.
is it possibile that it's not written because pympress crashes in a very early state? I double-click the exe, the progress-circle appears for 1-2 seconds, and that's it...

I've just installed pympress itself and PyGi.

**Comment by Cimbali** [comment]
I'm a little confused, do you install from source or from a binary installer? You say you click a .exe but you also report python version and installing dependencies, which is only needed to install from source. All dependencies are shipped with the binary installer.

Actually there might be a python2 bug, see e456d57. A git pull should be enough to see if that fixes it, or if you were using the binary install you might as well switch over now you have all the dependencies, and do: `python.exe -m pip install --user git+https://github.com/Cimbali/pympress#egg=pympress`

For the missing log file that is pretty strange, as it is one of the first things we set up exactly for these reasons. The easiest way to know where it is, is to start your python console and do:
```
>>> import tempfile
>>> tempfile.gettempdir()
```
and tell us what this reports.

**Comment by BlueRayONE** [comment]
Oh. I'm confused too ;)
I installed it by the binary installer. Misunderstood that, I thought the dependencies are also neccessary. Didn't read the "dependecies" in "If you don't want to know about source code or dependencies", sorry.

Ah, okay. Did that (without errors). Silly question: Where does pip install the new version? I didn't work on windows with pip yet. The original folder were I installed pympress doesn't seems to be touched.

Sounds logic, would do so, too ;)
The temp-query returns users/<user>/appdata/local/temp. But there is definitley nothing?! Very mysterious...can I provide any further information?

**Comment by Cimbali** [comment]
Well, does it work now? If you run `pympress` or `python -m pympress` ?

`python -m pip show pympress` will show you where it's installed.

**Comment by BlueRayONE** [comment]
Wasn't able to start it because path-var wasn't set. `python-m pympress` worked - and brings interesting results: 

```
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\<user>\AppData\Roaming\Python\Python27\site-packages\pympress\__main__.py", line 38, in <module>
    gi.require_version("Gtk", "3.0")
  File "C:\Python27\lib\site-packages\gi\__init__.py", line 118, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available
```
So Gtk is missing?! But I thought thats included in the binary? And it should in my case be available because I installed it with pyGi.

**Comment by Cimbali** [comment]
It should be installed by PyGi yes. Did you make sure to use the right python installation during the installation?

**Comment by BlueRayONE** [comment]
should. so not by the binary? Then your instruction needs to be updated. Just btw ;)

yes. I've got only Python2.7. In the PyGi-install I selected this version.

**Comment by Cimbali** [comment]
The binary installs the dependencies for the binary pympress, they all get installed together.
For the source version, you need the dependencies, which are installed by PyGi.

However it seems you are missing the dependency, hence "should". I'm not quite sure why though.

**Comment by Cimbali** [comment]
Alright, try to uninstall your previous binary version and install one of those I just uploaded, that include the bugfix for python 2: https://github.com/Cimbali/pympress/tree/v1.1.0.b2

**Comment by BlueRayONE** [comment]
Sorry for the next question, but how to install from another branch with pip?
Like this?
```
./python.exe -m pip install --user git+https://github.com/Cimbali/pympress/tree/v1.1.0.b2#egg=pympress
```
Then I get the error `remote not found`...

**Comment by Cimbali** [comment]
The latest tag is at the head of the master branch, soit don't need to do anything special to get it. However it must likely won't fix your dependency problems.

**Comment by BlueRayONE** [comment]
oh, didn't notice that it's matching with master-head.

you are right. same error as above. perhaps I just install python3 when I've got more time ;D

**Comment by Cimbali** [comment]
You can easily check whether the PyGi has installed correctly: run python and type
```
>>> import gi
>>> gi.require_version("Gtk", "3.0")
>>> from gi.repository import Gtk
```

This should not throw any errors. You can even go further and try creating a window:
```
>>> window = Gtk.Window(title="Hello World")
>>> window.show()
>>> window.connect("destroy", Gtk.main_quit)
>>> Gtk.main()
```

**Comment by Cimbali** [comment]
Any news @BlueRayONE ? Is it working now, or should I keep the issue open ? In which case, did you check the prerequisites were installed correctly ?

**Comment by BlueRayONE** [comment]
Currently I don't have access to my windows machine, I'll take a further
look next week.

Am 08.12.2017 00:57 schrieb "Cimbali" <notifications@github.com>:

**Comment by Bumbadawg** [comment]
In case: on KDE Neon, i had to install the following packages (to run Lutris 0.5):
sudo apt install gir1.2-gnomedesktop-3.0
sudo apt install gir1.2-webkit2-4.0
