### ISSUE TITLE
Invalid checkbox states in menu

### ISSUE THREAD

**Issue by FriedrichFroebel** [Cimbali/pympress#42]
#### Environment
- Windows 8.1
- Python 3.4 (64 bit)

#### Pympress
- version 1.0.4 from pip
- version 1.1.0.b2 from `master` (using self-built executable from cx_freeze)

#### Expected behaviour, Steps to reproduce, Problem
1. Presentation -> Pause timer
    * Open presentation by calling `python -m pympress presentation.pdf`
    * Timer is paused, checkbox in presentation menu entry is checked -> works
    * Switch to next slide, checkbox is not checked anymore as the timer started -> does not work
    * Pause timer, checkbox is checked (currently unchecked) -> does not work
2. Presentation -> Highlight
    * Call highlight mode from presentation menu entry, checkbox is checked -> works
    * Close the highlighting mode using the close button, checkbox is not checked anymore -> does not work

(The problem may appear for other checkboxes, too, which I did not check.)

**Comment by Cimbali** [comment]
Alright, so sometimes we trigger an action that could be triggered by a checkbox, without calling through the associated checkbox. As a result the checkbox state is not updated.

The easy solution is to access the checkbox in each function associated with a checkbox (pausing, highlighting, etc) and to call [Gtk.CheckMenuItem.set_active(\<correct state\>)](https://lazka.github.io/pgi-docs/#Gtk-3.0/classes/CheckMenuItem.html#Gtk.CheckMenuItem.set_active).
