### ISSUE TITLE
Control playback of video files – seek and current position

### ISSUE THREAD

**Issue by complanar** [Cimbali/pympress#45]
Would’t it be nice to be able to control the playback of a video aside of pausing and resuming?

Pdfpc implements such a feature. I have used it lately, but it has a very high cpu usage while playing videos, which does not go down once the playback is stopped – this is a problem in long presentations because it limits my battery time dramatically. 

Pympress + vlc performs much better in that way, but control over video playback is currently very limited.

I could imagine an implementation with keystrokes (as possible in vlc player) or by showing the playing video in the presenter view, too – together with a kind of progressbar that allows seeking by clicking a specific position or something like that.

I can not tell if this is possible and how much work it would be as I have never looked into python-vlc so far.

**Comment by Cimbali** [comment]
So we are talking about a pdf with embedded media, that has the options for controls enabled (for example `showcontrols=true` with the `multimedia` package). In this case we do show a control bar, that is indeed pretty basic. It has only play, pause and stop buttons.

The control bar is built in [`VLCVideo.get_player_control_toolbar()`](https://github.com/Cimbali/pympress/blob/master/pympress/vlcvideo.py#L130), so extending this with a couple other buttons and callbacks to the media should be rather easy. I just fixed the pause button which was not working.

If you want to take a shot at a PR, the [code and some examples of python-vlc](https://github.com/oaubert/python-vlc/) and the [API documentation](https://www.olivieraubert.net/vlc/python-ctypes/doc/) are available online if you need them, just add some widgets to our control bar and connect them to the right callbacks.

**Comment by complanar** [comment]
You’re right. I was aware of the showcontrols option. But I do not find a toolbar at the presentation view very usable.
Most of the time this view will be behind me, so I can not really see what’s happening. At my system vlc hides the mouse pointer from time to time (normally a good idea because it distracts the viewer of a movie), so I can not really see, where the mouse is.

I was thinking of showing the playing video at the presenter view as well (maybe one can clone the overlay to save system resources) and showing the toolbar there, where it makes more sense in my opinion.
The audience does not need to see control buttons no matter which if a showcontrols option was set or not.

This is more then extending just the toolbar. I could easily add two or more buttons, but I do not know poppler and gtk good enough, that would be a steep learning curve for me. You seem to have more background knowledge :-)
I’m coming from PHP, JavaScript and LaTeX, I had rarely to deal with GUIs.

**Comment by lucjaulmes** [comment]
Yes, I did think already about duplicating the video output but I have no idea how to do it. That's the hard part, the rest we can tweak easily.

Let me see what I can do.

**Comment by Cimbali** [comment]
Yes, I did think already about duplicating the video output but I have no idea how to do it. That's the hard part, the rest we can tweak easily.

Let me see what I can do.
