### ISSUE TITLE
Resolve shared files from local folder if possible

### ISSUE THREAD

**Issue by FriedrichFroebel** [Cimbali/pympress#47]
### Environment
- Ubuntu 16.04
- Python 3.5

### Pympress
- latest master in local folder
- current release installed via pip

### Expected behaviour 
Starting `pympress` in local master clone using `python3 -m pympress` from within a folder should use the shared files from the `share/` directory of the current folder and not throw any errors.

### Steps to reproduce
- Install `pympress` using pip3.
- Clone the latest master into a local directory.
- Run `python3 -m pympress` inside the cloned directory.

### Problem
The shared files from the pip install are used and an error message may be produced, see https://github.com/Cimbali/pympress/commit/0bdc5da56b90ff6a8388f3bf007d2eac160a2e0e#commitcomment-26206898 and https://github.com/Cimbali/pympress/commit/0bdc5da56b90ff6a8388f3bf007d2eac160a2e0e#commitcomment-26212807.

**Comment by Cimbali** [comment]
It's hard to figure out whether the code that is running is the installed pympress or a different one. Plus the file resolution is done automatically by `pkg_resources` and I'm not sure we should stray from the way all other python packages work. 

One solution could be to use the current master in your system by going to the folder and doing `pip install [--user] -e .` Now files will be resolved from the local folder.

**Comment by FriedrichFroebel** [comment]
If I use `getattr(sys, 'frozen', True)`, this does not work as `sys.executable` maps to `/usr/bin/python3` in this case.

A quick test did not throw any errors when adding an `elif` inside the `__get_resource_path` method (I did not test whether this would have an effect on pip installations):

```python
if getattr(sys, 'frozen', False):
    return os.path.join(os.path.dirname(sys.executable), *path_parts)
elif os.path.exists(os.path.join(os.path.dirname(__file__), *path_parts)):
    return os.path.join(os.path.dirname(__file__), *path_parts)
else:
    req = pkg_resources.Requirement.parse('pympress')
    return pkg_resources.resource_filename(req, os.path.join('pympress', *path_parts))
```

**Comment by Cimbali** [comment]
Alright I was looking whether it's worth integrating this, but I'd think it would be too confusing. `python -m pympress` already loads local files if you have no version installed with pip. If you have both a local version and one installed, then `python -m pympress` would now mean different things based on your current path.

If you really need both, I suggest you use a [virtualenv](https://virtualenv.pypa.io/en/stable/userguide/#using-virtualenv-without-bin-python) for the "local" version, that you can install inside the virtualenv in editable mode `pip install -e /path/to/local/dir`. Just remember to create the virtual env with `--system-site-packages` so you inherit the pygobject dependencies:

    > virtualenv --system-site-packages venv
     Using base prefix '/usr'
     New python executable in /path/to/venv/bin/python3
     Also creating executable in /path/to/venv/bin/python
     Installing setuptools, pip, wheel...done.
    > source /path/to/venv/bin/activate
    (venv) > pip install -e /path/to/local/dir
     Obtaining file:///path/to/local/dir
     Requirement already satisfied: python-vlc in $HOME/.local/lib/python3.6/site-packages (from pympress==1.1.0)
     Installing collected packages: pympress
       Found existing installation: pympress 1.1.0
         Not uninstalling pympress at $HOME/.local/lib/python3.6/site-packages, outside environment /path/to/venv
       Running setup.py develop for pympress
     Successfully installed pympress
    (venv) > python -m pympress
