### ISSUE TITLE
Video/audio playback tinny (because of the doubled video output?)

### ISSUE THREAD

**Issue by complanar** [Cimbali/pympress#52]
# Environment
- Linux Mint 18.3
- Python version 3.5

# Pympress
- 1.1
- Installation method: source

# Expected behaviour 
When playing videos the sound should be heard clearly.

# Steps to reproduce
1. Open a pdf file with embedded video.
2. Show a slide with video and start playback. 
3. Listen closely :) 
4. Examine the system’s audio output streams (e.g. with pavucontrol) – you should see the audio track of the video twice.

# Problem
Sometimes the audio track of videos sounds quite tinny. Probably this is because of the doubled video on the presenter and the presentation view. That way the audio output is doubled, too.
When disabling/muting one of the two output streams (e.g. with pavucontrol) the sound is clear again.

I think it is a good idea to disable the audio tracks of one of the two player instances. 
Sadly, libvlc doesn’t seem to be quit straight forward there. I could not manage it this morning, not even with reading the docs.
Looks like you’ve got to grab the audio track of one of the player’s media, "free" it somehow and then mute or disable it. Didn’t get it right.

**Comment by Cimbali** [comment]
Hmmmm I must say I didn't expect to play sound from pympress. But if it's already possible, we should definitely support it and do it the right way. I'll have a look at this.

I think `self.player.audio_set_mute(True)` is a good starting point, but I have to get my hands on an example pdf first.

**Comment by Cimbali** [comment]
Turns out set_mute is shared among players but set_volume is not.
