### ISSUE TITLE
Question about window size

### ISSUE THREAD

**Issue by susobaco** [Cimbali/pympress#54]
Hi, congratulations on your show. I have a question. In a dual monitor presentation, it is possible to start the fulscreen presentation, but it is possible that the other window, the control window, will not start full screen? I'd like a small window. I've tried it with the openbox configuration, but the output of "xprop | grep class" is the same for both windows, so I can't define the size for a single window.
I am using the latest version of pympres on lxde in Tisquel 8 (ubuntu 16.04). Thank you for your work.

**Comment by Cimbali** [comment]
HI @susobaco you should look at the "Startup configuration" menu and tick "Content fullscreen" and untick "Presenter fullscreen". The presenter (or control as you say) window will probably still start maximized but not fullscreen.

Also I don't know much about openbox configurations, byt from what I see in xprop:
- the presenter window allows the maximized actions but the content window doesn't, so you could try applying it to both and seeing what happens.
- the windows have the same class but different names "pympress presenter" and "pympress content" so maybe you could filter by that.

**Comment by susobaco** [comment]
Hello, the result is the same following your instructions. 
The xprop outputs:
``_OB_APP_TYPE(UTF8_STRING) = "normal"
_OB_APP_TITLE(UTF8_STRING) = "pympress presenter"
_OB_APP_GROUP_CLASS(UTF8_STRING) = 
_OB_APP_GROUP_NAME(UTF8_STRING) = "pympress"
_OB_APP_CLASS(UTF8_STRING) = "Pympress"
_OB_APP_NAME(UTF8_STRING) = "pympress"
_OB_APP_ROLE(UTF8_STRING) = 
_NET_WM_VISIBLE_ICON_NAME(UTF8_STRING) = "pympress presenter"
_NET_WM_VISIBLE_NAME(UTF8_STRING) = "pympress `presenter"`

`` _OB_APP_TYPE(UTF8_STRING) = "normal"
_OB_APP_TITLE(UTF8_STRING) = "Pympress Content"
_OB_APP_GROUP_CLASS(UTF8_STRING) = 
_OB_APP_GROUP_NAME(UTF8_STRING) = "pympress"
_OB_APP_CLASS(UTF8_STRING) = "Pympress"
_OB_APP_NAME(UTF8_STRING) = "pympress"
_OB_APP_ROLE(UTF8_STRING) = 
_NET_WM_VISIBLE_ICON_NAME(UTF8_STRING) = "Pympress Content"
_NET_WM_VISIBLE_NAME(UTF8_STRING) = "Pympress Content"
`` 

 The name is different, but in order for the openbox configuration to work, the "class" or "role" must be different.

**Comment by Cimbali** [comment]
There you go, now the windows have different roles.
