### ISSUE TITLE
Crash at startup on OSX "Failed to load shared library"

### ISSUE THREAD

**Issue by Hazza4569** [Cimbali/pympress#58]
I am running OSX 10.13.3 with Python version 2.7. I installed pympress via pip yesterday (not sure what version it is, I assume the latest).

# Expected behaviour 
What are you trying to achieve? What's the expected outcome?
It took me a while to install the relevant dependencies and I had to create symbolic links for gi and cairo in the pympress install location, but I now have it operational such that the program will open without errors (to an extent).

My issue now is that when I try and open the program with a pdf file, or when I try to open a pdf after having already started the program, I get a pop-up messagebox simply saying

```
Error opening the file "/path/presentation.pdf"
```

I'm simply typing
`pympress /path/presentation.pdf`
in the terminal, and get output

```
(pympress:25174): Gtk-WARNING **: 10:22:21.204: Allocating size to GtkPaned 0x7fe54d0eff00 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

** (pympress:25174): WARNING **: 10:22:21.214: Failed to load shared library '@rpath/libpoppler-glib.8.dylib' referenced by the typelib: dlopen(@rpath/libpoppler-glib.8.dylib, 9): image not found

** (pympress:25174): WARNING **: 10:22:21.293: Failed to load shared library 'libcairo-gobject.2.dylib' referenced by the typelib: dlopen(libcairo-gobject.2.dylib, 9): image not found
```

The log file at /tmp/pympress.log is empty.

Any ideas on how to fix this issue?

**Comment by Cimbali** [comment]
It seems you have some dependencies missing. I don't have OSX myself so let's try to figure this one out. If you have [Homebrew](https://brew.sh/), run the following:

    brew install gtk+3 poppler gobject-introspection

If that works, I'll add it to the documentation.

**Comment by Hazza4569** [comment]
I ran the command and all three came back as already installed.

**Comment by Cimbali** [comment]
Can you try to run `brew update` followed by `brew doctor` and post your output here, to check for missing dependencies or similar problems?

**Comment by Hazza4569** [comment]
`> brew update
 Already up-to-date.
 > brew doctor
 Your system is ready to brew.`

**Comment by Cimbali** [comment]
Let's try listing `dylib`s referenced in gobject introspections:

     strings $(brew --prefix)/lib/girepository-1.0/*.typelib | grep dylib

**Comment by Hazza4569** [comment]
That gives the output
```bash
/usr/local/Cellar/atk/2.28.1/lib/libatk-1.0.0.dylib
/usr/local/Cellar/gobject-introspection/1.56.0/lib/libgirepository-1.0.1.dylib
/usr/local/opt/glib/lib/libglib-2.0.0.dylib,/usr/local/opt/glib/lib/libgobject-2.0.0.dylib
/usr/local/opt/glib/lib/libgmodule-2.0.0.dylib
/usr/local/opt/glib/lib/libgobject-2.0.0.dylib
/usr/local/Cellar/gtk+/2.24.32_1/lib/libgdk-quartz-2.0.0.dylib
/usr/local/Cellar/gtk+3/3.22.29/lib/libgdk-3.0.dylib
/usr/local/Cellar/gdk-pixbuf/2.36.11/lib/libgdk_pixbuf-2.0.0.dylib
/usr/local/opt/glib/lib/libgio-2.0.0.dylib
/usr/local/Cellar/gtk+/2.24.32_1/lib/libgtk-quartz-2.0.0.dylib
/usr/local/Cellar/gtk+3/3.22.29/lib/libgtk-3.0.dylib,/usr/local/Cellar/gtk+3/3.22.29/lib/libgdk-3.0.dylib
/usr/local/Cellar/harfbuzz/1.7.6/lib/libharfbuzz.0.dylib,/usr/local/Cellar/harfbuzz/1.7.6/lib/libharfbuzz-gobject.0.dylib
/usr/local/Cellar/pango/1.42.0/lib/libpango-1.0.0.dylib
/usr/local/Cellar/pango/1.42.0/lib/libpango-1.0.0.dylib,/usr/local/Cellar/pango/1.42.0/lib/libpangocairo-1.0.0.dylib,/usr/local/Cellar/pango/1.42.0/lib/libpango-1.0.0.dylib,/usr/local/Cellar/pango/1.42.0/lib/libpangoft2-1.0.0.dylib
/usr/local/Cellar/pango/1.42.0/lib/libpango-1.0.0.dylib,/usr/local/Cellar/pango/1.42.0/lib/libpangoft2-1.0.0.dylib
@rpath/libpoppler-glib.8.dylib
libcairo-gobject.2.dylib
```

**Comment by Cimbali** [comment]
OK so the two last ones seem to not have full paths, maybe the system can't find them. Can you find where they are installed (e.g. with `locate`) and add their directories to `DYLD_FALLBACK_LIBRARY_PATH` (`/path/for/libpoppler:/path/for/libcairo`)? If that doesn't work, fix it, can you try with `DYLD_LIBRARY_PATH`?

**Comment by Hazza4569** [comment]
I have found the libraries (they're both in `/usr/local/lib`), but not sure how to add the directory to the path. I tried `echo $DYD_FALLBACK_LIBRARY_PATH` and it came back blank, same for the other path.

Doing `export DYLD_FALLBACK_LIBRARY_PATH=$DYLD_FALLBACK_LIBRARY_PATH:/usr/local/lib` didn't affect the result of the strings command.

**Comment by Cimbali** [comment]
If it's blank you don't need the `:`

Does `export DYLD_FALLBACK_LIBRARY_PATH=/usr/local/lib; pympress` work ?

**Comment by Hazza4569** [comment]
Still the same error unfortunately

**Comment by Cimbali** [comment]
Can you run the following in python, to see which return a correct CDLL object and which can't find the library?

    import ctypes, os
    ctypes.CDLL('libpoppler-glib.8.dylib')
    ctypes.CDLL('libcairo-gobject.2.dylib')

    ctypes.CDLL('/usr/local/lib/libpoppler-glib.8.dylib')
    ctypes.CDLL('/usr/local/lib/libcairo-gobject.2.dylib')

    os.environ['DYLD_FALLBACK_LIBRARY_PATH']='/usr/local/lib'
    ctypes.CDLL('libpoppler-glib.8.dylib')
    ctypes.CDLL('libcairo-gobject.2.dylib')
    del os.environ['DYLD_FALLBACK_LIBRARY_PATH']

    os.environ['DYLD_LIBRARY_PATH']='/usr/local/lib'
    ctypes.CDLL('libpoppler-glib.8.dylib')
    ctypes.CDLL('libcairo-gobject.2.dylib')

**Comment by Cimbali** [comment]
This is probably a packaging error in gobject btw, since many similar errors appear for ruby, julia, or other programming languages that use similar bindings. Probably a workaround will be to symlink the libraries to a location where they can be found.

**Comment by Cimbali** [comment]
@Hazza4569 Can you run pygobject's hello world (as described in [this other issue](https://github.com/Cimbali/pympress/issues/63#issuecomment-378692140))?

**Comment by Hazza4569** [comment]
Just as there, the window loads as expected.

The output from the CDLL code is
```python
>>> import ctypes, os
>>> ctypes.CDLL('libpoppler-glib.8.dylib')
<CDLL 'libpoppler-glib.8.dylib', handle 7ffc02c06df0 at 1019b4bd0>
>>> ctypes.CDLL('libcairo-gobject.2.dylib')
<CDLL 'libcairo-gobject.2.dylib', handle 7ffc02c0ee80 at 1019b4cd0>
>>> 
>>> ctypes.CDLL('/usr/local/lib/libpoppler-glib.8.dylib')
<CDLL '/usr/local/lib/libpoppler-glib.8.dylib', handle 7ffc02c06df0 at 1019b4bd0>
>>> ctypes.CDLL('/usr/local/lib/libcairo-gobject.2.dylib')
<CDLL '/usr/local/lib/libcairo-gobject.2.dylib', handle 7ffc02c0ee80 at 1019b4cd0>
>>> 
>>> os.environ['DYLD_FALLBACK_LIBRARY_PATH']='/usr/local/lib'
>>> ctypes.CDLL('libpoppler-glib.8.dylib')
<CDLL 'libpoppler-glib.8.dylib', handle 7ffc02c06df0 at 1019b4890>
>>> ctypes.CDLL('libcairo-gobject.2.dylib')
<CDLL 'libcairo-gobject.2.dylib', handle 7ffc02c0ee80 at 101a07550>
>>> del os.environ['DYLD_FALLBACK_LIBRARY_PATH']
>>> 
>>> os.environ['DYLD_LIBRARY_PATH']='/usr/local/lib'
>>> ctypes.CDLL('libpoppler-glib.8.dylib')
<CDLL 'libpoppler-glib.8.dylib', handle 7ffc02c06df0 at 1019b4bd0>
>>> ctypes.CDLL('libcairo-gobject.2.dylib')
```

**Comment by Hazza4569** [comment]
Also, I tried symlinking the libpoppler and libcairo dylib files to `/usr/local/opt/glib/lib/` (one of the directories mentioned in the output from the strings command), however this didn't affect the output of the strings command when re-running it, and the same error still occurs in pympress.

For reference, the commands run to establish the links were
```bash
[]$ ln -s /usr/local/lib/libpoppler-glib.8.dylib /usr/local/opt/glib/lib
[]$ ln -s /usr/local/lib/libcairo-gobject.2.dylib /usr/local/opt/glib/lib
```

and the directory now looks like
```bash
[] $ ls -l /usr/local/opt/glib/lib
total 7340
drwxr-xr-x  3 harry admin      96 Mar 12 20:59 glib-2.0
lrwxr-xr-x  1 harry admin      39 Apr  4 20:51 libcairo-gobject.2.dylib -> /usr/local/lib/libcairo-gobject.2.dylib
-r--r--r--  1 harry admin 1503604 Mar 14 09:28 libgio-2.0.0.dylib
-r--r--r--  1 harry admin 2823488 Mar 12 20:59 libgio-2.0.a
lrwxr-xr-x  1 harry admin      18 Mar 12 20:59 libgio-2.0.dylib -> libgio-2.0.0.dylib
-r--r--r--  1 harry admin  977628 Mar 14 09:28 libglib-2.0.0.dylib
-r--r--r--  1 harry admin 1425800 Mar 12 20:59 libglib-2.0.a
lrwxr-xr-x  1 harry admin      19 Mar 12 20:59 libglib-2.0.dylib -> libglib-2.0.0.dylib
-r--r--r--  1 harry admin   27296 Mar 14 09:28 libgmodule-2.0.0.dylib
-r--r--r--  1 harry admin    9288 Mar 12 20:59 libgmodule-2.0.a
lrwxr-xr-x  1 harry admin      22 Mar 12 20:59 libgmodule-2.0.dylib -> libgmodule-2.0.0.dylib
-r--r--r--  1 harry admin  275936 Mar 14 09:28 libgobject-2.0.0.dylib
-r--r--r--  1 harry admin  422168 Mar 12 20:59 libgobject-2.0.a
lrwxr-xr-x  1 harry admin      22 Mar 12 20:59 libgobject-2.0.dylib -> libgobject-2.0.0.dylib
-r--r--r--  1 harry admin   20840 Mar 14 09:28 libgthread-2.0.0.dylib
-r--r--r--  1 harry admin    1544 Mar 12 20:59 libgthread-2.0.a
lrwxr-xr-x  1 harry admin      22 Mar 12 20:59 libgthread-2.0.dylib -> libgthread-2.0.0.dylib
lrwxr-xr-x  1 harry admin      38 Apr  4 20:51 libpoppler-glib.8.dylib -> /usr/local/lib/libpoppler-glib.8.dylib
drwxr-xr-x 10 harry admin     320 Mar 14 09:28 pkgconfig
```

**Comment by Cimbali** [comment]
Thanks a lot @RJVB ! Should this be applied upstream at [GNOME/gobject-introspection](https://github.com/GNOME/gobject-introspection) maybe?

**Comment by RJVB** [comment]
I suppose so, but in a form which integrates completely with the autoconf scripts.

**Comment by Cimbali** [comment]
I’ve been able to play with a Sierra and a Mojave macOS virtual machines but can not seem to reproduce this. Does the bug appear to be fixed? If not, does running just `pympress --help` trigger the bug?

**Comment by Cimbali** [comment]
Does this still happen @Hazza4569 @ekrimsk ?

I have found some other information about this issue on https://gitlab.freedesktop.org/poppler/poppler/issues/18 where it seems to be fixable with compile-time CMAKE options.

There also seems to be code that replaces the `@rpath` part in the library directly in the homebrew formula:
https://github.com/Homebrew/homebrew-core/blob/4e69530a44199e7e569d776acb31244317cc2d43/Formula/poppler.rb#L62-L72
