### ISSUE TITLE
Enable blank screen with dot

### ISSUE THREAD

**Issue by FriedrichFroebel** [Cimbali/pympress#6]
It would be great to get a blank screen when pressing the dot, too. This seems to be the key event which is send by Logitech presenters.

**Comment by Cimbali** [comment]
Sounds like a good idea, thanks! Should be simple enough.
After a quick bit of research, I think the shortcut will need to be reassignable. It's apparently a keycode that's sent directly, not a character, which may cause some [conflicts on different keyboard layouts](https://community.logitech.com/s/feed/0D53100005NbgQCCAZ).

**Comment by Cimbali** [comment]
@FriedrichFroebel can you check out the [logitech_blanking](https://github.com/Cimbali/pympress/tree/logitech_blanking) branch, tell me if it works for you?

**Comment by FriedrichFroebel** [comment]
I tried to install it from source (using latest Python3 version), but could not get it to work on Windows (I previously installed it using the given installer and now uninstalled it). Running `setup.py install` returns a message about the successful installation, but calling `pympress` with or without an argument from command line only results in a short loading without any other output. (Same result when using the master branch this way.)

**Comment by Cimbali** [comment]
I'm afraid you

 probably need [some prerequisites](https://github.com/Cimbali/pympress#dependencies) from source. If you copy the DLLs from your previous install it should work. To get error messages you should try `python -m pympress` instead of just `pympress` from the command line.

Alternately I can build you a distributable package but I'm not sure the hardware keycode I used is universally correct (it seems to be on my laptop), so it's easier if you have the source and can play with it a little.

**Comment by FriedrichFroebel** [comment]
Ok, just used the PyGi installer for Gtk+3, but `python -m pympress` keeps saying `ImportError: No module named 'gi'`. Seems to a problem with Python 3.5 (https://sourceforge.net/p/pygobjectwin32/tickets/32/) and seems like there was another request about this not long ago (https://sourceforge.net/p/pygobjectwin32/tickets/50/).

I will have a look at this with an Linux system as soon as possible.

**Comment by Cimbali** [comment]
Yeah, no python3.5 support. The installer ships with the 3.4 dll.

**Comment by FriedrichFroebel** [comment]
Just tried to set it up using Linux Mint with both Python 2.7.12 and Python 3.5.2 without having success. When running `python -m pympress` (or the python3 equivalent), I get `ValueError: Namespace Poppler not available` which is raised by `"/usr/lib/python/dist-packages/gi/__init__.py"`.

I installed some poppler packages for Mint (if they have not already been installed), but this has not changed anything concerning getting pympress to work as expected: `Python-poppler`, `Python-poppler-dbg`, `Libpoppler-glib8`, `Libpoppler-qt5-1`, `Python3-poppler-qt5`.

**Comment by Cimbali** [comment]
pympress doesn't use directly poppler bindings, but uses the GObject introspection to access the library instead. On ubuntu, there is a package called `gir1.2-poppler-0.18` for that (`typelib-1_0-Poppler-0_18` on OpenSUSE but I suspect the ubuntu naming must be closer). That is probably the package that you are missing.

The package that proves the introspection (`python3-gi` on ubuntu) already depends on the similarly named `gir1.2-glib-2.0` which is the introspection data for GLib.

I'll try to add a one-liner setup command for ubuntu and similar on the README at some point.

**Comment by FriedrichFroebel** [comment]
Ok, could get it to run now using the gir... package. Using the presenter for blanking did not work. I added a `print` statement as first statement inside the `on_navigation` method - only the `prev` and `next` button produced some output, the other buttons did not (blanking, start presentation).

**Comment by Cimbali** [comment]
Alright, can you check what `xev` gives you as output for the buttons of the logitech presenter? If there's no output there's probably not much we can do about it application side.

If this is the case, you might be able to remap the keycodes (obtained with showkey) to some that are supported (below 255). This is all assuming you are in the scenario [described by this thread](https://bbs.archlinux.org/viewtopic.php?id=174772).

**Comment by FriedrichFroebel** [comment]
`xev` produces no output for the blanking key. `showkey` gives me the same keys as in your thread, but remapping is too much overkill for me at the moment.

**Comment by Cimbali** [comment]
Well I'm afraid we can't catch these buttons without remapping. If you remap them, you might as well do so to the current shortcut for blanking, namely 'b'.
