### ISSUE TITLE
vlc always opens new window, rather than embedding

### ISSUE THREAD

**Issue by jpezaris** [Cimbali/pympress#60]
# Environment
- Fedora 26, KDE spin
- Python 3.6.4
- (beamer / pdflatex)

# Pympress
- version 1.1.2
- Installation method:  python3 -m pip install git+https://github.com/Cimbali/pympress#egg=pympress

# Expected behaviour 
Video playback should appear seamlessly above the still image that acts as a placeholder, without any window decorations; the user should not be aware that a separate program has been invoked to perform the video playback.

# Steps to reproduce
Create PDF in beamer / pdflatex that includes .mp4 video. 
Start pympress on PDF and advance to page that has embedded video.
Click on placeholder for embedded video.

# Problem
Instead of embedding properly, VLC opens a new window to play the video.  The video plays correctly, except that it is not embedded and not at the size expected from the size of the placeholder.

The log file pympress.log is empty.

**Comment by Cimbali** [comment]
Hi @jpezaris, can you provide also your vlc version?

**Comment by jpezaris** [comment]
VLC media player 3.0.1 Vetinari (revision 3.0.1-0-gec0f700fcc)

On 3/16/18, Cimbali <notifications@github.com> wrote:
> Hi @jpezaris, can you provide also your vlc version?
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/Cimbali/pympress/issues/60#issuecomment-373861724


-- 
John Pezaris, Ph.D.
jpezaris@gmail.com

**Comment by Cimbali** [comment]
Alright well there should be some error message somewhere. Maybe we don't manage to catch it because it's outside of python (e.g. VLC or Gtk).
Can you run pympress from a console in the following way, and tell me if there's anything error messages that are printed?

    python3 -m pympress <file.pdf>

**Comment by jpezaris** [comment]
This is the only message:

(__main__.py:11842): Gtk-WARNING **: Allocating size to GtkPaned
0x562958d74f20 without calling
gtk_widget_get_preferred_width/height(). How does the code know the
size to allocate?



On 3/18/18, Cimbali <notifications@github.com> wrote:
> Alright well there should be some error message somewhere. Maybe we don't
> manage to catch it because it's outside of python (e.g. VLC or Gtk).
> Can you run pympress from a console in the following way, and tell me if
> there's anything error messages that are printed?
>
>     python3 -m pympress <file.pdf>
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/Cimbali/pympress/issues/60#issuecomment-373992995


-- 
John Pezaris, Ph.D.
jpezaris@gmail.com

**Comment by Cimbali** [comment]
Even when opening the VLC file?

**Comment by jpezaris** [comment]
I had not looked, and you are right: it happens at startup, and not
when the movie is clicked.

Perhaps this is an important clue: I have found that by changing the
File Associations for MP4 files in System Settings, I can switch
whether VLC or another program (e.g., mplayer) gets called when the
movie pane is clicked within pympress.

On 3/18/18, Cimbali <notifications@github.com> wrote:
> Even when opening the VLC file?
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/Cimbali/pympress/issues/60#issuecomment-373994038


-- 
John Pezaris, Ph.D.
jpezaris@gmail.com

**Comment by Cimbali** [comment]
So no messages at all when the movie is clicked? Also what beamer package do you use to include the video? Could you share the sources of a minimal compilable latex file here?

**Comment by complanar** [comment]
Sounds like you use the `external` option of the media package in your `.tex` file

**Comment by jpezaris** [comment]
\documentclass{beamer}
\begin{document}
\begin{frame}
  \href{run:test.mp4}{\includegraphics[height=0.2\textwidth]{test.jpg}}
\end{frame}
\end{document}

... the files test.jpg, test.mp4, and test.pdf are available from

http://pezlab.org/test.jpg
http://pezlab.org/test.mp4
http://pezlab.org/test.pdf

The beamer version is

Document Class: beamer 2015/01/05 3.36 A class for typesetting
presentations (rcs-revision 8a39122e1f63)



On 3/18/18, Holger Teichert <notifications@github.com> wrote:
> Sounds like you use the `external` option of the media package in your
> `.tex` file
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/Cimbali/pympress/issues/60#issuecomment-373999526


-- 
John Pezaris, Ph.D.
jpezaris@gmail.com

**Comment by Cimbali** [comment]
Alright that seems to be a link to open the file in its default program, which we do correctly.

Try this:

```
\documentclass[10pt]{beamer}
\usetheme{Warsaw}
\usepackage{multimedia}

\begin{document}
   \begin{frame}[plain]
      \movie[height=.2\textwidth]{\includegraphics[height=.2\textwidth]{test.jpg}}{test.mp4}%
   \end{frame}
\end{document}
```

**Comment by jpezaris** [comment]
Awesome, thanks!

Now the video in the minimal example works correctly.   The call to
\usetheme{Warsaw} is not necessary, I've found.

However, when you expand the minimal example as follows:

\documentclass[aspectratio=169,20pt]{beamer}
\usepackage{multimedia}
  \usepackage{pgfpages}
  \setbeameroption{show notes}
  \setbeameroption{show notes on second screen=right}
\begin{document}
\begin{frame}
  \movie{\includegraphics[width=0.8\textwidth]{test.jpg}}{test.mp4}
\end{frame}
\end{document}

The resulting movie plays, but has the wrong size and position,
compared to the frame grab, which remains correct.  The problem
remains the same whether the width is specified in absolute size
(e.g., "width=4in") or as a fraction of \textwidth.


On 3/18/18, Cimbali <notifications@github.com> wrote:
> Alright that seems to be a link to open the file in its default program,
> which we do correctly.
>
> Try this:
>
> ```
> \documentclass[10pt]{beamer}
> \usetheme{Warsaw}
> \usepackage{multimedia}
>
> \begin{document}
>    \begin{frame}[plain]
>
> \movie[height=.2\textwidth]{\includegraphics[height=.2\textwidth]{test.jpg}}{test.mp4}%
>    \end{frame}
> \end{document}
> ```
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/Cimbali/pympress/issues/60#issuecomment-374010933


-- 
John Pezaris, Ph.D.
jpezaris@gmail.com

**Comment by Cimbali** [comment]
Alright, that's a different issue. Only with notes on second screen it appears.

**Comment by gbaier** [comment]
Sorry for hijacking this issue. I had the same problem using fedora 28. Though the minmal working example did not work for me. The problem was that fedora uses Wayland instead of X11. The solution was simply to launch pympress the following way:
```
GDK_BACKEND=x11 pympress test.pdf
```

**Comment by leon-erd** [comment]
@gbaier Thank you so much! That was exactly my problem running pympress under xwayland fixed it for me as well!
Is there any chance to make the internal video player also work on wayland? :)
Great project tho
