### ISSUE TITLE
Embedded video appears at wrong location and too small when notes on second page enabled.

### ISSUE THREAD

**Issue by jpezaris** [Cimbali/pympress#61]
# Environment
- Fedora 26, KDE
- Python 3.6.4

# Pympress
- version 1.1.2
- Installation method: pip

# Expected behaviour 
Embeded video when clicked should play seamlessly over frame grab, matching position and size.

# Steps to reproduce
Minimum working example:

\documentclass{beamer}
\usepackage{multimedia}
\usepackage{pgfpages}
\setbeameroption{show notes}
\setbeameroption{show notes on second screen=right}
\begin{document}
\begin{frame}
  \movie{\includegraphics[width=0.8\textwidth]{test.jpg}}{test.mp4}
\end{frame}
\end{document}

# Problem
Video appears with wrong size (too small, perhaps 1/2 of expected width) and in slightly wrong location (too far left by about 1/2).  If notes on second page not used, works correctly.

/tmp/pympress.log is empty

**Comment by Cimbali** [comment]
Can reproduce. Working on it.

**Comment by Cimbali** [comment]
@jpezaris You should install from github to see these changes, try:

    pip install --upgrade --force-reinstall git+git://github.com/Cimbali/pympress@master

**Comment by jpezaris** [comment]
Verified!

Many thanks for your assistance and quick response.

On 3/19/18, Cimbali <notifications@github.com> wrote:
> @jpezaris You should install from github to see these changes, try:
>
>     pip install --upgrade --force-reinstall
> git+git://github.com/Cimbali/pympress@master
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/Cimbali/pympress/issues/61#issuecomment-374307482


-- 
John Pezaris, Ph.D.
jpezaris@gmail.com
