### ISSUE TITLE
Not loading library libpoppler-glib after osx 10.13.4 update 

### ISSUE THREAD

**Issue by ekrimsk** [Cimbali/pympress#63]
# Environment
- OSX 10.13.4
- Python 3.6

# Pympress
- version 1.1.2
- Installed with pip

# Expected behaviour 
Open a simple PDF (text only)

# Steps to reproduce
Open a simple PDF (text only)

# Problem
Upon starting pympress I get the error message

```
Error Opening the file "myfile.pdf"
```

Error log in Terminal:
```
** (pympress:17238): WARNING **: 02:52:29.653: Failed to load shared library '@rpath/libpoppler-glib.8.dylib' referenced by the typelib: dlopen(@rpath/libpoppler-glib.8.dylib, 9): image not found`
```

However the file is present at /usr/local/lib/libpoppler-glib.8.dylib 
This issue ONLY started to occur today (4/4/18) after updating from OSX 10.13.3 to 10.13.4.

**Comment by Cimbali** [comment]
Seems to be the same issue as #58

**Comment by Cimbali** [comment]
Alright so you have all the dependencies because it worked before. Can you try the following in your terminal:

    DYLD_FALLBACK_LIBRARY_PATH=/usr/local/lib pympress

And if that doesn't work:

    DYLD_LIBRARY_PATH=/usr/local/lib pympress

**Comment by ekrimsk** [comment]
Trying 
`DYLD_FALLBACK_LIBRARY_PATH=/usr/local/lib pympress`
produces the same issue as before (can't load files)

Trying 
`DYLD_LIBRARY_PATH=/usr/local/lib pympress`
produces 
`Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/site-packages/pympress/__main__.py", line 39, in <module>
    from pympress import util
  File "/usr/local/lib/python3.6/site-packages/pympress/util.py", line 33, in <module>
    import gi
  File "/usr/local/lib/python3.6/site-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: dlopen(/usr/local/lib/python3.6/site-packages/gi/_gi.cpython-36m-darwin.so, 2): Symbol not found: __cg_jpeg_resync_to_restart
  Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
  Expected in: /usr/local/lib/libJPEG.dylib
 in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO`

Calling pympress directly from terminal couldn't find the file so I've been using the following alias: 
`alias pympress='python3 /usr/local/lib/python3.6/site-packages/pympress' `
which may be related to the issue

**Comment by Cimbali** [comment]
I don't think your alias is causing the issue (though I would use `python3 -m pympress`).

Basically the FALLBACK doesn't allow to find libpoppler, and modifying the library path causes loading other libraries to fail.

**Comment by Cimbali** [comment]
Alright, can you try to run [pygobject's hello world](https://pygobject.readthedocs.io/en/latest/)? Basically put the following code in a file `hello.py` and then run `python3 hello.py`:

    import gi
    gi.require_version("Gtk", "3.0")
    from gi.repository import Gtk
    
    window = Gtk.Window(title="Hello World")
    window.show()
    window.connect("destroy", Gtk.main_quit)
    Gtk.main()

If this fails, instead of opening an empty window with title "Hello World", the issue needs to be reported [at pygobject](https://gitlab.gnome.org/GNOME/pygobject/issues).

**Comment by ekrimsk** [comment]
Running the hello.py script successfully opens a new window title "Hello World"

**Comment by ekrimsk** [comment]
CDLL commands from #58 
`
>>> import ctypes, os
>>> ctypes.CDLL('libpoppler-glib.8.dylib')
<CDLL 'libpoppler-glib.8.dylib', handle 7fb3ce53c520 at 0x107bea0f0>
>>> ctypes.CDLL('libcairo-gobject.2.dylib')
<CDLL 'libcairo-gobject.2.dylib', handle 7fb3ce41a490 at 0x107bd7400>
>>> ctypes.CDLL('/usr/local/lib/libpoppler-glib.8.dylib')
<CDLL '/usr/local/lib/libpoppler-glib.8.dylib', handle 7fb3ce53c520 at 0x107bea0f0>
>>> ctypes.CDLL('/usr/local/lib/libcairo-gobject.2.dylib')
<CDLL '/usr/local/lib/libcairo-gobject.2.dylib', handle 7fb3ce41a490 at 0x107bd7400>
>>> 
>>> os.environ['DYLD_FALLBACK_LIBRARY_PATH']='/usr/local/lib'
>>> ctypes.CDLL('libpoppler-glib.8.dylib')
<CDLL 'libpoppler-glib.8.dylib', handle 7fb3ce53c520 at 0x107bea0f0>
>>> ctypes.CDLL('libcairo-gobject.2.dylib')
<CDLL 'libcairo-gobject.2.dylib', handle 7fb3ce41a490 at 0x107bd7400>
>>> del os.environ['DYLD_FALLBACK_LIBRARY_PATH']
>>> 
>>> os.environ['DYLD_LIBRARY_PATH']='/usr/local/lib'
>>> ctypes.CDLL('libpoppler-glib.8.dylib')
<CDLL 'libpoppler-glib.8.dylib', handle 7fb3ce53c520 at 0x107bd73c8>
>>> ctypes.CDLL('libcairo-gobject.2.dylib')
<CDLL 'libcairo-gobject.2.dylib', handle 7fb3ce41a490 at 0x107bd7400>`

**Comment by Cimbali** [comment]
This is the same issue as #58, failing to open the libpoppler library.
