### ISSUE TITLE
Pane resize is not working

### ISSUE THREAD

**Issue by ceermonk** [Cimbali/pympress#69]
# Environment
- Ubuntu 16
- Python 2.7

# Problem
Resize is not working

# Error message
Traceback (most recent call last):
  File "/home/sp/pympress-master/pympress/builder.py", line 347, in resize_paned
    hnd = GObject.signal_handler_find(paned, GObject.SignalMatchType.ID, sig, 0, None, None, None)
TypeError: Argument 5 does not allow None as a value

# Fix 
Builder.py, Line 347:  changing the argument to 0 fixes the problem.

hnd = GObject.signal_handler_find(paned, GObject.SignalMatchType.ID, sig, 0, None, 0, 0)

**Comment by ceermonk** [comment]
Please ignore. It was perhaps a problem with my system.

**Comment by ceermonk** [comment]
The bug comes back if the argument is changed back to None. This should be looked into. Thanks.

**Comment by Cimbali** [comment]
Could you provide your gtk and gobject versions? I'm assuming you're running the pympress master from source?

**Comment by ceermonk** [comment]
gir1.2-gtk-3.0 version: 3.18.9-1ubuntu3.3  
libgtk-3-0 version: 3.18.9-1ubuntu3.3  
dpkg-query: no packages found matching python2-gi
python3-gi version: 3.20.0-0ubuntu1

Removing the last two arguments throws error:

hnd = GObject.signal_handler_find(paned, GObject.SignalMatchType.ID, sig, 0, closure = None)
TypeError: GObject.signal_handler_find() takes exactly 7 non-keyword arguments (4 given)

**Comment by Cimbali** [comment]
Sorry the python 2 package is called `python - gi`, which is the one that is interesting if you use python 2.7

**Comment by ceermonk** [comment]
The version of python-gi is 3.20.0-0ubuntu1.

In any case, setting those two parameters to 0 should not cause issues in Python 2.7.
