### ISSUE TITLE
When I run pympress nothing happens

### ISSUE THREAD

**Issue by Nagidal** [Cimbali/pympress#70]
# Environment
-  Windows 7, Microsoft Windows [Version 6.1.7601]
- Python 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)] on win32 

# Pympress
- pympress in c:\python36\lib\site-packages (1.1.2)                      
python-vlc in c:\python36\lib\site-packages (from pympress) (3.0.102)  version
- Installation method: pip install pympress

# Expected behaviour 
I'd like to see pympress open and present a pdf

# Steps to reproduce
in command line I execute "pympress" and wait for something to happen.
Alternatively, I type the pdf filename as first argument after pympress

# Problem
Nothing is happening. Noting opens. I see pympress.exe and pythonw.exe briefly appearing the in process list but they immediately disappear.
What is reported in pympress.log?
I can see no pympress.log. Neither in the system temp directory (C:\TEMP) nor in my user temp directory (%USERPROFILE%\AppData\Local\Temp)

**Comment by Nagidal** [comment]
No, PyGobject will not install for anything newer than Python 3.4. I don't really want to have two python distributions on my computer, so I'm going to look for alternatives to pygment.

**Comment by Cimbali** [comment]
Yeah @Nagidal it's a bit of a mess to compile for windows right now. The ways it works are summed up in the README, but in short there's 3 that work:
- get a precompiled binary version (they're not the latest sorry but still recent)
- go the GNU for windows way, then you can get python, gtk, pympress etc. in msys2. All packges need to be those from the msys repo, so pycairo would be mingw-w64-x86_64-python3-cairo (in msys' pacman). See the readme for the full dependencies.
- use Python 3.4 for windows and use PyGobject for windows.

I tried to use a recent Python for windows (e.g. 3.6), with a msvc-precompiled Gtk+, e.g. from https://github.com/wingtk/gvsbuild but I couldn't make it work yet. I got trouble getting the python gobject packages to find the compiled libraries correctly.
