### ISSUE TITLE
Support autostart and looping for videos

### ISSUE THREAD

**Issue by Cimbali** [Cimbali/pympress#71]
As suggested by @multiflexi in #34

**Comment by susobaco** [comment]
One question, does pympress have the option of looping in presentations? I can't find it anywhere. When I activate the timer, it only warns me of the passage of time, it doesn't change the slides automatically. Is it a bug or doesn't it have the option?

**Comment by susobaco** [comment]
And you could add these functions?. I find them very interesting.

**Comment by cpitclaudel** [comment]
I *think* this would help? https://gitlab.freedesktop.org/poppler/poppler/-/merge_requests/829

**Comment by Cimbali** [comment]
Your MR got released in Poppler 21.04.0 apparently. Let’s see when that package becomes available downstream.

**Comment by cpitclaudel** [comment]
Great.  I'm not 100% sure that this PR will help, because some software implements autostart using a trigger when the page is shown instead of using an autostart annotation, but time will tell.

**Comment by Cimbali** [comment]
Thanks a lot for your Poppler MR @cpitclaudel, autostart and looping would not have been possible without it.

**Comment by ojura** [comment]
Hi @Cimbali, I tried out 1.7.0b1 and I can't get autoplay to work. I've tried it out on Windows with an MP4 embedded with Beamer's ` \movie`.
