### ISSUE TITLE
Look into gif support

### ISSUE THREAD

**Issue by Cimbali** [Cimbali/pympress#72]
Can gifs be embedded in pdfs, specifically in with latex? What kind of poppler objects are used? Can an embedded gif be rendered directly in an overlay like the videos, maybe with a Gtk.Image?

**Comment by Cimbali** [comment]
So they can be included with a `\movie` command from the `multimedia` package, but playing the gif crashes with the following VLC error:

> xcb_xv vout display error: no available XVideo adaptor

**Comment by Cimbali** [comment]
`Gtk.Image` does the job, playing the gif, looping, etc, right off the bat.

Tried with this test code:
```
#!/usr/bin/python3

import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk

win = Gtk.Window(title="Hello World")
win.add(Gtk.Image.new_from_file('tbag.gif'))
win.connect("destroy", Gtk.main_quit)
win.show_all()

Gtk.main()
```

And the tbag.gif:
![tbag](https://user-images.githubusercontent.com/6126377/44810425-f7e08080-abd1-11e8-9322-93328bf5df1b.gif)

**Comment by Cimbali** [comment]
Embedding gifs as videos now works, without requiring VLC support. Tested with the following example (same animated gif as above): 

```
\documentclass{beamer}

\usepackage{multimedia}

\begin{document}
\begin{frame}
   \movie[width=5cm,height=5cm,poster,loop,autostart]{}{tbag.gif}
\end{frame}

\end{document}
```

**Comment by multiflexi** [comment]
Great, I can confirm this works but only when shown for the first time, when I go back and then return it works only after click, no autostart. Loop does not have any affect as it probably should not have.
