### ISSUE TITLE
Issue with multiple audio/video files on one page

### ISSUE THREAD

**Issue by multiflexi** [Cimbali/pympress#78]
# Environment
- Ubuntu 18.04
- Python 3.6.5

# Pympress
- Git
- pip

# Expected behaviour 
Playing of separate audio files on click when multiple audiovisual files are on one page. Video playback stops when next slide is presented and starts from beginning when slide is loaded again.

# Steps to reproduce
Either
`\movie[height=\textwidth,width=\textwidth,poster,autostart,showcontrols=true]{\includegraphics[width=\textwidth]{img}}{sound}`

or
`\sound{\includegraphics[width=\textwidth]{img}}{sound}`
# Problem
When using \movie for audio as Beamer documentation suggests, the audio plays but only the latter one from multiple ones on page. When combined with .webm video, the video does not play at all, even when autostart is set, poster is not shown. When combined with gif video, the video plays without any issues but continues playing even after next slide is presented - when returning to the slide the video does not start from begining.
When using \sound, the page is not rendered at all.

#Terminal log:
for \sound:
[pympress-sound.txt](https://github.com/Cimbali/pympress/files/2367196/pympress-sound.txt)
for \video there is no message from VLC because the video is not played:

```
Protocol error: bad 3 (Window); Sequence Number 5
 Opcode (20, 0) = GetProperty
 Bad resource 1483866744 (0x58720278)
 at -e line 15.
/home/jaroslav/.local/lib/python3.6/site-packages/pympress/media_overlay.py:224: Warning: value "-125" of type 'gint' is invalid or out of range for property 'margin-bottom' of type 'gint'
  self.media_overlay.props.margin_bottom = ph * self.relative_margins.y1
/home/jaroslav/.local/lib/python3.6/site-packages/pympress/media_overlay.py:224: Warning: value "-48" of type 'gint' is invalid or out of range for property 'margin-bottom' of type 'gint'
  self.media_overlay.props.margin_bottom = ph * self.relative_margins.y1
/home/jaroslav/.local/lib/python3.6/site-packages/pympress/media_overlay.py:224: Warning: value "-57" of type 'gint' is invalid or out of range for property 'margin-bottom' of type 'gint'
  self.media_overlay.props.margin_bottom = ph * self.relative_margins.y1
/home/jaroslav/.local/lib/python3.6/site-packages/pympress/media_overlay.py:224: Warning: value "-22" of type 'gint' is invalid or out of range for property 'margin-bottom' of type 'gint'
  self.media_overlay.props.margin_bottom = ph * self.relative_margins.y1
```

**Comment by Cimbali** [comment]
There seem to be multiple issues with multiple medias on a single slide afaict:
- Without autoplay, there is no way to play a media if there is no poster, but this has to be solved by #71.
- There seems to be mistakes as to which media gets clicked when there are multiple on the page. Those seem mostly click-handling related, and should be fixable (that is I believe what you mean by "only the latter one from multiple ones on page.")
- I have very different sound levels between the first and second time I play a media. I believe one playback might be muted the first time, but both playbacks un-muted starting the second time they're played.
- The `\sound` does not seem supported in poppler (I currently have version 0.66) as it returns a poppler action of type "POPPLER_ACTION_UNKNOWN". However `\movie` with a sound file works fine.

However what I could not reproduce:
- When going away from a slide with gif+video with sound, the video and sound stop correctly
- When returning to the gif+video with sound slide, the video momentarily appears to be at the same spot than when I left the slide but resets to time 0 before playing.
- The message reported in your pympress.log does not appear with any test for me.

**Comment by Cimbali** [comment]
It seems the wrong-media issue is a closure problem. The lambda that starts playing the media does not capture the media but uses the last one that appeared in the scope where the lambda is created.

**Comment by Cimbali** [comment]
@multiflexi Can you test if multiple medias work now? It's good for me.

**Comment by multiflexi** [comment]
It works great now with multiple \video on one slide, it is possible to play the right videos on click, thank you very much for the fix.
Regarding the stuff you were not able to reproduce: looped \video with gifs are not played from beginning when showing the slide for second time, it just continues in background but probably just until it finishes. To put it simply the gif playback continues if you go quickly from one slide to another and back and do it repeatedly. It is not a big deal but I think the desired behavior is the same as is for e.g. .webm video playback which stops correctly and then plays from beginning when your return from subsequent slide.

**Comment by Cimbali** [comment]
@multiflexi gifs should be restarting from the beginning every time the slide is re-opened now.
