### ISSUE TITLE
Won't start on Mac OS X (10.12.6)

### ISSUE THREAD

**Issue by karchjd** [Cimbali/pympress#80]
# Environment
- Mac OS X (10.12.6)
- Python 3.7.0

# Pympress
- Latest pip version (1.2.0).
- Installation method: `python3 -m pip install pympress`

# Expected behaviour 
Starting pympress

# Steps to reproduce
`pympress`

# Problem
Instead of pympress starting, I get the following error ouput:
```
(pympress:68273): Gtk-WARNING **: 11:44:31.962: Locale not supported by C library.
	Using the fallback 'C' locale.
Traceback (most recent call last):
  File "/usr/local/bin/pympress", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/pympress/__main__.py", line 113, in main
    gui = ui.UI(ett, name)
  File "/usr/local/lib/python3.7/site-packages/pympress/ui.py", line 190, in __init__
    self.laser = pointer.Pointer(self.config, self)
  File "/usr/local/lib/python3.7/site-packages/pympress/pointer.py", line 73, in __init__
    self.load_pointer(default)
  File "/usr/local/lib/python3.7/site-packages/pympress/pointer.py", line 90, in load_pointer
    self.pointer = util.get_icon_pixbuf(name + '.png')
  File "/usr/local/lib/python3.7/site-packages/pympress/util.py", line 143, in get_icon_pixbuf
    return GdkPixbuf.Pixbuf.new_from_file(__get_resource_path('share', 'pixmaps', name))
gi.repository.GLib.Error: gdk-pixbuf-error-quark: Couldn’t recognize the image file format for file “/usr/local/lib/python3.7/site-packages/pympress/share/pixmaps/pointer_red.png” (3)
```

I don't see a pympress.log in any of the unix locations.

**Comment by Cimbali** [comment]
OK, that's interesting. Did you follow the install procedure? On Mac OS X, it is:
```
brew install gtk+3 poppler gobject-introspection
```

Can you also check if the file `/usr/local/lib/python3.7/site-packages/pympress/share/pixmaps/pointer_red.png` exists and if you can open it?

**Comment by Cimbali** [comment]
Well, gdk-pixbuf is depending on gtk+ in brew so it should be installed already. Can you try the following minimal example? If it fails, could you also try with a jpeg image?

```
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import GdkPixbuf
for fmt in GdkPixbuf.Pixbuf.get_formats():
    print(fmt.get_extensions())
GdkPixbuf.Pixbuf.new_from_file('/usr/local/lib/python3.7/site-packages/pympress/share/pixmaps/pointer_red.png')
```

This and other issues we have on OSX are probably related to gobject introspection files (`.gir`) and finding/loading the appropriate libraries. See for example problems encountered by the project-freezing pyinstaller in pyinstaller/pyinstaller#2596 and related bugs.

**Comment by Cimbali** [comment]
Can you maybe also try installiong `cairo` via homebrew? We use that rendering library but it doesn't appear to be in the dependencies of the gtk+3 recipe.

**Comment by karchjd** [comment]
I installed cairo via homebrew with `brew install cairo`. It seems as if it was already installed. As homebrew answered with

```
Warning: cairo 1.14.12 is already installed and up-to-date
To reinstall 1.14.12, run `brew reinstall cairo`
```

pympress still fails with the same error. The minimal example you provided also fails with the same error 

```
gdkpixpuf_mwe.py:3: PyGIWarning: GdkPixbuf was imported without specifying a version first. Use gi.require_version('GdkPixbuf', '2.0') before import to ensure that the right version gets loaded.
  from gi.repository import GdkPixbuf
['svg', 'svgz', 'svg.gz']
Traceback (most recent call last):
  File "gdkpixpuf_mwe.py", line 6, in <module>
    GdkPixbuf.Pixbuf.new_from_file('/usr/local/lib/python3.7/site-packages/pympress/share/pixmaps/pointer_red.png')
gi.repository.GLib.Error: gdk-pixbuf-error-quark: Couldn’t recognize the image file format for file “/usr/local/lib/python3.7/site-packages/pympress/share/pixmaps/pointer_red.png” (3)
```

I also tried this with another png and a jpg, which also resulted in the `Couldn't recognize the image file format` error. So, this error is not related to pympress and rather to my broken installation of GdkPixbug? My python knowledge is pretty rusty but if you point my to the correct place, I will report the error there.

**Comment by Cimbali** [comment]
The error is definitely not in pympress. It seems you only have the pixbuf loaders to load svg images, not png or jpeg. Those should have appeared in the `GdkPixbuf.Pixbuf.get_formats()` output. For example the ouput on my system is:
```
['dng', 'cr2', 'crw', 'nef', 'orf', 'pef', 'arw', 'erf', 'mrw']
['ani']
['bmp']
['gif']
['icns']
['ico', 'cur']
['jpeg', 'jpe', 'jpg']
['png']
['pnm', 'pbm', 'pgm', 'ppm']
['qtif', 'qif']
['svg', 'svgz', 'svg.gz']
['tga', 'targa']
['tiff', 'tif']
['xbm']
['xpm']
```

I'm afraid I don't quite know where to go from there, having never had a mac myself and without helpful results after googling a while. If it's an error in the installation of Gdk-Pixbuf, maybe you can go through the [Homebrew troubleshooting checklist](https://docs.brew.sh/Troubleshooting)? Sorry I can't be of more help.
