### ISSUE TITLE
Rearrange panels dynamically

### ISSUE THREAD

**Issue by Cimbali** [Cimbali/pympress#83]
Panels can be adjusted in the configuration file. A UX to do it would be great.

**Comment by Morfit** [comment]
Nice feature for me too. Sometimes **note** serves just as a supplement, **slide** is the one that we should focus on.

**Comment by Cimbali** [comment]
@Morfit  you can currently resize the panels by dragging the handle in between the two. That's about all you can do dynamically for now.

I'm wondering if this dynamic rearrangement should be a number of predefined configurations between which the user can switch (rather easy to implement) or if a more free form way is better (e.g. drag & drop, like tool panels in inkscape or gimp).
