### ISSUE TITLE
Problem with rendering shadows

### ISSUE THREAD

**Issue by jopohl** [Cimbali/pympress#84]
# Environment
- Operating system and version: Arch Linux
- Python version: 3.7.1

# Pympress
- version: 1.2.0
- Installation method: pip

# Expected behaviour 
Display a beamer presentation with shadows in theme.

# Problem
Shadows on boxes and itemize bullets are not rendered correctly, as shown in this screenshot:
![grafik](https://user-images.githubusercontent.com/18219846/49364023-825de200-f6e3-11e8-8653-f79a8b1a0d20.png)

Log is empty:
```
$ cat /tmp/pympress.log 

```

**Comment by Cimbali** [comment]
Hi, thanks for reporting the bug.

The shadows seem to be rendered correctly except for the black corners which shouldn't be there, is that right? Seems like a transparency issue. 

Can you try to convert the page `p` that you're showing of your pdf to jpeg, to see if it's a poppler/cairo rendering problem or a pympress issue? 

    pdfcairo -l p -f p -jpeg file.pdf

**Comment by jopohl** [comment]
Hey, thanks for the fast response!

I agree, it seems to be an issue with the transparency.

I converted the page using ```pdftocairo``` and the result looks fine to me:

![bildschirmfoto_2018-12-03_12-12-36](https://user-images.githubusercontent.com/18219846/49370541-c0afcd00-f6f4-11e8-9b8b-1f009d522f64.png)

**Comment by Cimbali** [comment]
Well, I can not seem to reproduce this anymore, with poppler 0.81 and cairo 1.16.0. I suppose it was transparency handling that got improved in one of our dependencies.

Feel free to reopen with specific version numbers of the dependencies (all shown in the log file, usually in `~/.cache/pympress.log`) if you still have this bug.
