### ISSUE TITLE
support vertical layout

### ISSUE THREAD

**Issue by vzaliva** [Cimbali/pympress#85]
I render my beamer presentations with notes slide below, not at the right. It is more convenient this way when I am editing them with live-preview on the 2nd screen which is in portrait mode. I can view them now with `pdfpc -c --notes=bottom slides.pdf`. I would like to do the same with pympress. Please add to pympress support for such layouts.

```
\setbeameroption{show notes on second screen=bottom}
```

**Comment by Cimbali** [comment]
This is interesting, I will look into it. Let me comment on some workarounds for now. Do you use a normal pdf viewer for editing / live-preview ? Or pympress/pdfpc ?
The current git version of pympress automatically reloads (live-preview) files that are modified.

Using pympress for live preview, try compiling with notes on second screen to the right and setting in the layout section of your pympress configuration file (most likely `~/.config/pympress`) the following: `notes = {"resizeable": true, "children": ["current", "notes", "next"], "proportions": [0.4, 0.4, 0.2], "orientation": "vertical"}` before opening pympress.
#83 should take care of doing this without the need to edit the config file.

Alternately if you use a normal pdf viewer for live-preview, the workaround would be to compile the final version for the presentation with notes on the right.

**Comment by vzaliva** [comment]
Thank you for the workarounds. They are helpful. 
I still hope you will add orientation command line option in the future. I am no python programmer but I quickly looked at the code and it seems to very simple patch. It just calculating page offsets based on orientation. Also overriding heuristic which detects notes presence based on the page size with command line option. I suggest command line option like in `pdfpc`:

       -n, --notes=P
              Position of notes on the PDF page. Position can be either left, right, top or
              bottom. Disable slide auto-grouping (Default: none)

**Comment by Cimbali** [comment]
It is not very hard indeed, but there are a couple places in the code where we rely on the second slide being left to compute coordinates (of the top off my head, for links and medias, but there are probably more).
