### ISSUE TITLE
No module named pympress.__main__

### ISSUE THREAD

**Issue by JasonB579** [Cimbali/pympress#96]
# Environment
- Operating system and version:
    Arch Linux: 4.20.3
- Python version:
    Python 3.7.2 and Python 2.7.15

# Pympress
Installed through pip3 and pip separately. When I had only installed it to with pip3 I got a different "No module" error for just the pympress module.

# Expected behaviour 
I'm trying to start pympress

# Steps to reproduce
Running pympress and pympress3 from the terminal

# Problem
Instead of pympress starting, I get an error: `ImportError: No module named pympress.__main__`

There's no pympress.log file.

I've made sure to install all of the dependencies, and I'm not really sure what I'm missing at this point.

**Comment by Cimbali** [comment]
There was a circular import problem at some point, which should have been fixed in the latest release.

Do you have several python versions installed? Maybe anaconda? Can you check pympress is in the python module path? Can you also try running with `python3 - 'm pympress`?

**Comment by JasonB579** [comment]
I have two versions of python installed, both python2 and python3. I do not believe I have anaconda installed. I've tried to install pympress with both python2 and python3.

Running `python3 -m pympress` gives the output:
`/usr/bin/python3: No module named pympress`

Running `python3 -m pip list` gives:
```Package         Version
--------------- ----------
appdirs         1.4.3
argh            0.26.2
arxiv2bib       1.0.8
beautifulsoup4  4.7.1
bibtexparser    1.1.0
btrfsutil       1.1.0
CacheControl    0.12.5
caffeine-ng     3.4.2
chardet         3.0.4
click           6.7
colorama        0.4.1
configparser    3.5.0
cycler          0.10.0
distlib         0.2.8
distro          1.3.0
docopt          0.6.2
evdev           1.1.2
ewmh            0.1.6
filetype        1.0.2
future          0.17.1
habanero        0.6.2
html5lib        1.0.1
idna            2.8
isbnlib         3.9.4
keyutils        0.5
kiwisolver      1.0.1
lensfun         0.3.2
lit             0.7.1.dev0
lockfile        0.12.2
lutris          0.5.0
matplotlib      3.0.2
msgpack         0.6.1
nose            1.3.7
numpy           1.16.0
packaging       19.0
papis           0.7.5
parse           1.6.5
pathtools       0.1.2
pep517          0.5.0
Pillow          5.4.1
pip             18.1
progress        1.4
prompt-toolkit  2.0.7
pycairo         1.18.0
PyGObject       3.30.4
pylibgen        2.0.1
pympress        1.3.0
pyparser        1.0
pyparsing       2.3.1
python-dateutil 2.7.5
python-slugify  1.2.6
python-vlc      3.0.4106
python-xlib     0.24
pytoml          0.1.20
pyxdg           0.26
PyYAML          3.13
ranger-fm       1.9.2
requests        2.21.0
retrying        1.3.3
setproctitle    1.1.10
setuptools      40.7.3
six             1.12.0
soupsieve       1.7.2
team            1.0
udiskie         1.7.5
Unidecode       1.0.23
urllib3         1.24.1
watchdog        0.9.0
wcwidth         0.1.7
webencodings    0.5.1
wheel           0.32.3
wordcloud       1.5.0
```
Pympress appears to be in that list, but none of my versions of python seem to be able to find it...

Running that last chunk of code just gives back `[]`

**Comment by Blaisorblade** [comment]
Same problem here. Downloading the package from https://pypi.org/project/pympress/1.3.0/#files suggests that Pympress is not getting installed (unlike for 1.2.1); installing from Github fails as well, so the problem could be in the packaging instructions? But I'm not a *Python* dev so what do I know.

No sources in the downloaded archive (while there's some in 1.2.1):
```
$ unzip -l pympress-1.3.0-py2.py3-none-any.whl
Archive:  pympress-1.3.0-py2.py3-none-any.whl
  Length      Date    Time    Name
---------  ---------- -----   ----
    18092  01-26-2019 16:04   pympress-1.3.0.dist-info/LICENSE.txt
     9851  01-26-2019 16:04   pympress-1.3.0.dist-info/METADATA
      110  01-26-2019 16:04   pympress-1.3.0.dist-info/WHEEL
       84  01-26-2019 16:04   pympress-1.3.0.dist-info/entry_points.txt
        1  01-26-2019 16:04   pympress-1.3.0.dist-info/top_level.txt
      492  01-26-2019 16:04   pympress-1.3.0.dist-info/RECORD
```


```
$ ls /usr/local/lib/python3.7/site-packages/pympress
gls: cannot access '/usr/local/lib/python3.7/site-packages/pympress': No such file or directory
$ ls /usr/local/lib/python3.7/site-packages/pympress-1.3.0.dist-info/
INSTALLER  LICENSE.txt  METADATA  RECORD  WHEEL  entry_points.txt  top_level.txt
$ ls /usr/local/lib/python3.7/site-packages/
PyYAML-3.13.dist-info                     _yaml.cpython-37m-darwin.so  easy_install.py         pathtools                  pip-18.1-py3.7.egg-info   python_vlc-3.0.4106.dist-info     sitecustomize.py       vlc.py                    wheel                        wheel-0.32.3-py3.7.egg-info
__pycache__                               argh                         numpy                   pathtools-0.1.2.dist-info  pkg_resources             setuptools                        torch                  watchdog                  wheel-0.31.1-py3.7.egg-info  yaml
_watchdog_fsevents.cpython-37m-darwin.so  argh-0.26.2.dist-info        numpy-1.15.0.dist-info  pip                        pympress-1.3.0.dist-info  setuptools-40.6.3-py3.7.egg-info  torch-0.4.1.dist-info  watchdog-0.9.0.dist-info  wheel-0.32.2-py3.7.egg-info
```

**Comment by Blaisorblade** [comment]
@JasonB579 FWIW, while I'm no Python dev, my current workaround is `python3 -m pip install pympress-1.2.1` (USE AT YOUR RISK) to install the previous version, hope this helps you use pympress while this issue is investigated!

Indeed, I got Pympress to work this way (after #97), and seeing real 2-screen support with Beamer is amazing!

**Comment by JasonB579** [comment]
@Blaisorblade Are you sure that's the right command? I ran that and it says it can't find that version.

For now my solution is just to install it from the AUR. It's not really a "solution" per se, but at least I'll have pympress working for my next presentation.

**Comment by JasonB579** [comment]
Probably not great to mix, but I've got a desktop as well that I can at least test the more raw python solutions on, even if it's not necessarily immediately necessary.

**Comment by Cimbali** [comment]
Turns out since 3f202e9 the Pympress package did not contain any actual pympress in it, only meta data. You should be good after doing a `pip install --user --upgrade pympress`.

**Comment by Blaisorblade** [comment]
@Cimbali Yeah almost! 1.3.1 is not on PyPI (https://pypi.org/project/pympress/1.3.0/#files), but it worked from GitHub.

**Comment by Cimbali** [comment]
Well it was a little late yesterday, I might have missed an error in the upload. It's done now!

**Comment by Blaisorblade** [comment]
Yep, works now thanks!
